# -*- coding: UTF-8 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: azisetup.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid
import wx.animate

# Custom source
from awc.controls.textctrl import TextCtrl, TextCtrl_LC
from awc.controls.datectrl import DateCtrl
from awc.controls.numctrl import NumCtrl
from awc.controls.radiobox import RadioBox
from awc.controls.checkbox import CheckBox
from awc.controls.linktable import LinkTable

from awc.controls.entries import FolderEntryCtrl

from anag.basetab import WorkZoneNotebook, PhotoContainerPanel

from anag.mag import MagazzDialog

import Env
bt = Env.Azienda.BaseTab


class ScorpIvaRadioBox(RadioBox):
    def __init__(self, *args, **kwargs):
        RadioBox.__init__(self, *args, **kwargs)
        self.SetDataLink(values=' 1')

class UnoZeroCheckBox(CheckBox):
    def __init__(self, *args, **kwargs):
        CheckBox.__init__(self, *args, **kwargs)
        self.SetDataLink(values={True: 1, False: 0})
    
    def SetValue(self, v):
        if isinstance(v, (str, unicode)):
            v = int(v)
        CheckBox.SetValue(self, v)


class SovrapposizioneRadioBox(RadioBox):

    def __init__(self, *args, **kwargs):
        RadioBox.__init__(self, *args, **kwargs)
        self.SetDataLink(values=(0,1))

class RitAccCheckBox(UnoZeroCheckBox):

    def __init__(self, *args, **kwargs):
        UnoZeroCheckBox.__init__(self, *args, **kwargs)
        self.Bind(wx.EVT_CHECKBOX, self.OnRitAccChanged)

    def OnRitAccChanged(self, event):
        for name in 'per com'.split():
            self.GetParent().FindWindowByName('setup_con%sritacc'%name).Enable(self.IsChecked())
        event.Skip()

class MagProvMovRadioBox(RadioBox):

    def __init__(self, *args, **kwargs):
        RadioBox.__init__(self, *args, **kwargs)
        self.SetDataLink(values=(" ", "E"))



# Window functions

ID_NOTEBOOK = 15000
ID_BTNOK = 15001

def AziendaSetup( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item2 = WorkZoneNotebook( parent, ID_NOTEBOOK, wx.DefaultPosition, wx.DefaultSize, 0 )
    item1 = item2
    
    item3 = wx.Panel( item2, -1 )
    DatiAziendaFunc(item3, False)
    item2.AddPage( item3, "Dati azienda" )

    item4 = wx.Panel( item2, -1 ); item4.SetName('contabpanel')
    ContabSetup(item4, False)
    item2.AddPage( item4, "ContabilitÃ " )

    item5 = wx.Panel( item2, -1 ); item5.SetName('magazzpanel')
    MagazzSetup(item5, False)
    item2.AddPage( item5, "Magazzino" )

    item6 = wx.Panel( item2, -1 ); item6.SetName('opzionipanel')
    OpzioniFunc(item6, False)
    item2.AddPage( item6, "Opzioni" )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item7 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item8 = wx.Button( parent, ID_BTNOK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.SetDefault()
    item8.SetName( "btnok" )
    item7.Add( item8, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.Add( item7, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_TEXT = 15002
ID_ESERCIZIOGG = 15003
ID_ESERCIZIOMM = 15004
ID_ESERCIZIOERR = 15005
ID_CONSOVGES = 15006
ID_RADIOBOX = 15007
ID_CONTABVAL = 15008
ID_CONTABDECIMP = 15009
ID_CHECKBOX = 15010
ID_CONBILRICL = 15011
ID_CONBILRCEE = 15012
ID_CONATTRITACC = 15013
ID_CONPERRITACC = 15014
ID_CONCOMRITACC = 15015

def ContabSetup( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item2 = wx.StaticBox( parent, -1, "Esercizio contabile" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    
    item3 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item4 = wx.StaticText( parent, ID_TEXT, "Giorno e mese di inizio dell'esercizio contabile:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item4, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item5 = NumCtrl( parent, integerWidth=2, allowNegative=False); item5.SetName('setup_esercizio_startgg')
    item3.Add( item5, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item6 = wx.StaticText( parent, ID_TEXT, "/", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item6, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 5 )

    item7 = NumCtrl( parent, integerWidth=2, allowNegative=False); item7.SetName('setup_esercizio_startmm')
    item3.Add( item7, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item8 = wx.StaticText( parent, ID_ESERCIZIOERR, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.SetForegroundColour( wx.RED )
    item8.SetName( "esercizio_err" )
    item3.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item3.AddGrowableCol( 4 )

    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item9 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item10 = SovrapposizioneRadioBox( parent, ID_CONSOVGES, "Chiusure contabili", wx.DefaultPosition, wx.DefaultSize, 
        ["Senza sovrapposizione d'esercizio","Con sovrapposizione d'esercizio"] , 1, wx.RA_SPECIFY_COLS )
    item10.SetName( "setup_consovges" )
    item9.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item11 = RadioBox( parent, ID_RADIOBOX, "Tipo di gestione dell'IVA", wx.DefaultPosition, wx.DefaultSize, 
        ["Ordinaria","Semplificata"] , 1, wx.RA_SPECIFY_COLS )
    item11.SetName( "setup_tipo_contab" )
    item9.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item12 = RadioBox( parent, ID_RADIOBOX, "PeriodicitÃ  di liquidazione IVA", wx.DefaultPosition, wx.DefaultSize, 
        ["Mensile","Trimestrale"] , 1, wx.RA_SPECIFY_COLS )
    item12.SetName( "setup_liqiva_periodic" )
    item9.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item9.AddGrowableCol( 0 )

    item9.AddGrowableCol( 1 )

    item0.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item14 = wx.StaticBox( parent, -1, "Impostazione valuta di conto" )
    item13 = wx.StaticBoxSizer( item14, wx.VERTICAL )
    
    item15 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item16 = wx.StaticText( parent, ID_TEXT, "Valuta di conto:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item15.Add( item16, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item17 = LinkTable(parent, ID_CONTABVAL ); item17.SetDataLink( bt.TABNAME_VALUTE, "setup_contab_valcon", None); item17.SetObligatory(True)
    item15.Add( item17, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item18 = wx.StaticText( parent, ID_TEXT, "Numero di decimali su importi:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item15.Add( item18, 0, wx.ALIGN_CENTER|wx.LEFT|wx.BOTTOM, 5 )

    item19 = NumCtrl( parent, integerWidth=2, allowNegative=False); item19.SetName('setup_contab_decimp')
    item15.Add( item19, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item15.AddGrowableCol( 1 )

    item13.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item21 = wx.StaticBox( parent, -1, "Gestione fidi clienti" )
    item20 = wx.StaticBoxSizer( item21, wx.VERTICAL )
    
    item22 = UnoZeroCheckBox( parent, ID_CHECKBOX, "Attiva la gestione dei fidi sui clienti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item22.SetName( "setup_gesfidicli" )
    item20.Add( item22, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item20, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item24 = wx.StaticBox( parent, -1, "Bilanci" )
    item23 = wx.StaticBoxSizer( item24, wx.HORIZONTAL )
    
    item25 = UnoZeroCheckBox( parent, ID_CONBILRICL, "Attiva riclassificazioni di bilancio", wx.DefaultPosition, wx.DefaultSize, 0 )
    item25.SetName( "setup_conbilricl" )
    item23.Add( item25, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item26 = UnoZeroCheckBox( parent, ID_CONBILRCEE, "Attiva riclassificazioni CEE", wx.DefaultPosition, wx.DefaultSize, 0 )
    item26.SetName( "setup_conbilrcee" )
    item23.Add( item26, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item23, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item28 = wx.StaticBox( parent, -1, "Ritenute d'Acconto" )
    item27 = wx.StaticBoxSizer( item28, wx.HORIZONTAL )
    
    item29 = RitAccCheckBox( parent, ID_CONATTRITACC, "Attiva gestione", wx.DefaultPosition, wx.DefaultSize, 0 )
    item29.SetName( "setup_conattritacc" )
    item27.Add( item29, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item30 = wx.StaticText( parent, ID_TEXT, "Calcolo %:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item27.Add( item30, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item31 = NumCtrl( parent, integerWidth=2, fractionWidth=2, allowNegative=False); item31.SetName('setup_conperritacc')
    item27.Add( item31, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item32 = wx.StaticText( parent, ID_TEXT, "da applicare all'imponibile in % del:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item27.Add( item32, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item33 = NumCtrl( parent, integerWidth=3, fractionWidth=2, allowNegative=False); item33.SetName('setup_concomritacc')
    item27.Add( item33, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item27, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_MAGDEFAULT = 15016
ID_magdec_qta = 15017
ID_magdec_prez = 15018
ID_magricpre = 15019
ID_MAGPZCONF = 15020
ID_MAGPZGRIP = 15021
ID_MAGSCORPCOS = 15022
ID_MAGSCORPPRE = 15023
ID_FOREIGN = 15024
ID_MAGSCOCAT = 15025
ID_MAGGESACC = 15026
ID_MAGEANPREFIX = 15027
ID_MAGDATCHI = 15028
ID_MAGNUMLIS = 15029
ID_MAGDATLIS = 15030
ID_MAGBCOLIS = 15031
ID_MAGFORLIS = 15032
ID_MAGROWLIS = 15033
ID_MAGVLIFOR = 15034
ID_MAGVLIMAR = 15035
ID_MAGVLICAT = 15036
ID_MAGVLIGRU = 15037
ID_MAGERPLIS = 15038
ID_MAGESPLIS = 15039
ID_MAGVRGLIS = 15040
ID_MAGVSGLIS = 15041
ID_MAGREPLIS = 15042
ID_MAGRELLIS = 15043
ID_MAGSEPLIS = 15044
ID_MAGSELLIS = 15045
ID_MAGPPROMO = 15046
ID_MAGATTGRIP = 15047
ID_MAGCDEGRIP = 15048
ID_LINE = 15049
ID_MAGATTGRIF = 15050
ID_MAGCDEGRIF = 15051
ID_MAGAGGGRIP = 15052
ID_MAGALWGRIP = 15053
ID_MAGDATGRIP = 15054
ID_MAGNOCODEVET = 15055
ID_MAGNOCDEFVET = 15056
ID_MAGEXTRAVET = 15057
ID_MAGNOCODEDES = 15058
ID_MAGNOCDEFDES = 15059
ID_MAGIMGPROD = 15060
ID_MAGDIGSEARCH = 15061
ID_MAGRETSEARCH = 15062
ID_MAGEXCSEARCH = 15063
ID_MAGVISGIA = 15064
ID_MAGVISCOS = 15065
ID_MAGVISPRE = 15066
ID_MAGVISCPF = 15067
ID_MAGVISBCD = 15068
ID_MAGPROVATT = 15069
ID_MAGPROVCLI = 15070
ID_MAGPROVPRO = 15071
ID_MAGPROVMOV = 15072
ID_MAGPROVSEQ = 15073

def MagazzSetup( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item2 = wx.StaticBox( parent, -1, "Magazzino di default per operazioni di carico/scarico e immissione documenti" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    
    item3 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item4 = wx.StaticText( parent, ID_TEXT, "Magazzino:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item4, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 5 )

    item5 = LinkTable(parent, ID_MAGDEFAULT ); item5.SetDataLink( bt.TABNAME_MAGAZZ, "setup_magazz_default:site %s" % Env.Azienda.config.Site_name, MagazzDialog); item5.SetObligatory(True)
    item3.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item3.AddGrowableCol( 1 )

    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item6 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item8 = wx.StaticBox( parent, -1, "Numero di decimali da gestire" )
    item7 = wx.StaticBoxSizer( item8, wx.VERTICAL )
    
    item9 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item10 = wx.StaticText( parent, ID_TEXT, "QuantitÃ :", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.Add( item10, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 5 )

    item11 = NumCtrl( parent, integerWidth=2, allowNegative=False); item11.SetName('setup_magdec_qta')
    item9.Add( item11, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item12 = wx.StaticText( parent, ID_TEXT, "Prezzi unitari:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.Add( item12, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item13 = NumCtrl( parent, integerWidth=2, allowNegative=False); item13.SetName('setup_magdec_prez')
    item9.Add( item13, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item7.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item6.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item15 = wx.StaticBox( parent, -1, "Prezzi" )
    item14 = wx.StaticBoxSizer( item15, wx.VERTICAL )
    
    item16 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item17 = wx.StaticText( parent, ID_TEXT, "Ricarica predefinita:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item16.Add( item17, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item18 = NumCtrl( parent, ID_magricpre, integerWidth=3, allowNegative=False); item18.SetName('setup_magricpre')
    item16.Add( item18, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item14.Add( item16, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item6.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item20 = wx.StaticBox( parent, -1, "Confezioni" )
    item19 = wx.StaticBoxSizer( item20, wx.VERTICAL )
    
    item21 = UnoZeroCheckBox( parent, ID_MAGPZCONF, "Gestisci", wx.DefaultPosition, wx.DefaultSize, 0 )
    item21.SetName( "setup_magpzconf" )
    item19.Add( item21, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item22 = UnoZeroCheckBox( parent, ID_MAGPZGRIP, "Su griglie", wx.DefaultPosition, wx.DefaultSize, 0 )
    item22.SetName( "setup_magpzgrip" )
    item19.Add( item22, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item6.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item6.AddGrowableCol( 0 )

    item6.AddGrowableCol( 1 )

    item0.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item23 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item24 = ScorpIvaRadioBox( parent, ID_MAGSCORPCOS, "I costi su scheda prodotto sono:", wx.DefaultPosition, wx.DefaultSize, 
        ["Imponibili: l'IVA sarÃ  aggiunta","Ivati: l'IVA sarÃ  scorporata"] , 1, wx.RA_SPECIFY_COLS )
    item24.SetName( "setup_magscorpcos" )
    item23.Add( item24, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item25 = ScorpIvaRadioBox( parent, ID_MAGSCORPPRE, "I prezzi su scheda prodotto sono:", wx.DefaultPosition, wx.DefaultSize, 
        ["Imponibili: l'IVA sarÃ  aggiunta","Ivati: l'IVA sarÃ  scorporata"] , 1, wx.RA_SPECIFY_COLS )
    item25.SetName( "setup_magscorppre" )
    item23.Add( item25, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item23.AddGrowableCol( 0 )

    item23.AddGrowableCol( 1 )

    item0.Add( item23, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item26 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item28 = wx.StaticBox( parent, -1, "Gestisci" )
    item27 = wx.StaticBoxSizer( item28, wx.VERTICAL )
    
    item29 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item30 = wx.StaticText( parent, ID_TEXT, "Ricariche:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item29.Add( item30, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item31 = NumCtrl(parent, ID_FOREIGN, integerWidth=1, allowNegative=False); item31.SetName('setup_magnumric'); item31.SetToolTipString("Indicare il numero delle ricariche da gestire (0-6)")
    item29.Add( item31, 0, wx.ALIGN_CENTER|wx.LEFT|wx.BOTTOM, 5 )

    item32 = wx.StaticText( parent, ID_TEXT, "Sconti:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item29.Add( item32, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item33 = NumCtrl(parent, ID_FOREIGN, integerWidth=1, allowNegative=False); item33.SetName('setup_magnumsco'); item33.SetToolTipString("Indicare il numero degli sconti da gestire (0-6)")
    item29.Add( item33, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item27.Add( item29, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item26.Add( item27, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item35 = wx.StaticBox( parent, -1, "" )
    item34 = wx.StaticBoxSizer( item35, wx.VERTICAL )
    
    item36 = UnoZeroCheckBox( parent, ID_MAGSCOCAT, "Attiva sconti per categoria", wx.DefaultPosition, wx.DefaultSize, 0 )
    item36.SetName( "setup_magscocat" )
    item34.Add( item36, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item37 = UnoZeroCheckBox( parent, ID_MAGGESACC, "Attiva gestione acconti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item37.SetName( "setup_maggesacc" )
    item34.Add( item37, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item26.Add( item34, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item39 = wx.StaticBox( parent, -1, "Codifica barcodes" )
    item38 = wx.StaticBoxSizer( item39, wx.HORIZONTAL )
    
    item40 = wx.StaticText( parent, ID_TEXT, "EAN13 C.C.:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item38.Add( item40, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item41 = wx.TextCtrl( parent, ID_MAGEANPREFIX, "", wx.DefaultPosition, [30,-1], 0 )
    item41.SetName( "setup_mageanprefix" )
    item38.Add( item41, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item26.Add( item38, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item43 = wx.StaticBox( parent, -1, "Chiusura" )
    item42 = wx.StaticBoxSizer( item43, wx.HORIZONTAL )
    
    item44 = wx.StaticText( parent, ID_TEXT, "Data ultima chiusura magazzino:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item42.Add( item44, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item45 = DateCtrl( parent, ID_MAGDATCHI, "", wx.DefaultPosition, [80,-1], 0 )
    item45.SetName( "setup_magdatchi" )
    item42.Add( item45, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item26.Add( item42, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item26.AddGrowableCol( 0 )

    item0.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item46 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item48 = wx.StaticBox( parent, -1, "Gestione Listini di vendita" )
    item47 = wx.StaticBoxSizer( item48, wx.VERTICAL )
    
    item49 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item50 = wx.StaticText( parent, ID_TEXT, "Num.Listini:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item49.Add( item50, 0, wx.ALIGN_CENTER|wx.BOTTOM, 5 )

    item51 = NumCtrl(parent, ID_MAGNUMLIS, integerWidth=1, allowNegative=False); item51.SetName('setup_magnumlis'); item51.SetToolTipString("Indicare il numero dei listini da gestire (0-9)")
    item49.Add( item51, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item52 = UnoZeroCheckBox( parent, ID_MAGDATLIS, "Per data", wx.DefaultPosition, wx.DefaultSize, 0 )
    item52.SetToolTip( wx.ToolTip("Attiva la gestione dei listini per data") )
    item52.SetName( "setup_magdatlis" )
    item49.Add( item52, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item47.Add( item49, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item53 = wx.BoxSizer( wx.HORIZONTAL )
    
    item54 = UnoZeroCheckBox( parent, ID_MAGBCOLIS, "Barcode", wx.DefaultPosition, wx.DefaultSize, 0 )
    item54.SetToolTip( wx.ToolTip("Attiva la gestione dei listini per data") )
    item54.SetName( "setup_magbcolis" )
    item53.Add( item54, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item55 = UnoZeroCheckBox( parent, ID_MAGFORLIS, "Cod.Forn.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item55.SetToolTip( wx.ToolTip("Attiva la codifica prodotto del fornitore sul listino") )
    item55.SetName( "setup_magforlis" )
    item53.Add( item55, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP, 5 )

    item56 = UnoZeroCheckBox( parent, ID_MAGROWLIS, "Su riga", wx.DefaultPosition, wx.DefaultSize, 0 )
    item56.SetToolTip( wx.ToolTip("Attiva la selezione del listino su ogni riga del documento") )
    item56.SetName( "setup_magrowlis" )
    item53.Add( item56, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP, 5 )

    item47.Add( item53, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item46.Add( item47, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item58 = wx.StaticBox( parent, -1, "Listini variabili per:" )
    item57 = wx.StaticBoxSizer( item58, wx.VERTICAL )
    
    item59 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item60 = UnoZeroCheckBox( parent, ID_MAGVLIFOR, "Fornit", wx.DefaultPosition, wx.DefaultSize, 0 )
    item60.SetName( "setup_magvlifor" )
    item59.Add( item60, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item61 = UnoZeroCheckBox( parent, ID_MAGVLIMAR, "Marca", wx.DefaultPosition, wx.DefaultSize, 0 )
    item61.SetName( "setup_magvlimar" )
    item59.Add( item61, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item62 = UnoZeroCheckBox( parent, ID_MAGVLICAT, "Categ.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item62.SetName( "setup_magvlicat" )
    item59.Add( item62, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item63 = UnoZeroCheckBox( parent, ID_MAGVLIGRU, "Gruppo", wx.DefaultPosition, wx.DefaultSize, 0 )
    item63.SetName( "setup_magvligru" )
    item59.Add( item63, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item57.Add( item59, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item46.Add( item57, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item65 = wx.StaticBox( parent, -1, "Su prodotto:" )
    item64 = wx.StaticBoxSizer( item65, wx.VERTICAL )
    
    item66 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item67 = wx.StaticText( parent, ID_TEXT, "Ricar:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item66.Add( item67, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item68 = NumCtrl(parent, ID_MAGERPLIS, integerWidth=1, allowNegative=False); item68.SetName('setup_magerplis'); item68.SetToolTipString("Indicare il numero delle ricariche del prodotto da gestire (0-3)")
    item66.Add( item68, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item69 = wx.StaticText( parent, ID_TEXT, "Sconti:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item66.Add( item69, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item70 = NumCtrl(parent, ID_MAGESPLIS, integerWidth=1, allowNegative=False); item70.SetName('setup_magesplis'); item70.SetToolTipString("Indicare il numero delle scontistiche del prodotto da gestire (0-3)")
    item66.Add( item70, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item64.Add( item66, 0, wx.ALIGN_CENTER, 5 )

    item46.Add( item64, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item72 = wx.StaticBox( parent, -1, "Su gruppo pr.:" )
    item71 = wx.StaticBoxSizer( item72, wx.VERTICAL )
    
    item73 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item74 = wx.StaticText( parent, ID_TEXT, "Ricar:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item73.Add( item74, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item75 = NumCtrl(parent, ID_MAGVRGLIS, integerWidth=1, allowNegative=False); item75.SetName('setup_magvrglis'); item75.SetToolTipString("Indicare il numero delle ricariche del gruppo prezzi da visualizzare (0-3)")
    item73.Add( item75, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item76 = wx.StaticText( parent, ID_TEXT, "Sconti:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item73.Add( item76, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item77 = NumCtrl(parent, ID_MAGVSGLIS, integerWidth=1, allowNegative=False); item77.SetName('setup_magvsglis'); item77.SetToolTipString("Indicare il numero delle scontistiche del gruppo prezzi da visualizzare (0-3)")
    item73.Add( item77, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item71.Add( item73, 0, wx.ALIGN_CENTER, 5 )

    item46.Add( item71, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item79 = wx.StaticBox( parent, -1, "Visualizza %effettiva:" )
    item78 = wx.StaticBoxSizer( item79, wx.VERTICAL )
    
    item80 = wx.FlexGridSizer( 0, 3, 0, 0 )
    
    item81 = wx.StaticText( parent, ID_TEXT, "Ricarica:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item80.Add( item81, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item82 = UnoZeroCheckBox( parent, ID_MAGREPLIS, "Prezzo p.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item82.SetToolTip( wx.ToolTip("Attiva la visualizzazione della ricarica effettiva del prezzo al pubblico rispetto al costo ultimo") )
    item82.SetName( "setup_magreplis" )
    item80.Add( item82, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item83 = UnoZeroCheckBox( parent, ID_MAGRELLIS, "Listino", wx.DefaultPosition, wx.DefaultSize, 0 )
    item83.SetToolTip( wx.ToolTip("Attiva la visualizzazione della ricarica effettiva di ogni listino rispetto al costo ultimo") )
    item83.SetName( "setup_magrellis" )
    item80.Add( item83, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item84 = wx.StaticText( parent, ID_TEXT, "Sconto:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item80.Add( item84, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item85 = UnoZeroCheckBox( parent, ID_MAGSEPLIS, "Prezzo p.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item85.SetToolTip( wx.ToolTip("Attiva la visualizzazione dello sconto effettivo del costo ultimo rispetto al prezzo al pubblico") )
    item85.SetName( "setup_magseplis" )
    item80.Add( item85, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item86 = UnoZeroCheckBox( parent, ID_MAGSELLIS, "Listino", wx.DefaultPosition, wx.DefaultSize, 0 )
    item86.SetToolTip( wx.ToolTip("Attiva la visualizzazione dello sconto effettivo del costo ultimo rispetto ad ogni listino") )
    item86.SetName( "setup_magsellis" )
    item80.Add( item86, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item78.Add( item80, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item46.Add( item78, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item88 = wx.StaticBox( parent, -1, "Promoz." )
    item87 = wx.StaticBoxSizer( item88, wx.HORIZONTAL )
    
    item89 = UnoZeroCheckBox( parent, ID_MAGPPROMO, "Attiva", wx.DefaultPosition, wx.DefaultSize, 0 )
    item89.SetToolTip( wx.ToolTip("Attiva le condizioni promozionali sui prodotti") )
    item89.SetName( "setup_magppromo" )
    item87.Add( item89, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item46.Add( item87, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item46.AddGrowableCol( 1 )

    item46.AddGrowableCol( 2 )

    item46.AddGrowableCol( 3 )

    item0.Add( item46, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item90 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item92 = wx.StaticBox( parent, -1, "Griglie prezzi Clienti/Fornitori" )
    item91 = wx.StaticBoxSizer( item92, wx.HORIZONTAL )
    
    item93 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item94 = UnoZeroCheckBox( parent, ID_MAGATTGRIP, "Attiva clienti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item94.SetToolTip( wx.ToolTip("Attiva la gestione delle griglie prezzi di vendita sui clienti") )
    item94.SetName( "setup_magattgrip" )
    item93.Add( item94, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item95 = UnoZeroCheckBox( parent, ID_MAGCDEGRIP, "Cod.esterna prodotti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item95.SetToolTip( wx.ToolTip("Attiva la codifica del prodotto sulla griglia da parte del cliente") )
    item95.SetName( "setup_magcdegrip" )
    item93.Add( item95, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item91.Add( item93, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item96 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [-1,20], wx.LI_VERTICAL )
    item91.Add( item96, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL|wx.RIGHT, 5 )

    item97 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item98 = UnoZeroCheckBox( parent, ID_MAGATTGRIF, "Attiva fornitori", wx.DefaultPosition, wx.DefaultSize, 0 )
    item98.SetToolTip( wx.ToolTip("Attiva la gestione delle griglie prezzi di acquisto sui fornitori") )
    item98.SetName( "setup_magattgrif" )
    item97.Add( item98, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item99 = UnoZeroCheckBox( parent, ID_MAGCDEGRIF, "Cod.esterna prodotti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item99.SetToolTip( wx.ToolTip("Attiva la codifica del prodotto sulla griglia da parte del fornitore") )
    item99.SetName( "setup_magcdegrif" )
    item97.Add( item99, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item91.Add( item97, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item100 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [-1,20], wx.LI_VERTICAL )
    item91.Add( item100, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL|wx.RIGHT, 5 )

    item101 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item102 = UnoZeroCheckBox( parent, ID_MAGAGGGRIP, "Aggiorna da doc.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item102.SetToolTip( wx.ToolTip("Attiva la facoltÃ  di creare/aggiornare la griglia dal dataentry di magazzino") )
    item102.SetName( "setup_magagggrip" )
    item101.Add( item102, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item103 = UnoZeroCheckBox( parent, ID_MAGALWGRIP, "Default sempre", wx.DefaultPosition, wx.DefaultSize, 0 )
    item103.SetToolTip( wx.ToolTip("Attiva di default l'aggiornamento della griglia dal dataentry di magazzino") )
    item103.SetName( "setup_magalwgrip" )
    item101.Add( item103, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item104 = UnoZeroCheckBox( parent, ID_MAGDATGRIP, "Griglie per data", wx.DefaultPosition, wx.DefaultSize, 0 )
    item104.SetToolTip( wx.ToolTip("Attiva la gestione delle griglie per data") )
    item104.SetName( "setup_magdatgrip" )
    item101.Add( item104, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item91.Add( item101, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item105 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [-1,20], wx.LI_VERTICAL )
    item91.Add( item105, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL|wx.RIGHT, 5 )

    item90.Add( item91, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item106 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item108 = wx.StaticBox( parent, -1, "Vettori" )
    item107 = wx.StaticBoxSizer( item108, wx.HORIZONTAL )
    
    item109 = UnoZeroCheckBox( parent, ID_MAGNOCODEVET, "Variaz.manuale", wx.DefaultPosition, wx.DefaultSize, 0 )
    item109.SetToolTip( wx.ToolTip("Attiva la possibilitÃ  di variazione manuale del vettore sul singolo documento, senza doverlo codificare") )
    item109.SetName( "setup_magnocodevet" )
    item107.Add( item109, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item110 = UnoZeroCheckBox( parent, ID_MAGNOCDEFVET, "Default", wx.DefaultPosition, wx.DefaultSize, 0 )
    item110.SetToolTip( wx.ToolTip("Imposta di default il nuovo documento con giÃ  spuntata la casella di variazione manuale del vettore") )
    item110.SetName( "setup_magnocdefvet" )
    item107.Add( item110, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item111 = UnoZeroCheckBox( parent, ID_MAGEXTRAVET, "Extra-dati", wx.DefaultPosition, wx.DefaultSize, 0 )
    item111.SetToolTip( wx.ToolTip("Attiva extra-dati sui vettori") )
    item111.SetName( "setup_magextravet" )
    item107.Add( item111, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item106.Add( item107, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item113 = wx.StaticBox( parent, -1, "Destinazioni merce" )
    item112 = wx.StaticBoxSizer( item113, wx.HORIZONTAL )
    
    item114 = UnoZeroCheckBox( parent, ID_MAGNOCODEDES, "Variaz.manuale", wx.DefaultPosition, wx.DefaultSize, 0 )
    item114.SetToolTip( wx.ToolTip("Attiva la possibilitÃ  di variazione manuale della destinazione merce sul singolo documento, senza doverla codificare") )
    item114.SetName( "setup_magnocodedes" )
    item112.Add( item114, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item115 = UnoZeroCheckBox( parent, ID_MAGNOCDEFDES, "Default", wx.DefaultPosition, wx.DefaultSize, 0 )
    item115.SetToolTip( wx.ToolTip("Imposta di default il nuovo documento con giÃ  spuntata la casella di variazione manuale della destinazione") )
    item115.SetName( "setup_magnocdefdes" )
    item112.Add( item115, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item106.Add( item112, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL|wx.LEFT|wx.RIGHT, 5 )

    item106.AddGrowableCol( 0 )

    item106.AddGrowableRow( 1 )

    item90.Add( item106, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item90.AddGrowableCol( 1 )

    item0.Add( item90, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item116 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item118 = wx.StaticBox( parent, -1, "Immagine del prodotto" )
    item117 = wx.StaticBoxSizer( item118, wx.VERTICAL )
    
    item119 = UnoZeroCheckBox( parent, ID_MAGIMGPROD, "Attiva se presente", wx.DefaultPosition, wx.DefaultSize, 0 )
    item119.SetName( "setup_magimgprod" )
    item117.Add( item119, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item116.Add( item117, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item121 = wx.StaticBox( parent, -1, "Ricerca prodotti" )
    item120 = wx.StaticBoxSizer( item121, wx.HORIZONTAL )
    
    item122 = CheckBox( parent, ID_MAGDIGSEARCH, "Cerca in digitaz. codice", wx.DefaultPosition, wx.DefaultSize, 0 )
    item122.SetName( "setup_magdigsearch" )
    item120.Add( item122, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item123 = UnoZeroCheckBox( parent, ID_MAGRETSEARCH, "Cerca con Invio", wx.DefaultPosition, wx.DefaultSize, 0 )
    item123.SetName( "setup_magretsearch" )
    item120.Add( item123, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item124 = UnoZeroCheckBox( parent, ID_MAGEXCSEARCH, "Ricerca esclusiva", wx.DefaultPosition, wx.DefaultSize, 0 )
    item124.SetName( "setup_magexcsearch" )
    item120.Add( item124, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item125 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [-1,20], wx.LI_VERTICAL )
    item120.Add( item125, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL|wx.LEFT|wx.RIGHT, 5 )

    item126 = wx.StaticText( parent, ID_TEXT, "Visualizza:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item120.Add( item126, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.BOTTOM, 5 )

    item127 = UnoZeroCheckBox( parent, ID_MAGVISGIA, "Giacenza", wx.DefaultPosition, wx.DefaultSize, 0 )
    item127.SetName( "setup_magvisgia" )
    item120.Add( item127, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item128 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item129 = UnoZeroCheckBox( parent, ID_MAGVISCOS, "Costo", wx.DefaultPosition, wx.DefaultSize, 0 )
    item129.SetName( "setup_magviscos" )
    item128.Add( item129, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item130 = UnoZeroCheckBox( parent, ID_MAGVISPRE, "Prezzo", wx.DefaultPosition, wx.DefaultSize, 0 )
    item130.SetName( "setup_magvispre" )
    item128.Add( item130, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item120.Add( item128, 0, wx.ALIGN_CENTER, 5 )

    item131 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item132 = UnoZeroCheckBox( parent, ID_MAGVISCPF, "Cod.Forn.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item132.SetName( "setup_magviscpf" )
    item131.Add( item132, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item133 = UnoZeroCheckBox( parent, ID_MAGVISBCD, "Barcode", wx.DefaultPosition, wx.DefaultSize, 0 )
    item133.SetName( "setup_magvisbcd" )
    item131.Add( item133, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item120.Add( item131, 0, wx.ALIGN_CENTER, 5 )

    item116.Add( item120, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item116.AddGrowableCol( 1 )

    item0.Add( item116, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item134 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item136 = wx.StaticBox( parent, -1, "Provvigioni" )
    item135 = wx.StaticBoxSizer( item136, wx.HORIZONTAL )
    
    item137 = UnoZeroCheckBox( parent, ID_MAGPROVATT, "Attiva", wx.DefaultPosition, wx.DefaultSize, 0 )
    item137.SetName( "setup_magprovatt" )
    item135.Add( item137, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item138 = UnoZeroCheckBox( parent, ID_MAGPROVCLI, "Su clienti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item138.SetName( "setup_magprovcli" )
    item135.Add( item138, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item139 = UnoZeroCheckBox( parent, ID_MAGPROVPRO, "Su prodotti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item139.SetName( "setup_magprovpro" )
    item135.Add( item139, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item134.Add( item135, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item140 = MagProvMovRadioBox( parent, ID_MAGPROVMOV, "Provvig. sui movimenti", wx.DefaultPosition, wx.DefaultSize, 
        ["Default","Eredita"] , 1, wx.RA_SPECIFY_ROWS )
    item140.SetName( "setup_magprovmov" )
    item134.Add( item140, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item142 = wx.StaticBox( parent, -1, "Gerarchia ereditarietÃ " )
    item141 = wx.StaticBoxSizer( item142, wx.HORIZONTAL )
    
    item143 = wx.StaticText( parent, ID_TEXT, "Sequenza prioritÃ  provvig.:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item141.Add( item143, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item144 = wx.TextCtrl( parent, ID_MAGPROVSEQ, "", wx.DefaultPosition, [80,-1], 0 )
    item144.SetName( "setup_magprovseq" )
    item141.Add( item144, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item134.Add( item141, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item134.AddGrowableCol( 2 )

    item0.Add( item134, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_OPTNOTIFICHE = 15074
ID_OPTTABSEARCH = 15075
ID_OPTDIGSEARCH = 15076
ID_OPTSPASEARCH = 15077
ID_OPTLNKCRDPDC = 15078
ID_OPTLNKGRDPDC = 15079
ID_OPTLNKCRDCLI = 15080
ID_OPTLNKGRDCLI = 15081
ID_OPTLNKCRDFOR = 15082
ID_OPTLNKGRDFOR = 15083
ID_BACKUPDIR = 15084
ID_GCP_USER = 15085
ID_GCP_PSWD = 15086
ID_GC_PRINT = 15087

def OpzioniFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item2 = wx.StaticBox( parent, -1, "Notifiche" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    
    item3 = UnoZeroCheckBox( parent, ID_OPTNOTIFICHE, "Attiva notifiche (Email, XMPP)", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.SetName( "setup_optnotifiche" )
    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item5 = wx.StaticBox( parent, -1, "Ricerche" )
    item4 = wx.StaticBoxSizer( item5, wx.VERTICAL )
    
    item6 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item7 = UnoZeroCheckBox( parent, ID_OPTTABSEARCH, "Attiva la ricerca con il tasto Tab", wx.DefaultPosition, wx.DefaultSize, 0 )
    item7.SetName( "setup_opttabsearch" )
    item6.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item8 = UnoZeroCheckBox( parent, ID_CHECKBOX, "Attiva la ricerca con il tasto Invio", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.SetName( "setup_optretsearch" )
    item6.Add( item8, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.BOTTOM, 5 )

    item9 = UnoZeroCheckBox( parent, ID_OPTDIGSEARCH, "Cerca durante la digitazione", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.SetName( "setup_optdigsearch" )
    item6.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item10 = UnoZeroCheckBox( parent, ID_OPTSPASEARCH, "Cerca per contenuto con \" \" (spazio)", wx.DefaultPosition, wx.DefaultSize, 0 )
    item10.SetName( "setup_optspasearch" )
    item6.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item4.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item11 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item4.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item12 = wx.StaticText( parent, ID_TEXT, "Alla ricezione del focus di tastiera, sui seguenti elementi di ricerca anagrafica imposta la priorità  sulla descrizione:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item13 = wx.FlexGridSizer( 0, 3, 0, 0 )
    
    item14 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item14, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP, 5 )

    item15 = wx.StaticText( parent, ID_TEXT, "In Scheda", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item15, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item16 = wx.StaticText( parent, ID_TEXT, "In griglia", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item16, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item17 = wx.StaticText( parent, ID_TEXT, "Piano dei Conti:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item17, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item18 = UnoZeroCheckBox( parent, ID_OPTLNKCRDPDC, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item18.SetName( "setup_optlnkcrdpdc" )
    item13.Add( item18, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item19 = UnoZeroCheckBox( parent, ID_OPTLNKGRDPDC, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item19.SetName( "setup_optlnkgrdpdc" )
    item13.Add( item19, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item20 = wx.StaticText( parent, ID_TEXT, "Clienti:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item20, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item21 = UnoZeroCheckBox( parent, ID_OPTLNKCRDCLI, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item21.SetName( "setup_optlnkcrdcli" )
    item13.Add( item21, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item22 = UnoZeroCheckBox( parent, ID_OPTLNKGRDCLI, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item22.SetName( "setup_optlnkgrdcli" )
    item13.Add( item22, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item23 = wx.StaticText( parent, ID_TEXT, "Fornitori:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item23, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item24 = UnoZeroCheckBox( parent, ID_OPTLNKCRDFOR, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item24.SetName( "setup_optlnkcrdfor" )
    item13.Add( item24, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item25 = UnoZeroCheckBox( parent, ID_OPTLNKGRDFOR, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item25.SetName( "setup_optlnkgrdfor" )
    item13.Add( item25, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item13.AddGrowableCol( 1 )

    item13.AddGrowableCol( 2 )

    item4.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item27 = wx.StaticBox( parent, -1, "Percorso backup azienda" )
    item26 = wx.StaticBoxSizer( item27, wx.VERTICAL )
    
    item28 = FolderEntryCtrl( parent, ID_BACKUPDIR, "", wx.DefaultPosition, [280,-1], 0 )
    item28.SetName( "setup_optbackupdir" )
    item26.Add( item28, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item0.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item30 = wx.StaticBox( parent, -1, "Google Account" )
    item29 = wx.StaticBoxSizer( item30, wx.VERTICAL )
    
    item31 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item32 = wx.StaticText( parent, ID_TEXT, "Username:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item31.Add( item32, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item33 = TextCtrl_LC( parent, ID_GCP_USER, "", wx.DefaultPosition, [80,-1], 0 )
    item33.SetName( "setup_opt_gcp_user" )
    item31.Add( item33, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item34 = wx.StaticText( parent, ID_TEXT, "Password:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item31.Add( item34, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item35 = TextCtrl_LC( parent, ID_GCP_PSWD, "", wx.DefaultPosition, [80,-1], wx.TE_PASSWORD )
    item35.SetName( "setup_opt_gcp_pswd" )
    item31.Add( item35, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item31.AddGrowableCol( 1 )

    item31.AddGrowableCol( 3 )

    item29.Add( item31, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item36 = UnoZeroCheckBox( parent, ID_GC_PRINT, "Abilita stampe su Google Cloud Print", wx.DefaultPosition, wx.DefaultSize, 0 )
    item36.SetName( "setup_opt_gc_print" )
    item29.Add( item36, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item29, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_TEXTCTRL = 15088
ID_AZIENDA_LOGO = 15089

def DatiAziendaFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item2 = wx.StaticBox( parent, -1, "Intestazione azienda" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    
    item3 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item4 = wx.StaticText( parent, ID_TEXT, "Codice:", wx.DefaultPosition, [100,-1], wx.ALIGN_RIGHT )
    item3.Add( item4, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item5 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [100,-1], 0 )
    item5.SetName( "setup_azienda_codice" )
    item3.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item6 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item1.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item7 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item8 = wx.StaticText( parent, ID_TEXT, "Ragione Sociale:", wx.DefaultPosition, [100,-1], wx.ALIGN_RIGHT )
    item7.Add( item8, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item9 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [360,-1], 0 )
    item9.SetName( "setup_azienda_ragsoc" )
    item7.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item10 = wx.StaticText( parent, ID_TEXT, "Indirizzo:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item7.Add( item10, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item11 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item11.SetName( "setup_azienda_indirizzo" )
    item7.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item12 = wx.StaticText( parent, ID_TEXT, "CAP, CittÃ , Prov.:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item7.Add( item12, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item13 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item14 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [60,-1], 0 )
    item14.SetName( "setup_azienda_cap" )
    item13.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item15 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item15.SetName( "setup_azienda_citta" )
    item13.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item16 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [35,-1], 0 )
    item16.SetName( "setup_azienda_prov" )
    item13.Add( item16, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item13.AddGrowableCol( 1 )

    item7.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item17 = wx.StaticText( parent, ID_TEXT, "Cod.Fiscale:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item7.Add( item17, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item18 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item19 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [120,-1], 0 )
    item19.SetName( "setup_azienda_codfisc" )
    item18.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item20 = wx.StaticText( parent, ID_TEXT, "Stato:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item18.Add( item20, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item21 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [35,-1], 0 )
    item21.SetName( "setup_azienda_stato" )
    item18.Add( item21, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item22 = wx.StaticText( parent, ID_TEXT, "P.IVA:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item18.Add( item22, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item23 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [90,-1], 0 )
    item23.SetName( "setup_azienda_piva" )
    item18.Add( item23, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item18.AddGrowableCol( 0 )

    item18.AddGrowableCol( 4 )

    item7.Add( item18, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item24 = wx.StaticText( parent, ID_TEXT, "Telefono:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item7.Add( item24, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item25 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item26 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item26.SetName( "setup_azienda_numtel" )
    item25.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item27 = wx.StaticText( parent, ID_TEXT, "FAX:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item25.Add( item27, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item28 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item28.SetName( "setup_azienda_numfax" )
    item25.Add( item28, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item25.AddGrowableCol( 0 )

    item25.AddGrowableCol( 2 )

    item7.Add( item25, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item29 = wx.StaticText( parent, ID_TEXT, "email:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item7.Add( item29, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item30 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item30.SetName( "setup_azienda_email" )
    item7.Add( item30, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item31 = wx.StaticText( parent, ID_TEXT, "Titolare privacy:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item7.Add( item31, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item32 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item32.SetName( "setup_azienda_titprivacy" )
    item7.Add( item32, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item7.AddGrowableCol( 1 )

    item1.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item33 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item34 = wx.StaticText( parent, ID_TEXT, "Logo:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item33.Add( item34, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item35 = wx.StaticText( parent, ID_TEXT, "Descrizione attivitÃ :", wx.DefaultPosition, wx.DefaultSize, 0 )
    item33.Add( item35, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item36 = PhotoContainerPanel( parent, ID_AZIENDA_LOGO, wx.DefaultPosition, [128,128], wx.SUNKEN_BORDER )
    item36.SetName( "azienda_logo" )
    item33.Add( item36, 0, wx.LEFT|wx.BOTTOM, 5 )

    item37 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,40], wx.TE_MULTILINE )
    item37.SetName( "setup_azienda_infatti" )
    item33.Add( item37, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item33.AddGrowableCol( 1 )

    item33.AddGrowableRow( 1 )

    item0.Add( item33, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 1 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
