# -*- coding: UTF-8 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: bilcee.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid
import wx.animate

# Custom source
from anag.basetab import AnagCardPanel

from awc.controls.linktable import LinkTable
from awc.controls.radiobox import RadioBox
from awc.controls.checkbox import UnoZeroCheckBox
from awc.controls.textctrl import TextCtrl, TextCtrl_LC

from awc.controls.attachbutton import AttachmentButton

from Env import Azienda
bt = Azienda.BaseTab



# Window functions

ID_ANAGMAIN = 16000
ID_TEXT = 16001
ID_SEZIONE = 16002
ID_VOCE = 16003
ID_CAPITOLO = 16004
ID_DETTAGLIO = 16005
ID_SUBDETT = 16006
ID_SELECTABLE = 16007

def BilCeeCardFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = AnagCardPanel(parent)
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item2 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item3 = wx.StaticText( parent, ID_TEXT, "Sezione:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.Add( item3, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item4 = TextCtrl( parent, ID_SEZIONE, "", wx.DefaultPosition, [20,-1], 0 )
    item4.SetFont( wx.Font( 10, wx.MODERN, wx.NORMAL, wx.NORMAL ) )
    item4.SetName( "sezione" )
    item2.Add( item4, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item5 = wx.StaticText( parent, ID_TEXT, "Voce:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.Add( item5, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item6 = TextCtrl( parent, ID_VOCE, "", wx.DefaultPosition, [20,-1], 0 )
    item6.SetFont( wx.Font( 10, wx.MODERN, wx.NORMAL, wx.NORMAL ) )
    item6.SetName( "voce" )
    item2.Add( item6, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item7 = wx.StaticText( parent, ID_TEXT, "Capitolo:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.Add( item7, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item8 = TextCtrl( parent, ID_CAPITOLO, "", wx.DefaultPosition, [40,-1], 0 )
    item8.SetFont( wx.Font( 10, wx.MODERN, wx.NORMAL, wx.NORMAL ) )
    item8.SetName( "capitolo" )
    item2.Add( item8, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item9 = wx.StaticText( parent, ID_TEXT, "Dettaglio:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.Add( item9, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item10 = TextCtrl( parent, ID_DETTAGLIO, "", wx.DefaultPosition, [30,-1], 0 )
    item10.SetFont( wx.Font( 10, wx.MODERN, wx.NORMAL, wx.NORMAL ) )
    item10.SetName( "dettaglio" )
    item2.Add( item10, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item11 = wx.StaticText( parent, ID_TEXT, "Sub-dett.:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.Add( item11, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item12 = TextCtrl_LC( parent, ID_SUBDETT, "", wx.DefaultPosition, [20,-1], 0 )
    item12.SetFont( wx.Font( 10, wx.MODERN, wx.NORMAL, wx.NORMAL ) )
    item12.SetName( "subdett" )
    item2.Add( item12, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item13 = UnoZeroCheckBox( parent, ID_SELECTABLE, "Selezionabile dal sottoconto", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.SetName( "selectable" )
    item2.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( [ 20, 230 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
