# -*- coding: UTF-8 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: docsemail.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid
import wx.animate

# Custom source
from anag.basetab import AnagCardPanel

from awc.controls.textctrl import TextCtrl, TextCtrl_LC
from awc.controls.numctrl import NumCtrl
from awc.controls.radiobox import RadioBox
from awc.controls.checkbox import CheckBox
from awc.controls.linktable import LinkTable
from awc.controls.dbgrid import DbGrid
from awc.controls.entries import PrintersComboBox
from awc.controls.notebook import Notebook
from awc.controls.entries import MailEntryCtrl

from Env import Azienda
bt = Azienda.BaseTab

from anag.basetab import UnoZeroStringCheckBox


# Window functions

ID_SENDFLAG = 16000
ID_TEXT = 16001
ID_DOCSEMAIL_SENDDESC = 16002
ID_DOCSEMAIL_SENDADDR = 16003
ID_DOCSEMAIL_DALLBODY = 16004
ID_BUTOK = 16005

def DocEmailFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = UnoZeroStringCheckBox( parent, ID_SENDFLAG, "Attiva la spedizione dei documenti via posta elettronica", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.SetName( "setup_docsemail_sendflag" )
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item3 = wx.StaticBox( parent, -1, "Mittente dei messaggi" )
    item2 = wx.StaticBoxSizer( item3, wx.VERTICAL )
    
    item4 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item5 = wx.StaticText( parent, ID_TEXT, "Descrizione:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item5, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item6 = wx.TextCtrl( parent, ID_DOCSEMAIL_SENDDESC, "", wx.DefaultPosition, [400,-1], 0 )
    item6.SetName( "setup_docsemail_senddesc" )
    item4.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item7 = wx.StaticText( parent, ID_TEXT, "email:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item7, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item8 = MailEntryCtrl( parent, ID_DOCSEMAIL_SENDADDR, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.SetForegroundColour( wx.BLUE )
    item8.SetName( "setup_docsemail_sendaddr" )
    item4.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item4.AddGrowableCol( 1 )

    item2.Add( item4, 0, 0, 5 )

    item0.Add( item2, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item9 = wx.StaticText( parent, ID_TEXT, "Testo (corpo) del messaggio:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.SetForegroundColour( wx.BLUE )
    item0.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item10 = wx.TextCtrl( parent, ID_DOCSEMAIL_DALLBODY, "", wx.DefaultPosition, [-1,200], wx.TE_MULTILINE )
    item10.SetName( "setup_docsemail_dallbody" )
    item0.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item11 = wx.Button( parent, ID_BUTOK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item11.SetName( "butok" )
    item0.Add( item11, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
