# -*- coding: iso-8859-15 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: pdcpref.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid

# Window functions

ID_BTN_MOVEUP = 25000
ID_BTN_MOVEDOWN = 25001
ID_BTN_MOVEDEL = 25002
ID_PANGRIDPREF = 25003

def PdcPrefPanelFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item0.AddGrowableCol( 0 )
    item0.AddGrowableRow( 1 )
    
    item1 = wx.BoxSizer( wx.HORIZONTAL )
    
    item2 = wx.Button( parent, ID_BTN_MOVEUP, "Sposta in alto", wx.DefaultPosition, [100,-1], 0 )
    item2.SetName( "butmoveup" )
    item1.Add( item2, 0, wx.GROW|wx.LEFT, 5 )

    item3 = wx.Button( parent, ID_BTN_MOVEDOWN, "Sposta in basso", wx.DefaultPosition, [100,-1], 0 )
    item3.SetName( "butmovedown" )
    item1.Add( item3, 0, wx.GROW|wx.LEFT, 5 )

    item4 = wx.Button( parent, ID_BTN_MOVEDEL, "Elimina", wx.DefaultPosition, [100,-1], 0 )
    item4.SetName( "butdelete" )
    item1.Add( item4, 0, wx.GROW|wx.LEFT|wx.RIGHT, 5 )

    item0.Add( item1, 0, wx.ALIGN_CENTER_VERTICAL|wx.TOP, 5 )

    item5 = wx.FlexGridSizer( 0, 2, 0, 0 )
    item5.AddGrowableCol( 0 )
    item5.AddGrowableRow( 0 )
    
    item6 = wx.Panel( parent, ID_PANGRIDPREF, wx.DefaultPosition, wx.DefaultSize, wx.SUNKEN_BORDER )
    item6.SetName( "pangridpref" )
    item5.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
