# -*- coding: iso-8859-15 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: vsynt.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid

# Custom source
import wx

from Env import Azienda
bt = Azienda.BaseTab

from awc.controls.checkbox import CheckBox
from awc.controls.textctrl import TextCtrl

class VoiceListBox(wx.ListBox):
    def GetValue(self):
        return wx.ListBox.GetSelection(self)

    def SetValue(self, value):
        return wx.ListBox.SetSelection(self, value)



# Window functions

ID_ENABLE = 15000
ID_TEXT = 15001
ID_VOICE = 15002
ID_CURSPEED = 15003
ID_SPEED = 15004
ID_CURPITCH = 15005
ID_PITCH = 15006
ID_CURVOLSX = 15007
ID_VOLSX = 15008
ID_CURVOLDX = 15009
ID_VOLDX = 15010
ID_TEST = 15011
ID_SPEAK = 15012
ID_OK = 5100
ID_CANCEL = 15013

def VoiceSyntFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item0.AddGrowableCol( 0 )
    item0.AddGrowableRow( 3 )
    
    item1 = CheckBox( parent, ID_ENABLE, "Abilita sintetizzatore vocale", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item2 = wx.FlexGridSizer( 1, 0, 0, 0 )
    item2.AddGrowableCol( 0 )
    item2.AddGrowableCol( 1 )
    
    item3 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item3.AddGrowableCol( 0 )
    item3.AddGrowableRow( 1 )
    
    item4 = wx.StaticText( parent, ID_TEXT, "Voci disponibili", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.SetBackgroundColour( wx.LIGHT_GREY )
    item4.SetFont( wx.Font( 10, wx.DEFAULT, wx.ITALIC, wx.NORMAL ) )
    item3.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item5 = VoiceListBox( parent, ID_VOICE, wx.DefaultPosition, [300,100], [], wx.LB_SINGLE )
    item3.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item2.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item6 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item6.AddGrowableCol( 0 )
    
    item7 = wx.StaticText( parent, ID_TEXT, "Impostazioni", wx.DefaultPosition, wx.DefaultSize, 0 )
    item7.SetBackgroundColour( wx.LIGHT_GREY )
    item7.SetFont( wx.Font( 10, wx.DEFAULT, wx.ITALIC, wx.NORMAL ) )
    item6.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item8 = wx.FlexGridSizer( 0, 3, 0, 0 )
    item8.AddGrowableCol( 2 )
    
    item9 = wx.StaticText( parent, ID_TEXT, "Velocità:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.Add( item9, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item10 = wx.StaticText( parent, ID_CURSPEED, "", wx.DefaultPosition, [40,-1], wx.ST_NO_AUTORESIZE|wx.ALIGN_RIGHT )
    item10.SetFont( wx.Font( 10, wx.SWISS, wx.NORMAL, wx.NORMAL ) )
    item8.Add( item10, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item11 = wx.Slider( parent, ID_SPEED, 0, 0, 100, wx.DefaultPosition, [100,-1], wx.SL_HORIZONTAL )
    item8.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item12 = wx.StaticText( parent, ID_TEXT, "Pitch:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.Add( item12, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item13 = wx.StaticText( parent, ID_CURPITCH, "", wx.DefaultPosition, [40,-1], wx.ST_NO_AUTORESIZE|wx.ALIGN_RIGHT )
    item13.SetFont( wx.Font( 10, wx.SWISS, wx.NORMAL, wx.NORMAL ) )
    item8.Add( item13, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item14 = wx.Slider( parent, ID_PITCH, 0, 0, 100, wx.DefaultPosition, [100,-1], wx.SL_HORIZONTAL )
    item8.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item15 = wx.StaticText( parent, ID_TEXT, "Volume Sx:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.Add( item15, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item16 = wx.StaticText( parent, ID_CURVOLSX, "", wx.DefaultPosition, [40,-1], wx.ST_NO_AUTORESIZE|wx.ALIGN_RIGHT )
    item16.SetFont( wx.Font( 10, wx.SWISS, wx.NORMAL, wx.NORMAL ) )
    item8.Add( item16, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item17 = wx.Slider( parent, ID_VOLSX, 0, 0, 100, wx.DefaultPosition, [100,-1], wx.SL_HORIZONTAL )
    item8.Add( item17, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item18 = wx.StaticText( parent, ID_TEXT, "Volume Dx:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.Add( item18, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item19 = wx.StaticText( parent, ID_CURVOLDX, "", wx.DefaultPosition, [40,-1], wx.ST_NO_AUTORESIZE|wx.ALIGN_RIGHT )
    item19.SetFont( wx.Font( 10, wx.SWISS, wx.NORMAL, wx.NORMAL ) )
    item8.Add( item19, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item20 = wx.Slider( parent, ID_VOLDX, 0, 0, 100, wx.DefaultPosition, [100,-1], wx.SL_HORIZONTAL )
    item8.Add( item20, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item6.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item21 = wx.StaticText( parent, ID_TEXT, "Test", wx.DefaultPosition, wx.DefaultSize, 0 )
    item21.SetBackgroundColour( wx.LIGHT_GREY )
    item21.SetFont( wx.Font( 10, wx.DEFAULT, wx.ITALIC, wx.NORMAL ) )
    item6.Add( item21, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item22 = wx.FlexGridSizer( 1, 0, 0, 0 )
    item22.AddGrowableCol( 1 )
    
    item23 = wx.StaticText( parent, ID_TEXT, "Frase test:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item22.Add( item23, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item24 = TextCtrl( parent, ID_TEST, "Questa è una frase di prova. Come mi senti?", wx.DefaultPosition, [200,-1], 0 )
    item22.Add( item24, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item25 = wx.Button( parent, ID_SPEAK, "Test", wx.DefaultPosition, [40,-1], wx.NO_BORDER )
    item22.Add( item25, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item6.Add( item22, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item2.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item26 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item0.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item27 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item28 = wx.Button( parent, ID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item28.SetDefault()
    item27.Add( item28, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item29 = wx.Button( parent, ID_CANCEL, "Abbandona", wx.DefaultPosition, wx.DefaultSize, 0 )
    item27.Add( item29, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item27, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
