# -*- coding: iso-8859-15 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: promem.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid

# Custom source
import images
from awc.controls.textctrl import TextCtrl, TextCtrl_LC
from awc.controls.datectrl import DateCtrl, DateTimeCtrl
from awc.controls.checkbox import CheckBox, CheckListBox
from awc.controls.numctrl import NumCtrl
from awc.controls.linktable import LinkTable
from awc.controls.button import FlatBitmapButton

import awc.layout.images as images

import Env
bt = Env.Azienda.BaseTab


# Window functions

ID_TEXT = 16000
ID_DATINS = 16001
ID_UTEINS = 16002
ID_LINE = 16003
ID_GLOBALE = 16004
ID_UTENTI = 16005
ID_DATASCA = 16006
ID_STATUS = 16007
ID_AVVISA = 16008
ID_DATAREM = 16009
ID_OGGETTO = 16010
ID_TEXTCTRL = 16011
ID_DELETE = 16012
ID_SAVE = 16013

def PromemPanelFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item0.AddGrowableCol( 0 )
    item0.AddGrowableRow( 2 )
    
    item1 = wx.FlexGridSizer( 1, 0, 0, 0 )
    item1.AddGrowableCol( 4 )
    
    item2 = wx.StaticText( parent, ID_TEXT, "Inserito il:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item2, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item3 = DateTimeCtrl( parent, ID_DATINS, "", wx.DefaultPosition, [80,-1], 0 )
    item3.SetName( "datains" )
    item3.Enable(False)
    item1.Add( item3, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item4 = wx.StaticText( parent, ID_TEXT, "dall'utente:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item4, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item5 = TextCtrl( parent, ID_UTEINS, "", wx.DefaultPosition, [30,-1], 0 )
    item5.SetName( "uteins" )
    item5.Enable(False)
    item1.Add( item5, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item6 = TextCtrl_LC( parent, ID_UTEINS, "", wx.DefaultPosition, [30,-1], 0 )
    item6.SetName( "_descuteins" )
    item6.Enable(False)
    item1.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item7 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item0.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item8 = wx.FlexGridSizer( 1, 0, 0, 0 )
    item8.AddGrowableCol( 1 )
    item8.AddGrowableRow( 0 )
    
    item9 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item9.AddGrowableCol( 0 )
    item9.AddGrowableRow( 3 )
    
    item10 = wx.StaticText( parent, ID_TEXT, "Destinatari del promemoria", wx.DefaultPosition, wx.DefaultSize, 0 )
    item10.SetForegroundColour( wx.BLUE )
    item9.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item11 = CheckBox( parent, ID_GLOBALE, "Chiunque (comparirà a tutti)", wx.DefaultPosition, wx.DefaultSize, 0 )
    item11.SetName( "globale" )
    item9.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item12 = wx.StaticText( parent, ID_TEXT, "Solo i seguenti utenti:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item13 = CheckListBox( parent, ID_UTENTI, wx.DefaultPosition, [120,160], [], wx.LB_SINGLE )
    item13.SetName( "utenti" )
    item9.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item8.Add( item9, 0, wx.GROW, 5 )

    item14 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item14.AddGrowableCol( 0 )
    item14.AddGrowableRow( 4 )
    
    item15 = wx.StaticText( parent, ID_TEXT, "Dettagli del promemoria", wx.DefaultPosition, wx.DefaultSize, 0 )
    item15.SetForegroundColour( wx.BLUE )
    item14.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item16 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item17 = wx.StaticText( parent, ID_TEXT, "Scade il:", wx.DefaultPosition, [60,-1], wx.ALIGN_RIGHT )
    item16.Add( item17, 0, wx.ALIGN_BOTTOM|wx.ALIGN_CENTER_HORIZONTAL|wx.LEFT|wx.BOTTOM, 5 )

    item18 = DateTimeCtrl( parent, ID_DATASCA, "", wx.DefaultPosition, [80,-1], 0 )
    item18.SetName( "datasca" )
    item16.Add( item18, 0, wx.ALIGN_BOTTOM|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 5 )

    item19 = CheckBox( parent, ID_STATUS, "Finito", wx.DefaultPosition, wx.DefaultSize, 0 )
    item19.SetName( "status" )
    item16.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item14.Add( item16, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item20 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item21 = CheckBox( parent, ID_AVVISA, "Avvisa il:", wx.DefaultPosition, [60,-1], 0 )
    item21.SetName( "avvisa" )
    item20.Add( item21, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item22 = DateTimeCtrl( parent, ID_DATAREM, "", wx.DefaultPosition, [80,-1], 0 )
    item22.SetName( "datarem" )
    item22.Enable(False)
    item20.Add( item22, 0, wx.ALIGN_BOTTOM|wx.ALIGN_CENTER_HORIZONTAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item14.Add( item20, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item23 = wx.FlexGridSizer( 1, 0, 0, 0 )
    item23.AddGrowableCol( 1 )
    
    item24 = wx.StaticText( parent, ID_TEXT, "Oggetto:", wx.DefaultPosition, [60,-1], wx.ALIGN_RIGHT )
    item23.Add( item24, 0, wx.ALIGN_CENTER|wx.LEFT|wx.BOTTOM, 5 )

    item25 = TextCtrl_LC( parent, ID_OGGETTO, "", wx.DefaultPosition, [300,-1], 0 )
    item25.SetName( "oggetto" )
    item23.Add( item25, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item14.Add( item23, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item26 = wx.FlexGridSizer( 1, 0, 0, 0 )
    item26.AddGrowableCol( 1 )
    item26.AddGrowableRow( 0 )
    
    item27 = wx.StaticText( parent, ID_TEXT, "Descrizione:", wx.DefaultPosition, [60,-1], wx.ALIGN_RIGHT )
    item26.Add( item27, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.LEFT|wx.BOTTOM, 5 )

    item28 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [400,200], wx.TE_MULTILINE )
    item28.SetName( "descriz" )
    item26.Add( item28, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item14.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item29 = wx.BoxSizer( wx.HORIZONTAL )
    
    item30 = wx.Button( parent, ID_DELETE, "Elimina", wx.DefaultPosition, wx.DefaultSize, 0 )
    item30.SetName( "_delete" )
    item29.Add( item30, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item31 = wx.Button( parent, ID_SAVE, "Salva", wx.DefaultPosition, wx.DefaultSize, 0 )
    item31.SetDefault()
    item31.SetName( "_save" )
    item29.Add( item31, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item14.Add( item29, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item8.Add( item14, 0, wx.GROW, 5 )

    item0.Add( item8, 0, wx.GROW, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_SCADENZA = 16014
ID_DESCRIZ = 16015
ID_TEMPO = 16016
ID_RIMANDA = 16017
ID_MODIFICA = 16018
ID_FINITO = 16019

def PromemAlertFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item0.AddGrowableCol( 0 )
    item0.AddGrowableRow( 2 )
    
    item1 = wx.StaticText( parent, ID_OGGETTO, "-oggetto-", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.SetFont( wx.Font( 11, wx.DEFAULT, wx.NORMAL, wx.BOLD ) )
    item1.SetName( "oggetto" )
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item2 = wx.StaticText( parent, ID_SCADENZA, "-scadenza-", wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.SetFont( wx.Font( 8, wx.DEFAULT, wx.NORMAL, wx.NORMAL ) )
    item2.SetName( "_scadenza" )
    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item3 = wx.StaticText( parent, ID_DESCRIZ, "-descrizione-", wx.DefaultPosition, [380,200], wx.ST_NO_AUTORESIZE )
    item3.SetName( "descriz" )
    item0.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item4 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item0.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item5 = wx.FlexGridSizer( 1, 0, 0, 0 )
    item5.AddGrowableCol( 1 )
    
    item6 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item7 = wx.StaticText( parent, ID_TEXT, "Rimanda di:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item7, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item8 = wx.Choice( parent, ID_TEMPO, wx.DefaultPosition, [100,-1], 
        ["1 minuto","5 minuti","10 minuti","un quarto d'ora","mezz'ora","1 ora","2 ore","3 ore","4 ore","6 ore","mezza giornata","1 giorno","2 giorni"] , 0 )
    item8.SetName( "_tempo" )
    item6.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item9 = wx.Button( parent, ID_RIMANDA, "Rimanda", wx.DefaultPosition, [60,-1], 0 )
    item9.SetDefault()
    item9.SetName( "_rimanda" )
    item6.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item10 = DateTimeCtrl( parent, ID_DATAREM, "", wx.DefaultPosition, [140,-1], 0 )
    item10.SetName( "datarem" )
    item6.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item5.Add( item6, 0, wx.ALIGN_CENTER, 5 )

    item11 = wx.BoxSizer( wx.VERTICAL )
    
    item12 = wx.Button( parent, ID_MODIFICA, "Modifica", wx.DefaultPosition, wx.DefaultSize, 0 )
    item12.SetName( "_modifica" )
    item11.Add( item12, 0, wx.GROW|wx.ALIGN_BOTTOM|wx.ALL, 5 )

    item13 = wx.Button( parent, ID_FINITO, "Finito", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.SetName( "_finito" )
    item11.Add( item13, 0, wx.GROW|wx.ALIGN_BOTTOM|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item5.Add( item11, 0, wx.ALIGN_RIGHT|wx.ALIGN_BOTTOM, 5 )

    item0.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_NUOVOPM = 16020
ID_SOLOATT = 16021
ID_PANEL = 16022

def PromemRiepFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item0.AddGrowableCol( 0 )
    item0.AddGrowableRow( 1 )
    
    item1 = wx.StaticText( parent, ID_TEXT, " Promemoria", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.SetBackgroundColour( wx.LIGHT_GREY )
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item2 = wx.FlexGridSizer( 2, 0, 0, 0 )
    item2.AddGrowableCol( 0 )
    item2.AddGrowableRow( 1 )
    
    item3 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item4 = FlatBitmapButton(parent, ID_NUOVOPM, images.getNew20Bitmap()); item4.SetName('_nuovopm')
    item3.Add( item4, 0, wx.ALIGN_CENTER, 5 )

    item5 = wx.CheckBox( parent, ID_SOLOATT, "Visualizza solo promemoria attivi", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.SetValue( True )
    item5.SetName( "_soloatt" )
    item3.Add( item5, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item2.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item6 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item6.AddGrowableCol( 0 )
    item6.AddGrowableRow( 0 )
    
    item7 = wx.Panel( parent, ID_PANEL, wx.DefaultPosition, [660,160], 0 )
    item7.SetName( "_panelriep" )
    item6.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item2.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
