# -*- coding: UTF-8 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: X.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid
import wx.animate

# Custom source
import version
import images
import awc.layout.images as awimages

from awc.controls.button import FlatButton
from awc.controls.button import FlatBitmapButton as BitmapButton

from awc.controls.textctrl import TextCtrl
from awc.controls.datectrl import DateCtrl
from awc.controls.checkbox import CheckBox, RCheckBox
from awc.controls.notebook import Notebook

import awc.controls.windows as aw

from awc.controls.entries import FolderEntryCtrl

import wx.lib.hyperlink as hl

from anag.basetab import WorkZoneNotebook, PhotoContainerPanel

import Env

class BranchText(wx.StaticText):
    
    def __init__(self, *args, **kwargs):
        wx.StaticText.__init__(self, *args, **kwargs)
        branch = version.VERSION_BRANCH
        self.SetLabel('(branch: %s)' % branch)
        self.SetFont(wx.Font(10, wx.SWISS, wx.NORMAL, wx.BOLD))
        self.SetForegroundColour('gray')
        if branch == 'master':
            self.Hide()


class MyChoice(wx.Choice):
    def GetValue(self):
        return self.GetClientData(self.GetSelection())


import cfg.license_wdr as licwdr
from cfg.license import License, LicenseInfoDialog

import plugins


class AboutPanel(wx.Panel):
    """
    Genitore dei Panel contenenti informazioni sul programma.
    """
    def __init__(self, *args, **kwargs):
        wx.Panel.__init__(self, *args, **kwargs)
        sizer = AboutFunc(self)
        def cn(x):
            return self.FindWindowByName(x)
        l = Env.Azienda.license
        try:
            rs = l.get('License', 'head')
            pi = l.get('License', 'piva')
        except:
            rs = pi = ''
        cn('appinfo').SetLabel(version.VERSION_INFO)
        if version.OSS():
            if rs:
                dul = "Copia registrata da:"
            else:
                dul = 'Copia non registrata'
                cn('panuserlic').Hide()
        else:
            dul = "Licenza d'uso rilasciata a:"
        cn('lic_ragsoc').SetLabel(rs)
        cn('lic_piva').SetLabel(pi)
        cn('destuserlic').SetLabel(dul)
        if not version.MODVERSION_NAME:
            for name in ('labelmod', 'modname', 'modversion'):
                cn(name).Show(False)
        if not version.MODVERSION_NAME and not Env.plugins:
            cn('plugins').Hide()
        self.Fit()
        self.Layout()
        self.SetSizer(sizer)
        sizer.SetSizeHints(self)
        for cid, func in ((ID_LICINFO, self.OnLicInfo),
                          (ID_VERINFO, self.OnVerInfo),
                          (ID_PLUGINS, self.OnPlugins)):
            self.Bind(wx.EVT_BUTTON, func, id=cid)
    
    def OnPlugins(self, event):
        dlg = plugins.PluginsDialog()
        dlg.ShowModal()
        dlg.Destroy()
        event.Skip()
    
    def OnLicInfo(self, event):
        dlg = LicenseInfoDialog(self)
        dlg.ShowModal()
        dlg.Destroy()
        event.Skip()
    
    def OnVerInfo(self, event):
        dlg = aw.Dialog(self, -1, 'X4 :: Informazioni sulla versione')
        p = aw.Panel(dlg)
        VersionChangesFunc(p)
        cn = self.FindWindowByName
        from versionchanges import history, historymod
        for name, hist in (('changes',    history),
                           ('modchanges', historymod),):
            txt = ''
            for relver, reldat, relchg in hist:
                if txt:
                    txt += '\n\n'
                txt += "Versione %s " % relver
                if reldat is None:
                    txt += "(non rilasciata)\n"
                else:
                    txt += "del %s\n" % reldat.Format().split()[0]
                for tag, chg in relchg:
                    while '\n ' in chg:
                        chg = chg.replace('\n ', '\n')
                    txt += '\n%s\n' % tag.replace('\n', ' ')
                    txt += '%s\n' % chg.replace('\n', ' ')
                txt += '\n'
            vertxt = cn(name)
            vertxt.SetValue(txt)
            vertxt.SetEditable(False)
        if not historymod:
            nb = cn('workzone')
            nb.RemovePage(1)
        dlg.AddSizedPanel(p)
        dlg.Bind(wx.EVT_BUTTON, lambda *x: dlg.EndModal(wx.ID_OK))
        dlg.ShowModal()
        dlg.Destroy()
        event.Skip()


class VersionText(wx.StaticText):
    def __init__(self, parent, id, text, *args, **kwargs):
        wx.StaticText.__init__(self, parent, id, text, *args, **kwargs)
        self.SetFont(wx.Font( 12, wx.SWISS, wx.NORMAL, wx.BOLD ))

class LogoPanel(wx.Panel):
    def __init__(self, *args, **kwargs):
        wx.Panel.__init__(self, *args, **kwargs)
        self.SetBackgroundColour('white')
        AboutLogoPanelFunc(self)
        AboutProgramPanelFunc(self, False)
        self.Fit()
        self.Layout()


class AutoCheckUpdatesCheckBox(CheckBox):

    def __init__(self, *args, **kwargs):
        CheckBox.__init__(self, *args, **kwargs)
        self.SetDataLink(values={True: '1', False: '0'})

class AppDescStaticText(wx.StaticText):
    def __init__(self, *args, **kwargs):
        wx.StaticText.__init__(self, *args, **kwargs)
        self.SetLabel(version.appdesc)


#class ElencoTabelleAziendaCheckListBox(wx.CheckListBox):
#
#    def __init__(self, *args, **kwargs):
#        wx.CheckListBox.__init__(self, *args, **kwargs)
#        self.tabelle = []
#        self.tabdesc = {}
#        for tab in Env.Azienda.BaseTab.tabelle:
#            self.tabelle.append(tab[0])
#            self.tabdesc[tab[0]] = tab[1]
#        self.tabelle.sort()
#        for tab in self.tabelle:
#            self.Append('%s - %s' % (tab, self.tabdesc[tab]))
#    
#    def GetTables(self):
#        tables = []
#        for tab in Env.Azienda.BaseTab.tabelle:
#            i = self.tabelle.index(tab[0])
#            if self.IsChecked(i):
#                tables.append(tab[0])
#        return tables



from wx.lib.mixins.listctrl import CheckListCtrlMixin

class ElencoTabelleAziendaCheckListBox(wx.ListCtrl, CheckListCtrlMixin):

    def __init__(self, parent, id, pos, size, *args):
        wx.ListCtrl.__init__(self, parent, id, pos, size, style=wx.LC_REPORT)
        CheckListCtrlMixin.__init__(self)
        self.tabelle = []
        self.tabdesc = {}
        for tab in Env.Azienda.BaseTab.tabelle:
            self.tabelle.append(tab[0])
            self.tabdesc[tab[0]] = tab[1]
        self.tabelle.sort()
    
    def SetModeBackup(self):
        self.InsertColumn(0, "Tabella")
        self.InsertColumn(1, "Contenuto")
        self.SetColumnWidth(0, 100)
        self.SetColumnWidth(1, 240)
        for tab in self.tabelle:
            index = self.InsertStringItem(999, tab)
            self.SetStringItem(index, 0, tab)
            self.SetStringItem(index, 1, self.tabdesc[tab])
    
    def SetModeRestore(self, tabrows):
        self.InsertColumn(0, "Tabella")
        self.InsertColumn(1, "Contenuto")
        self.InsertColumn(2, "Righe", wx.LIST_FORMAT_RIGHT)
        self.SetColumnWidth(0, 100)
        self.SetColumnWidth(1, 240)
        self.SetColumnWidth(2, 60)
        for tab in self.tabelle:
            if not tabrows or tab in tabrows:
                index = self.InsertStringItem(999, tab)
                self.SetStringItem(index, 0, tab)
                self.SetStringItem(index, 1, self.tabdesc[tab])
                if tabrows and tab in tabrows:
                    self.SetStringItem(index, 2, str(tabrows[tab]))
                    self.CheckItem(index)
    
    def GetTables(self):
        tables = []
        for tab in Env.Azienda.BaseTab.tabelle:
            i = self.tabelle.index(tab[0])
            if self.IsChecked(i):
                tables.append(tab[0])
        return tables


import os
class LogoAziendaleBitmap(PhotoContainerPanel):
    
    def __init__(self, *args, **kwargs):
        kwargs['dnd'] = False
        PhotoContainerPanel.__init__(self, *args, **kwargs)
        hide = True
        p = Env.Azienda.config.get('Site', 'folder')
        if os.path.isdir(p):
            fn = os.path.join(p, 'logo_aziendale.jpg')
            if os.path.isfile(fn):
                self.display_image(fn)
                hide = False
        if hide:
            self.Hide()


class UserLicenseInfoPanel(wx.Panel):

    def __init__(self, *args, **kwargs):
        wx.Panel.__init__(self, *args, **kwargs)
        UserLicenseInfoFunc(self)




# Window functions

ID_LOGOPANEL = 10000
ID_LINE = 10001
ID_APPINFO = 10002
ID_DESTUSERLIC = 10003
ID_PLUGINS = 10004
ID_LICINFO = 10005
ID_VERINFO = 10006
ID_PANUSERLIC = 10007

def AboutFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = LogoPanel( parent, ID_LOGOPANEL, wx.DefaultPosition, [200,160], 0 )
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item2 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item3 = wx.StaticText( parent, ID_APPINFO, "-appinfo-", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_CENTRE )
    item3.SetForegroundColour( wx.LIGHT_GREY )
    item3.SetFont( wx.Font( 8, wx.SWISS, wx.NORMAL, wx.NORMAL ) )
    item3.SetName( "appinfo" )
    item0.Add( item3, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item4 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item0.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item5 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item6 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item7 = wx.StaticText( parent, ID_DESTUSERLIC, "-destuserlic-", wx.DefaultPosition, wx.DefaultSize, 0 )
    item7.SetName( "destuserlic" )
    item6.Add( item7, 0, wx.ALIGN_BOTTOM|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item8 = wx.BoxSizer( wx.HORIZONTAL )
    
    item9 = FlatButton( parent, ID_PLUGINS, "Plugins", wx.DefaultPosition, wx.DefaultSize, wx.NO_BORDER )
    item9.SetFont( wx.Font( 7, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item9.SetName( "plugins" )
    item8.Add( item9, 0, wx.ALIGN_BOTTOM|wx.ALIGN_CENTER_HORIZONTAL|wx.RIGHT|wx.TOP, 5 )

    item10 = wx.Button( parent, ID_LICINFO, "Visualizza licenza d'uso", wx.DefaultPosition, wx.DefaultSize, wx.NO_BORDER )
    item10.SetForegroundColour( wx.BLUE )
    item10.SetFont( wx.Font( 7, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item10.SetToolTip( wx.ToolTip("Visualizza il testo della licenza d'uso") )
    item10.SetName( "licinfo" )
    item8.Add( item10, 0, wx.ALIGN_BOTTOM|wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item11 = wx.Button( parent, ID_VERINFO, "Informazioni sulla versione", wx.DefaultPosition, wx.DefaultSize, wx.NO_BORDER )
    item11.SetForegroundColour( wx.BLUE )
    item11.SetFont( wx.Font( 7, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item11.SetToolTip( wx.ToolTip("Visualizza l'elenco delle modifiche apportate in questa versione e quelle precedenti") )
    item11.SetName( "verinfo" )
    item8.Add( item11, 0, wx.ALIGN_RIGHT|wx.ALIGN_BOTTOM|wx.RIGHT, 5 )

    item6.Add( item8, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item6.AddGrowableCol( 1 )

    item5.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item12 = UserLicenseInfoPanel( parent, ID_PANUSERLIC, wx.DefaultPosition, wx.DefaultSize, 0 )
    item12.SetName( "panuserlic" )
    item5.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item5.AddGrowableCol( 0 )

    item0.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_CHANGES = 10008
ID_BTNOK = 10009

def _old_VersionChangesFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.TextCtrl( parent, ID_CHANGES, "", wx.DefaultPosition, [640,480], wx.TE_MULTILINE )
    item1.SetName( "changes" )
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item2 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item3 = wx.Button( parent, ID_BTNOK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.SetDefault()
    item3.SetName( "btnok" )
    item2.Add( item3, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item2.AddGrowableCol( 1 )

    item0.Add( item2, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_CHANGESZONE = 10010

def VersionChangesFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item2 = WorkZoneNotebook( parent, ID_CHANGESZONE, wx.DefaultPosition, [200,160], 0 )
    item1 = item2
    
    item3 = wx.Panel( item2, -1 )
    ModVersionChangesVerFunc(item3, False)
    item2.AddPage( item3, "X4" )

    item4 = wx.Panel( item2, -1 )
    ModVersionChangesModFunc(item4, False)
    item2.AddPage( item4, "Mod" )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item5 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item6 = wx.Button( parent, ID_BTNOK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.Add( item6, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item5.AddGrowableCol( 1 )

    item0.Add( item5, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0


def ModVersionChangesVerFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.TextCtrl( parent, ID_CHANGES, "", wx.DefaultPosition, [640,480], wx.TE_MULTILINE )
    item1.SetName( "changes" )
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_MODCHANGES = 10011

def ModVersionChangesModFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.TextCtrl( parent, ID_MODCHANGES, "", wx.DefaultPosition, [640,480], wx.TE_MULTILINE )
    item1.SetName( "modchanges" )
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_TEXT = 10012
ID_FOREIGN = 10013
ID_MODNAME = 10014
ID_VERACT = 10015
ID_VERDISP = 10016
ID_MESSAGE = 10017
ID_PROGRESS = 10018
ID_BYTES = 10019
ID_CANCEL = 10020
ID_ACTION = 10021
ID_INFO = 10022

def _ProgramUpdateFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.StaticText( parent, ID_TEXT, "Controllo aggiornamenti programma", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_CENTRE )
    item1.SetForegroundColour( wx.BLUE )
    item1.SetBackgroundColour( wx.LIGHT_GREY )
    item1.SetFont( wx.Font( 11, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item2 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item3 = wx.StaticBitmap(parent, ID_FOREIGN, images.getProgramUpdateBitmap())
    item2.Add( item3, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item4 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item5 = wx.StaticText( parent, ID_TEXT, "mod:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item5, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item6 = wx.StaticText( parent, ID_MODNAME, "-", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item6, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item7 = wx.StaticText( parent, ID_TEXT, "Vers. attuale:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item7, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item8 = wx.StaticText( parent, ID_VERACT, "-", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item8, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item9 = wx.StaticText( parent, ID_TEXT, "Vers. disponibile:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item9, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item10 = wx.StaticText( parent, ID_VERDISP, "-", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item10, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item2.Add( item4, 0, wx.GROW|wx.ALL, 5 )

    item2.AddGrowableCol( 1 )

    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item11 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [280,-1], wx.LI_HORIZONTAL )
    item0.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item12 = wx.StaticText( parent, ID_MESSAGE, "-", wx.DefaultPosition, [200,-1], 0 )
    item0.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item13 = wx.Gauge( parent, ID_PROGRESS, 100, wx.DefaultPosition, [-1,14], 0 )
    item0.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item14 = wx.StaticText( parent, ID_BYTES, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item15 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item0.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item16 = wx.BoxSizer( wx.HORIZONTAL )
    
    item17 = wx.Button( parent, ID_CANCEL, "Chiudi", wx.DefaultPosition, wx.DefaultSize, 0 )
    item16.Add( item17, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item18 = wx.Button( parent, ID_ACTION, "Verifica", wx.DefaultPosition, wx.DefaultSize, 0 )
    item18.SetDefault()
    item16.Add( item18, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item19 = wx.Button( parent, ID_INFO, "Info", wx.DefaultPosition, wx.DefaultSize, 0 )
    item16.Add( item19, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item16, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_TEXTCTRL = 10023
ID_BTNTEST = 10024
ID_BTNFIND = 10025
ID_AUTOCHECK = 10026
ID_BTNQUIT = 10027

def ProgramUpdateSetupFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item2 = wx.StaticBox( parent, -1, "Autenticazione" )
    item1 = wx.StaticBoxSizer( item2, wx.HORIZONTAL )
    
    item3 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item4 = wx.StaticText( parent, ID_TEXT, "Username:", wx.DefaultPosition, [180,-1], wx.ALIGN_RIGHT )
    item3.Add( item4, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item5 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.SetName( "Updates_user" )
    item3.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item6 = wx.StaticText( parent, ID_TEXT, "Password:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item6, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item7 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, wx.TE_PASSWORD )
    item7.SetName( "Updates_pswd" )
    item3.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item3.Add( [ 50, 20 ] , 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item3.AddGrowableCol( 1 )

    item3.AddGrowableCol( 3 )

    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item9 = wx.StaticBox( parent, -1, "Url e cartelle" )
    item8 = wx.StaticBoxSizer( item9, wx.HORIZONTAL )
    
    item10 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item11 = wx.StaticText( parent, ID_TEXT, "Indirizzo http server:", wx.DefaultPosition, [180,-1], wx.ALIGN_RIGHT )
    item10.Add( item11, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item12 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item13 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item14 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [300,-1], 0 )
    item14.SetName( "Updates_url" )
    item13.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item15 = wx.Button( parent, ID_BTNTEST, "Test", wx.DefaultPosition, [50,-1], 0 )
    item13.Add( item15, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item13.AddGrowableCol( 0 )

    item12.Add( item13, 0, wx.ALIGN_CENTER, 5 )

    item12.AddGrowableCol( 0 )

    item10.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item16 = wx.StaticText( parent, ID_TEXT, "Percorso aggiornamenti scaricati:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item10.Add( item16, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item17 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item18 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [300,-1], 0 )
    item18.SetName( "Updates_folder" )
    item17.Add( item18, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item19 = wx.Button( parent, ID_BTNFIND, "Trova", wx.DefaultPosition, [50,-1], 0 )
    item17.Add( item19, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.BOTTOM, 5 )

    item17.AddGrowableCol( 0 )

    item10.Add( item17, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item10.AddGrowableCol( 1 )

    item8.Add( item10, 0, wx.GROW, 5 )

    item0.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item21 = wx.StaticBox( parent, -1, "AutoCheck" )
    item20 = wx.StaticBoxSizer( item21, wx.VERTICAL )
    
    item22 = AutoCheckUpdatesCheckBox( parent, ID_AUTOCHECK, "Verifica la disponibilità di nuove versioni del programma ad ogni avvio", wx.DefaultPosition, wx.DefaultSize, 0 )
    item22.SetName( "Updates_autocheck" )
    item20.Add( item22, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.Add( item20, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item23 = wx.BoxSizer( wx.HORIZONTAL )
    
    item24 = wx.Button( parent, ID_BTNOK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item24.SetDefault()
    item23.Add( item24, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item25 = wx.Button( parent, ID_BTNQUIT, "Abbandona", wx.DefaultPosition, wx.DefaultSize, 0 )
    item23.Add( item25, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item23, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_OK = 10028

def VersionInfoFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.TextCtrl( parent, ID_VERINFO, "", wx.DefaultPosition, [600,400], wx.TE_MULTILINE )
    item1.SetFont( wx.Font( 9, wx.MODERN, wx.NORMAL, wx.NORMAL ) )
    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item2 = wx.BoxSizer( wx.HORIZONTAL )
    
    item3 = wx.Button( parent, ID_OK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.Add( item3, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.Add( item2, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_LOGO = 10029

def AboutLogoPanelFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item1 = wx.StaticBitmap(parent, ID_LOGO, images.getX4LogoBitmap())#, style=wx.SUNKEN_BORDER)
    item0.Add( item1, 0, wx.ALIGN_CENTER, 5 )

    item0.Add( [ 130, 20 ] , 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.AddGrowableCol( 1 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_VERSION = 10030
ID_BRANCH = 10031
ID_LABELMOD = 10032
ID_MODVERSION = 10033

def AboutProgramPanelFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item0.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( [ 260, 20 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item1 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item2 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item3 = AppDescStaticText( parent, ID_TEXT, "X4 Gestione Aziendale", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.SetFont( wx.Font( 18, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item3.SetName( "appdesc" )
    item2.Add( item3, 0, wx.ALIGN_RIGHT|wx.ALIGN_BOTTOM|wx.LEFT|wx.RIGHT, 5 )

    item2.Add( [ 20, 10 ] , 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item4 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item5 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item6 = wx.StaticText(parent, ID_APPINFO,  version.VERSION_TYPEXT); item6.SetFont(wx.Font(12, wx.SWISS, wx.NORMAL, wx.BOLD)); item6.SetForegroundColour('gray')
    item5.Add( item6, 0, wx.ALIGN_RIGHT|wx.ALIGN_BOTTOM|wx.RIGHT, 5 )

    item7 = wx.StaticText(parent, ID_VERSION,  'v.%s' % version.__version__); item7.SetFont(wx.Font(12, wx.SWISS, wx.NORMAL, wx.BOLD)); item7.SetForegroundColour('gray')
    item5.Add( item7, 0, wx.ALIGN_RIGHT|wx.ALIGN_BOTTOM|wx.RIGHT, 5 )

    item4.Add( item5, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item8 = BranchText(parent, ID_BRANCH)
    item4.Add( item8, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item2.Add( item4, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item9 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item10 = wx.BoxSizer( wx.HORIZONTAL )
    
    item11 = wx.StaticText( parent, ID_LABELMOD, "mod:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item11.SetName( "labelmod" )
    item10.Add( item11, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item12 = wx.StaticText(parent, ID_MODNAME,  version.MODVERSION_NAME); item12.SetName('modname');     item12.SetFont( wx.Font( 13, wx.ROMAN, wx.NORMAL, wx.BOLD ) )

    item10.Add( item12, 0, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item13 = wx.StaticText(parent, ID_MODVERSION,  version.__modversion__); item13.SetName('modversion'); item13.SetFont(wx.Font( 12, wx.SWISS, wx.NORMAL, wx.BOLD ))
    item10.Add( item13, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item9.Add( item10, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item9.AddGrowableCol( 1 )

    item2.Add( item9, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item2.Add( [ 20, 10 ] , 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item2.AddGrowableCol( 0 )

    item1.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item1.Add( [ 16, 16 ] , 0, wx.ALIGN_CENTER, 5 )

    item1.AddGrowableCol( 0 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item0.AddGrowableCol( 1 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_PANGRIDPLUGINS = 10034
ID_PLUGINNAME = 10035
ID_PLUGINDESC = 10036
ID_PLUGINVERS = 10037
ID_PLUGINAUTH = 10038
ID_PLUGININFO = 10039
ID_PLUGINEND = 10040

def PluginsFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item2 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item3 = wx.StaticText( parent, ID_TEXT, "Elenco dei plugin installati", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.SetForegroundColour( wx.BLUE )
    item2.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item4 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item2.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item5 = wx.Panel( parent, ID_PANGRIDPLUGINS, wx.DefaultPosition, [350,160], wx.SUNKEN_BORDER )
    item2.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item2.AddGrowableCol( 0 )

    item2.AddGrowableRow( 2 )

    item1.Add( item2, 0, wx.GROW, 5 )

    item6 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item7 = wx.StaticText( parent, ID_TEXT, "Informazioni sul plugin", wx.DefaultPosition, [350,-1], 0 )
    item7.SetForegroundColour( wx.BLUE )
    item6.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item8 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item6.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item9 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item10 = wx.StaticText( parent, ID_TEXT, "Nome:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.Add( item10, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item11 = wx.StaticText( parent, ID_PLUGINNAME, "plugin", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.Add( item11, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item12 = wx.StaticText( parent, ID_TEXT, "Descrizione:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.Add( item12, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item13 = wx.StaticText( parent, ID_PLUGINDESC, "Descrizione plugin", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.Add( item13, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item14 = wx.StaticText( parent, ID_TEXT, "Versione:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.Add( item14, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item15 = wx.StaticText( parent, ID_PLUGINVERS, "0.0.00", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.Add( item15, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item16 = wx.StaticText( parent, ID_TEXT, "Autore:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.Add( item16, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item17 = wx.StaticText( parent, ID_PLUGINAUTH, "Astra S.r.l.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.Add( item17, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item18 = wx.StaticText( parent, ID_TEXT, "Info:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.Add( item18, 0, wx.ALIGN_RIGHT|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item19 = wx.TextCtrl( parent, ID_PLUGININFO, "", wx.DefaultPosition, [80,180], wx.TE_MULTILINE )
    item9.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item9.AddGrowableCol( 1 )

    item9.AddGrowableRow( 4 )

    item6.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item6.AddGrowableCol( 0 )

    item6.AddGrowableRow( 2 )

    item1.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item1.AddGrowableCol( 1 )

    item1.AddGrowableRow( 0 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item20 = wx.Button( parent, ID_PLUGINEND, "Chiudi", wx.DefaultPosition, wx.DefaultSize, 0 )
    item20.SetDefault()
    item0.Add( item20, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_UPDATESLOGO = 10041
ID_URL = 10042
ID_PANGRIDUPDATES = 10043

def ProgramUpdateFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item2 = wx.StaticBitmap(parent, ID_UPDATESLOGO, images.getProgramUpdateBitmap())#, style=wx.SUNKEN_BORDER)
    item1.Add( item2, 0, wx.ALIGN_CENTER, 5 )

    item3 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item4 = wx.StaticText( parent, ID_TEXT, "Aggiornamenti programma", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item5 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item3.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item6 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item7 = wx.StaticText( parent, ID_TEXT, "URL:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item7, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item8 = wx.StaticText( parent, ID_URL, "http://", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item6.AddGrowableCol( 1 )

    item3.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item3.AddGrowableCol( 0 )

    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item1.AddGrowableCol( 1 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item9 = wx.Panel( parent, ID_PANGRIDUPDATES, wx.DefaultPosition, [600,160], wx.SUNKEN_BORDER )
    item0.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item10 = wx.StaticText( parent, ID_MESSAGE, "-", wx.DefaultPosition, [200,-1], wx.ALIGN_CENTRE )
    item0.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item11 = wx.Gauge( parent, ID_PROGRESS, 100, wx.DefaultPosition, [-1,14], 0 )
    item0.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item12 = wx.StaticText( parent, ID_BYTES, "", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_CENTRE )
    item0.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item13 = wx.BoxSizer( wx.HORIZONTAL )
    
    item14 = wx.Button( parent, ID_CANCEL, "Chiudi", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item14, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item15 = wx.Button( parent, ID_ACTION, "Verifica", wx.DefaultPosition, wx.DefaultSize, 0 )
    item15.SetDefault()
    item13.Add( item15, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item13, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_BACKUPDIR = 10044
ID_BUTREFRESH = 10045
ID_SOLAZI = 10046
ID_PANGRIDBACKUP = 10047
ID_BUTNEW = 10048

def BackupExplorerFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item2 = wx.StaticText( parent, ID_TEXT, "Cartella dei files di backup delle aziende:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item2, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item3 = FolderEntryCtrl( parent, ID_BACKUPDIR, "", wx.DefaultPosition, [280,-1], 0 )
    item3.SetName( "backupdir" )
    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item4 = BitmapButton(parent, ID_BUTREFRESH, awimages.getUndo20Bitmap()); item4.SetName('butrefresh'); item4.SetToolTipString("Ricarica il contenuto della cartella")
    item1.Add( item4, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item5 = wx.CheckBox( parent, ID_SOLAZI, "Mostra solo i backup di questa azienda", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.SetValue( True )
    item5.SetName( "solazi" )
    item1.Add( item5, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item1.AddGrowableCol( 1 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item6 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item0.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item7 = wx.StaticText( parent, ID_TEXT, "Elenco dei files di backup presenti:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item7.SetForegroundColour( wx.BLUE )
    item0.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item8 = wx.Panel( parent, ID_PANGRIDBACKUP, wx.DefaultPosition, [900,350], wx.SUNKEN_BORDER )
    item8.SetName( "pangridbackup" )
    item0.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item9 = wx.Button( parent, ID_BUTNEW, "Crea nuovo backup", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.SetName( "butnew" )
    item0.Add( item9, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 3 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_TITLETEXT = 10049
ID_FILENAME = 10050
ID_COMMENT = 10051
ID_ALLEGATI = 10052
ID_ALLTABLES = 10053
ID_SELECTALL = 10054
ID_TABLES = 10055
ID_WARNING = 10056
ID_BUTOK = 10057

def SpecificheBackupFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.StaticText( parent, ID_TITLETEXT, "Creazione nuovo backup", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.SetForegroundColour( wx.BLUE )
    item1.SetFont( wx.Font( 12, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item1.SetName( "titletext" )
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item2 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item3 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item4 = wx.StaticText( parent, ID_TEXT, "File:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item4, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item5 = wx.TextCtrl( parent, ID_FILENAME, "", wx.DefaultPosition, [200,-1], 0 )
    item5.SetName( "filename" )
    item3.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item6 = wx.StaticText( parent, ID_TEXT, "Commento:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item6, 0, wx.ALIGN_RIGHT|wx.LEFT|wx.BOTTOM, 5 )

    item7 = wx.TextCtrl( parent, ID_COMMENT, "", wx.DefaultPosition, [300,60], wx.TE_MULTILINE )
    item7.SetName( "comment" )
    item3.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item3.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER, 5 )

    item8 = wx.CheckBox( parent, ID_ALLEGATI, "Includi i files degli allegati", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.SetName( "allegati" )
    item3.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item3.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER, 5 )

    item9 = wx.CheckBox( parent, ID_ALLTABLES, "Includi tutte le tabelle dell'azienda", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.SetValue( True )
    item9.SetName( "alltables" )
    item3.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item3.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER, 5 )

    item10 = wx.CheckBox( parent, ID_SELECTALL, "Seleziona tutte le tabelle elencate", wx.DefaultPosition, wx.DefaultSize, 0 )
    item10.SetValue( True )
    item10.SetName( "selectall" )
    item3.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item11 = wx.StaticText( parent, ID_TEXT, "Tabelle:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item11, 0, wx.ALIGN_RIGHT|wx.LEFT|wx.BOTTOM, 5 )

    item12 = ElencoTabelleAziendaCheckListBox( parent, ID_TABLES, wx.DefaultPosition, [500,260], [], wx.LB_SINGLE )
    item12.SetName( "tables" )
    item3.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item3.AddGrowableCol( 1 )

    item3.AddGrowableRow( 5 )

    item0.Add( item3, 0, wx.GROW, 5 )

    item13 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item14 = wx.StaticText( parent, ID_WARNING, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.SetForegroundColour( wx.RED )
    item14.SetFont( wx.Font( 12, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item14.SetName( "warning" )
    item13.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item15 = wx.Button( parent, ID_BUTOK, "Avvia Backup", wx.DefaultPosition, [120,-1], 0 )
    item15.SetFont( wx.Font( 10, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item15.SetName( "butok" )
    item13.Add( item15, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item13.AddGrowableCol( 0 )

    item0.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 2 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_LOGO_AZIENDALE = 10058

def UserLicenseInfoFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item1 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item2 = LogoAziendaleBitmap(parent, ID_LOGO_AZIENDALE, size=(64,64)); item2.SetName('logo_aziendale')
    item1.Add( item2, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item3 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item4 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.SetForegroundColour( wx.BLUE )
    item4.SetFont( wx.Font( 12, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item4.SetName( "lic_ragsoc" )
    item3.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item5 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.SetForegroundColour( wx.BLUE )
    item5.SetFont( wx.Font( 10, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item5.SetName( "lic_piva" )
    item3.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item3.AddGrowableCol( 0 )

    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item1.AddGrowableCol( 1 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

ID_QUIT = 10059
ID_MENUFILE = 10060
ID_GESCLIENT = 10061
ID_GESCLIENT_CATEGO = 10062
ID_GESCLIENT_STATUS = 10063
ID_MENU = 10064
ID_GESFORNIT = 10065
ID_GESFORNIT_CATEGO = 10066
ID_GESFORNIT_STATUS = 10067
ID_GESALQIVA = 10068
ID_CFGSTATI = 10069
ID_MENUTABGLOBAL = 10070
ID_GESBILPDC = 10071
ID_GESTIPANA = 10072
ID_GESBILMAS = 10073
ID_GESBILCON = 10074
ID_GESSTATPDC = 10075
ID_GESBILSTR = 10076
ID_GESBRIMAS = 10077
ID_GESBRICON = 10078
ID_GESBILRICLSTR = 10079
ID_GESTBILRICL = 10080
ID_GESBILCEE = 10081
ID_GESPDCCEE = 10082
ID_GESTBILCEE = 10083
ID_GESCASSE = 10084
ID_GESBANCHE = 10085
ID_GESEFFETT = 10086
ID_MENUTABCONTAB = 10087
ID_GESPROD = 10088
ID_GESPROD_TIPART = 10089
ID_GESPROD_CATART = 10090
ID_GESPROD_GRUART = 10091
ID_GESPROD_MARART = 10092
ID_GESPROD_STATUS = 10093
ID_GESINVSTR = 10094
ID_GESPROD_GRUPREZ = 10095
ID_GESPROD_TIPLIST = 10096
ID_GESLISVEN = 10097
ID_GESSTALIS = 10098
ID_LISVEN = 10099
ID_GESGRPCLI = 10100
ID_STAGRPCLI = 10101
ID_GRIPCLI = 10102
ID_GESGRPFOR = 10103
ID_STAGRPFOR = 10104
ID_GRIPFOR = 10105
ID_GESPRODPROMO = 10106
ID_GESTRACAU = 10107
ID_GESTRACUR = 10108
ID_GESTRAPOR = 10109
ID_GESTRAVET = 10110
ID_GESTRAASP = 10111
ID_GESTRACON = 10112
ID_MENUTRASP = 10113
ID_BARCODESPOT = 10114
ID_MENUBARCODES = 10115
ID_MENUTABMAGAZZ = 10116
ID_GESMODPAG = 10117
ID_GESGRUSCA = 10118
ID_MENUTABSCAD = 10119
ID_GESTZONE = 10120
ID_GESTAGENTI = 10121
ID_GESTSPEINC = 10122
ID_MENUTABVEND = 10123
ID_MENUTAB = 10124
ID_CONTABGES_ACQVEN = 10125
ID_CONTABGES_INCPAG = 10126
ID_CONTABGES_ALTRO = 10127
ID_CONTABGES_SOLIVA = 10128
ID_MENUCONTINS = 10129
ID_INTCONCLI = 10130
ID_INTCONFOR = 10131
ID_INTCONCAS = 10132
ID_INTCONBAN = 10133
ID_INTCONEFF = 10134
ID_INTCONPDC = 10135
ID_INTCONTAB = 10136
ID_INTREGCON = 10137
ID_INTREGIVA = 10138
ID_INTALIQIVA = 10139
ID_FATCONACQVEN = 10140
ID_VENDAZIPRIV = 10141
ID_CONTAB_SPESOM = 10142
ID_MENUCONTINT = 10143
ID_CTR_CASSA = 10144
ID_CTR_QUADCON = 10145
ID_CONTAB_GIORNALE = 10146
ID_CONTAB_MASTRI = 10147
ID_MENUSTAFIS = 10148
ID_CONTABIL_VERIF = 10149
ID_CONTABIL_GEST = 10150
ID_CONTABIL_CONTR = 10151
ID_MENUBIL = 10152
ID_CONTABRI_VERIF = 10153
ID_CONTABRI_GEST = 10154
ID_CONTABRI_CONTR = 10155
ID_BILRICL = 10156
ID_CONTABIL_CEE = 10157
ID_BILCEE = 10158
ID_REGIVA = 10159
ID_LIQIVA = 10160
ID_IVASEQ = 10161
ID_MENUIVA = 10162
ID_MENUCONTGES = 10163
ID_MENUCONT = 10164
ID_MAGAZZINS = 10165
ID_INTPROD = 10166
ID_INTDOCMAG = 10167
ID_INTMOVMAG = 10168
ID_INTINVENT = 10169
ID_INTSOTTOSC = 10170
ID_INTMAGCLI = 10171
ID_INTMAGACC = 10172
ID_INTMAGSRCDES = 10173
ID_INTMAGFOR = 10174
ID_INTEVAMAG = 10175
ID_INTGIAPRE = 10176
ID_STATFATCLI = 10177
ID_STATFATCLICAT = 10178
ID_STATFATPRO = 10179
ID_STATFATPROCLI = 10180
ID_STATFATAGE = 10181
ID_STATFATCATART = 10182
ID_PDCSINTART = 10183
ID_STATCOSACQ = 10184
ID_STATPREAPP = 10185
ID_PROVAGE = 10186
ID_MENUPROVAGE = 10187
ID_INTDOCVET = 10188
ID_MAGAZZINT = 10189
ID_STADIFF = 10190
ID_MAGOPEDIF = 10191
ID_MAGPRODPRORIC = 10192
ID_MAGPRODCOSTIZERO = 10193
ID_MENUMAGELAB = 10194
ID_MENUMAG = 10195
ID_SCADINS = 10196
ID_INTPCFCLI = 10197
ID_INTPCFFOR = 10198
ID_SCAD_SCAD = 10199
ID_SCAD_SCADGRP = 10200
ID_SCAD_CTRQUAD = 10201
ID_SCAD_GLOBAL = 10202
ID_SCAD_GLOBAL_INCASSI = 10203
ID_SCAD_GLOBAL_PAGAMENTI = 10204
ID_SCAD_GLOBAL_EFFETTIDAEMETTERE = 10205
ID_SCAD_GLOBAL_EFFETTIEMESSI = 10206
ID_SCAD_GLOBAL_EFFETTIINSOLUTI = 10207
ID_MENUSCAD = 10208
ID_EMIEFF = 10209
ID_RAGGRPCF = 10210
ID_MENUEFF = 10211
ID_CFGCONCAU = 10212
ID_CFGAUTCON = 10213
ID_CFGPDCRANGE = 10214
ID_CFGPROGRCON = 10215
ID_CFGSPESOM = 10216
ID_CFGREGIVA = 10217
ID_CFGLIQIVA = 10218
ID_MENUSETUP_CONTAB = 10219
ID_CFGMAGCAU = 10220
ID_CFGMAGAZZ = 10221
ID_CFGAUTMAG = 10222
ID_CFGFTDIF = 10223
ID_MENUSETUP_MAGAZZ = 10224
ID_CFGAZIENDA = 10225
ID_CFGWKS = 10226
ID_CFGUPDATES = 10227
ID_CFGLICENSE = 10228
ID_CFGACTIVATIONCODES = 10229
ID_MENUSETUP_IMPOSTAZIONI = 10230
ID_CFGEMAIL = 10231
ID_CFGXMPP = 10232
ID_CFGDOCSEMAIL = 10233
ID_MENUSETUP_COMM = 10234
ID_CFGTIPEVENT = 10235
ID_CFGEVENTMGR = 10236
ID_MENUEVENTI = 10237
ID_MENUSETUP_OPZIONI = 10238
ID_MENUSETUP = 10239
ID_CHIUSCONT_SOVRAPP = 10240
ID_CHIUSCONT_GENMOV = 10241
ID_CHIUSCONT_ANNUALE = 10242
ID_MENUCHIUSCONTAB = 10243
ID_CHIUSIVA_CHIUSIVA = 10244
ID_MENUCHIUSIVA = 10245
ID_CHIUSMAGAZZ_CREACOSTI = 10246
ID_CHIUSMAGAZZ_EDITGIAC = 10247
ID_CHIUSMAGAZZ_GENMOVINI = 10248
ID_MENUCHIUSMAGAZZ = 10249
ID_MENUCHIUSURE = 10250
ID_BACKUPEXPLORER = 10251
ID_MENUSTRUMENTI = 10252
ID_ABOUT = 10253
ID_UPDATES = 10254

def XMenuBarFunc():
    item0 = wx.MenuBar(wx.MB_DOCKABLE)
    
    item1 = wx.Menu()
    item1.Append( ID_QUIT, "Esci\tAlt-Ctrl-Q", "Chiude la sessione di lavoro" )
    item0.Append( item1, "File" )
    
    item2 = wx.Menu()
    
    item3 = wx.Menu()
    item3.Append( ID_GESCLIENT, "Clienti\tCtrl-C", "Gestione tabella Clienti" )
    item3.Append( ID_GESCLIENT_CATEGO, "Categorie clienti", "Gestione tabella Categorie Clienti" )
    item3.Append( ID_GESCLIENT_STATUS, "Status clienti", "Gestione tabella Status Clienti" )
    item3.AppendSeparator()
    item3.Append( ID_GESFORNIT, "Fornitori\tCtrl-F", "Gestione tabella Fornitori" )
    item3.Append( ID_GESFORNIT_CATEGO, "Categorie Fornitori", "Gestione tabella Categorie Fornitori" )
    item3.Append( ID_GESFORNIT_STATUS, "Status fornitori", "Gestione tabella Status Fornitori" )
    item3.AppendSeparator()
    item3.Append( ID_GESALQIVA, "Aliquote IVA\tCtrl-I", "Gestione tabella Aliquote IVA" )
    item3.AppendSeparator()
    item3.Append( ID_CFGSTATI, "Stati\tCtrl-S", "Manutenzione tabella Stati" )
    item2.AppendMenu( ID_MENUTABGLOBAL, "Globali", item3 )

    
    item4 = wx.Menu()
    item4.Append( ID_GESBILPDC, "Piano dei Conti\tCtrl-O", "Gestione tabella Sottoconti (Intero Piano dei Conti)" )
    item4.AppendSeparator()
    item4.Append( ID_GESTIPANA, "Tipi Sottoconto", "Gestione tabella Tipi di Sottoconto (classificazione non contabile)" )
    item4.Append( ID_GESBILMAS, "Mastri", "Gestione tabella Mastri di Bilancio" )
    item4.Append( ID_GESBILCON, "Conti", "Gestione tabella Conti di Bilancio" )
    item4.Append( ID_GESSTATPDC, "Status Sottoconti", "Gestione tabella Status Sottoconti" )
    item4.Append( ID_GESBILSTR, "Struttura del Piano dei Conti", "Visualizzazione e stampa la struttura gerarchica del Piano dei Conti" )
    
    item5 = wx.Menu()
    item5.Append( ID_GESBRIMAS, "Mastri", "Gestione tabella Mastri Bilancio Riclassificato" )
    item5.Append( ID_GESBRICON, "Conti", "Gestione tabella Conti Bilancio Riclassificato" )
    item5.Append( ID_GESBILRICLSTR, "Struttura del Piano dei Conti", "Visualizzazione e stampa la struttura gerarchica del Piano dei Conti" )
    item4.AppendMenu( ID_GESTBILRICL, "Bilancio riclassificato", item5 )

    
    item6 = wx.Menu()
    item6.Append( ID_GESBILCEE, "Classificazioni Bilancio CEE", "Gestione tabella Piano dei Conti riclassificato CEE" )
    item6.Append( ID_GESPDCCEE, "Piano dei Conti riclassificato CEE", "Gestione tabella Sottoconti (Intero Piano dei Conti) visto secondo la classificazione CEE" )
    item4.AppendMenu( ID_GESTBILCEE, "Bilancio CEE", item6 )

    item4.AppendSeparator()
    item4.Append( ID_GESCASSE, "Casse\tCtrl-A", "Gestione tabella Sottoconti di tipo Cassa" )
    item4.Append( ID_GESBANCHE, "Banche\tCtrl-B", "Gestione tabella Sottoconti di tipo Banca" )
    item4.Append( ID_GESEFFETT, "Effetti\tCtrl-E", "Gestione tabella Sottoconti di tipo Effetto" )
    item2.AppendMenu( ID_MENUTABCONTAB, "Contabilità", item4 )

    
    item7 = wx.Menu()
    item7.Append( ID_GESPROD, "Prodotti\tCtrl-P", "Gestione tabella Articoli di Magazzino" )
    item7.AppendSeparator()
    item7.Append( ID_GESPROD_TIPART, "Tipi Prodotto", "Gestione tabella Tipi prodotto" )
    item7.Append( ID_GESPROD_CATART, "Categorie", "Gestione tabella Categorie merce" )
    item7.Append( ID_GESPROD_GRUART, "Gruppi", "Gestione tabella Gruppi merce" )
    item7.Append( ID_GESPROD_MARART, "Marche prodotti", "Gestione tabella Gruppi merce" )
    item7.Append( ID_GESPROD_STATUS, "Status prodotti", "Gestione tabella Status prodotti" )
    item7.Append( ID_GESINVSTR, "Struttura Inventario", "Visualizzazione e stampa la struttura gerarchica del'inventario" )
    item7.AppendSeparator()
    item7.Append( ID_GESPROD_GRUPREZ, "Gruppi prezzo", "Gestione tabella Gruppi prezzo" )
    item7.AppendSeparator()
    
    item8 = wx.Menu()
    item8.Append( ID_GESPROD_TIPLIST, "Tipi Listino", "Gestione tabella Tipi listino" )
    item8.Append( ID_GESLISVEN, "Manutenzione", "Gestione dei Listini di vendita" )
    item8.Append( ID_GESSTALIS, "Consultazione prezzi in vigore", "Consultazione dei prezzi attualmente in vigore sui Listini di Vendita" )
    item7.AppendMenu( ID_LISVEN, "Listini di vendita", item8 )

    
    item9 = wx.Menu()
    item9.Append( ID_GESGRPCLI, "Manutenzione", "Gestione delle Griglie di prezzo per i clienti" )
    item9.Append( ID_STAGRPCLI, "Consultazione prezzi in vigore", "Consultazione dei prezzi attualmente in vigore sulle Griglie di prezzo per i clienti" )
    item7.AppendMenu( ID_GRIPCLI, "Griglie prezzi clienti", item9 )

    
    item10 = wx.Menu()
    item10.Append( ID_GESGRPFOR, "Manutenzione", "Gestione delle Griglie di prezzo per i fornitori" )
    item10.Append( ID_STAGRPFOR, "Consultazione prezzi in vigore", "Consultazione dei prezzi attualmente in vigore sulle Griglie di prezzo per i fornitori" )
    item7.AppendMenu( ID_GRIPFOR, "Griglie prezzi fornitori", item10 )

    item7.Append( ID_GESPRODPROMO, "Condizioni promozionali", "Gestione condizioni promozionali di vendita" )
    item7.AppendSeparator()
    
    item11 = wx.Menu()
    item11.Append( ID_GESTRACAU, "Causali", "Gestione tabella Causali di trasporto" )
    item11.Append( ID_GESTRACUR, "A cura", "Gestione tabella Trasporto a cura" )
    item11.Append( ID_GESTRAPOR, "Porto", "Gestione tabella Tipo di porto" )
    item11.Append( ID_GESTRAVET, "Vettori", "Gestione tabella Vettori di consegna" )
    item11.Append( ID_GESTRAASP, "Aspetto esteriore dei beni", "Gestione tabella Aspetto esteriore dei beni" )
    item11.Append( ID_GESTRACON, "Tipi di incasso dei contrassegni", "Gestione tabella Tipi di incasso dei contrassegni" )
    item7.AppendMenu( ID_MENUTRASP, "Dati trasporto", item11 )

    item7.AppendSeparator()
    
    item12 = wx.Menu()
    item12.Append( ID_BARCODESPOT, "Stampa articoli spot", "" )
    item7.AppendMenu( ID_MENUBARCODES, "Gestione codici a barre", item12 )

    item2.AppendMenu( ID_MENUTABMAGAZZ, "Magazzino", item7 )

    
    item13 = wx.Menu()
    item13.Append( ID_GESMODPAG, "Modalità di pagamento", "Gestione tabella Modalità di pagamento" )
    item13.Append( ID_GESGRUSCA, "Criteri di gruppo", "Gestione tabella Raggruppamenti per Scadenzario Clienti/Fornitori" )
    item2.AppendMenu( ID_MENUTABSCAD, "Scadenzario Clienti/Fornitori", item13 )

    item2.AppendSeparator()
    
    item14 = wx.Menu()
    item14.Append( ID_GESTZONE, "Zone", "Gestione tabella Zone" )
    item14.Append( ID_GESTAGENTI, "Agenti", "Gestione tabella Agenti" )
    item14.Append( ID_GESTSPEINC, "Spese di incasso", "Gestione tabella Spese di incasso su effetti" )
    item2.AppendMenu( ID_MENUTABVEND, "Organizzazione Vendite", item14 )

    item0.Append( item2, "Tabelle" )
    
    item15 = wx.Menu()
    
    item16 = wx.Menu()
    item16.Append( ID_CONTABGES_ACQVEN, "Acquisti e Vendite\tCtrl-F5", "Inserimento registrazioni IVA (Acquisti/Vendite)" )
    item16.Append( ID_CONTABGES_INCPAG, "Incassi e Pagamenti\tCtrl-F6", "Inserimento registrazioni di tipo Incasso/Pagamento" )
    item16.Append( ID_CONTABGES_ALTRO, "Altre registrazioni\tCtrl-F7", "Inserimento registrazioni semplici/composte senza legame a scadenzari" )
    item16.AppendSeparator()
    item16.Append( ID_CONTABGES_SOLIVA, "Scritture di sola IVA\tCtrl-F8", "Inserimento registrazioni di sola IVA" )
    item15.AppendMenu( ID_MENUCONTINS, "Inserisci", item16 )

    
    item17 = wx.Menu()
    
    item18 = wx.Menu()
    item18.Append( ID_INTCONCLI, "Clienti\tAlt-C", "Interrogazione Mastri Clienti con dati anagrafici completi" )
    item18.Append( ID_INTCONFOR, "Fornitori\tAlt-F", "Interrogazione Mastri Fornitori con dati anagrafici completi" )
    item18.AppendSeparator()
    item18.Append( ID_INTCONCAS, "Casse\tAlt-A", "Interrogazione Mastri Sottoconti Cassa con dati anagrafici completi" )
    item18.Append( ID_INTCONBAN, "Banche\tAlt-B", "Interrogazione Mastri Sottoconti Banca con dati anagrafici completi" )
    item18.Append( ID_INTCONEFF, "Effetti\tAlt-E", "Interrogazione Mastri Sottoconti Effetti con dati anagrafici completi" )
    item18.AppendSeparator()
    item18.Append( ID_INTCONPDC, "Piano dei conti\tAlt-O", "Interrogazione Mastri intero Piano dei Conti con sole informazioni contabili" )
    item17.AppendMenu( ID_INTCONTAB, "Mastri", item18 )

    item17.Append( ID_INTREGCON, "Registrazioni contabili", "Interrogazione registrazioni contabili" )
    item17.Append( ID_INTREGIVA, "Registrazioni IVA", "Interrogazione registrazioni IVA" )
    item17.Append( ID_INTALIQIVA, "Utilizzo Aliquote IVA\tAlt-I", "Interrogazione Aliquote IVA" )
    item17.AppendSeparator()
    item17.Append( ID_FATCONACQVEN, "Analisi fatturato acquisti/vendite", "Analizza le vendite di un periodo e ne evidenzia imponibile ed imposta per anagrafica" )
    item17.Append( ID_VENDAZIPRIV, "Sintesi vendite privati/aziende", "Analizza le vendite di un periodo e ne evidenzia imponibile ed imposta per anagrafica" )
    item17.Append( ID_CONTAB_SPESOM, "Spesometro", "Analisi operazioni di acquisto/vendita per compilazione spesometro" )
    item15.AppendMenu( ID_MENUCONTINT, "Interroga", item17 )

    
    item19 = wx.Menu()
    item19.Append( ID_CTR_CASSA, "Controllo saldo cassa/banca", "Controllo saldo contabile sottoconti Cassa/Banca" )
    item19.Append( ID_CTR_QUADCON, "Controllo quadratura registrazioni", "Controlli di coerenza sulle registrazioni contabili" )
    item19.AppendSeparator()
    
    item20 = wx.Menu()
    item20.Append( ID_CONTAB_GIORNALE, "Libro giornale", "Interrogazione e stampa del Libro Giornale" )
    item20.Append( ID_CONTAB_MASTRI, "Mastri sottoconto", "Interrogazione e stampa dei Mastri" )
    item19.AppendMenu( ID_MENUSTAFIS, "Stampe fiscali", item20 )

    
    item21 = wx.Menu()
    item21.Append( ID_CONTABIL_VERIF, "Verifica", "Interrogazione Bilancio di Verifica" )
    item21.Append( ID_CONTABIL_GEST, "Gestionale", "Interrogazione Bilancio Gestionale" )
    item21.Append( ID_CONTABIL_CONTR, "Contrapposto", "Interrogazione Bilancio Contrapposto" )
    item19.AppendMenu( ID_MENUBIL, "Bilancio", item21 )

    
    item22 = wx.Menu()
    item22.Append( ID_CONTABRI_VERIF, "Verifica", "Interrogazione Bilancio di Verifica Riclassificato" )
    item22.Append( ID_CONTABRI_GEST, "Gestionale", "Interrogazione Bilancio Gestionale Riclassificato" )
    item22.Append( ID_CONTABRI_CONTR, "Contrapposto", "Interrogazione Bilancio Contrapposto Riclassificato" )
    item19.AppendMenu( ID_BILRICL, "Bilancio Riclassificato", item22 )

    
    item23 = wx.Menu()
    item23.Append( ID_CONTABIL_CEE, "Bilancio Riclassificato CEE", "Interrogazione Bilancio Riclassificato CEE" )
    item19.AppendMenu( ID_BILCEE, "Bilancio Riclassificato CEE", item23 )

    item19.AppendSeparator()
    
    item24 = wx.Menu()
    item24.Append( ID_REGIVA, "Registri IVA", "Consultazione e stampa Registri IVA" )
    item24.Append( ID_LIQIVA, "Liquidazione IVA", "Interrogazione e gestione Liquidazioni IVA" )
    item24.Append( ID_IVASEQ, "Controllo sequenza protocolli", "Controllo corretta sequenza protocolli IVA di un registro" )
    item19.AppendMenu( ID_MENUIVA, "IVA", item24 )

    item15.AppendMenu( ID_MENUCONTGES, "Gestione", item19 )

    item0.Append( item15, "Contabilità" )
    
    item25 = wx.Menu()
    item25.Append( ID_MAGAZZINS, "Immissione documenti\tCtrl-D", "Inserimento documenti di magazzino" )
    
    item26 = wx.Menu()
    item26.Append( ID_INTPROD, "Prodotto\tAlt-P", "Interrogazione scheda e mastro prodotto" )
    item26.Append( ID_INTDOCMAG, "Documenti\tAlt-D", "Interrogazione documenti" )
    item26.Append( ID_INTMOVMAG, "Movimenti\tAlt-M", "Interrogazione movimenti" )
    
    item27 = wx.Menu()
    item27.Append( ID_INTINVENT, "Inventario\tAlt-I", "Interrogazione e stampa Inventari" )
    item27.Append( ID_INTSOTTOSC, "Sottoscorta", "Interrogazione e stampa prodotti sottoscorta" )
    item26.AppendMenu( ID_MENU, "Giacenze", item27 )

    item26.AppendSeparator()
    
    item28 = wx.Menu()
    item28.Append( ID_INTMAGCLI, "Clienti", "Interrogazione scheda e dati di magazzino dei clienti" )
    item28.Append( ID_INTMAGACC, "Situazione acconti clienti", "Interrogazione acconti disponibili dei clienti" )
    item28.Append( ID_INTMAGSRCDES, "Ricerca destinazioni merce", "Ricerca clienti da destinazione merce" )
    item28.AppendSeparator()
    item28.Append( ID_INTMAGFOR, "Fornitori", "Interrogazione scheda e dati di magazzino dei fornitori" )
    item26.AppendMenu( ID_MENU, "Anagrafiche", item28 )

    item26.AppendSeparator()
    
    item29 = wx.Menu()
    item29.Append( ID_INTEVAMAG, "Stato evasione movimenti\tAlt-V", "" )
    item29.Append( ID_INTGIAPRE, "Inventario presunto", "Interrogazione e stampa Inventario presunto" )
    item26.AppendMenu( ID_MENU, "Evasione", item29 )

    item26.AppendSeparator()
    
    item30 = wx.Menu()
    item30.Append( ID_STATFATCLI, "Fatturato Clienti", "Statistica sul fatturato clienti" )
    item30.Append( ID_STATFATCLICAT, "Fatturato Clienti per Categoria prodotto", "Statistica sul fatturato clienti per categoria merce" )
    item30.AppendSeparator()
    item30.Append( ID_STATFATPRO, "Fatturato Prodotti", "Statistica sul fatturato prodotti" )
    item30.Append( ID_STATFATPROCLI, "Fatturato Prodotti per Cliente", "Statistica sul fatturato prodotti per cliente" )
    item30.AppendSeparator()
    item30.Append( ID_STATFATAGE, "Fatturato Agenti", "Statistica sul fatturato agenti" )
    item30.Append( ID_STATFATCATART, "Fatturato Categorie prodotto", "Statistica sul fatturato per categoria prodotto" )
    item30.Append( ID_PDCSINTART, "Schede clienti con sintesi vendite prodotti", "" )
    item30.AppendSeparator()
    item30.Append( ID_STATCOSACQ, "Valutazione Costi di Acquisto", "Statistica sui costi di acquisto presenti" )
    item30.Append( ID_STATPREAPP, "Valutazione Prezzi di Vendita", "Statistica sui prezzi di vendita applicati" )
    item26.AppendMenu( ID_MENU, "Statistiche", item30 )

    
    item31 = wx.Menu()
    item31.Append( ID_PROVAGE, "Calcolo provvigioni agenti", "Visualizza e stampa le provvigioni degli agenti" )
    item26.AppendMenu( ID_MENUPROVAGE, "Provvigoni agenti", item31 )

    item26.AppendSeparator()
    item26.Append( ID_INTDOCVET, "Vettori", "Interrogazione vettori" )
    item25.AppendMenu( ID_MAGAZZINT, "Interroga", item26 )

    
    item32 = wx.Menu()
    item32.Append( ID_STADIFF, "Stampa differita", "Stampa un insieme di documenti" )
    item32.AppendSeparator()
    item25.AppendMenu( ID_MAGOPEDIF, "Operazioni differite", item32 )

    
    item33 = wx.Menu()
    item33.Append( ID_MAGPRODPRORIC, "Ricalcolo progressivi prodotti", "" )
    item33.Append( ID_MAGPRODCOSTIZERO, "Aggiornamento costi nulli sui movimenti", "" )
    item25.AppendMenu( ID_MENUMAGELAB, "Elaborazioni", item33 )

    item0.Append( item25, "Magazzino" )
    
    item34 = wx.Menu()
    item34.Append( ID_SCADINS, "Inserisci", "" )
    
    item35 = wx.Menu()
    item35.Append( ID_INTPCFCLI, "Clienti", "Interrogazione Scadenzario Clienti con dati anagrafici completi" )
    item35.Append( ID_INTPCFFOR, "Fornitori", "Interrogazione Scadenzario Fornitori con dati anagrafici completi" )
    item34.AppendMenu( ID_MENU, "Interroga", item35 )

    
    item36 = wx.Menu()
    item36.Append( ID_SCAD_SCAD, "Scadenzario Clienti/Fornitori", "Interrogazione Scadenzari Clienti/Fornitori" )
    item36.Append( ID_SCAD_SCADGRP, "Scadenzario Clienti/Fornitori di gruppo", "Interrogazione Scadenzari Clienti/Fornitori di gruppo" )
    item36.Append( ID_SCAD_CTRQUAD, "Controllo quadratura con mastri", "" )
    
    item37 = wx.Menu()
    item37.Append( ID_SCAD_GLOBAL, "Analisi scadenzario globale (cash-flow)", "Analisi dinamica delle scadenze Clienti/Fornitori" )
    item37.AppendSeparator()
    item37.Append( ID_SCAD_GLOBAL_INCASSI, "Previsione generale incassi", "Analizza le partite dei clienti e ne sintetizza le scadenze" )
    item37.Append( ID_SCAD_GLOBAL_PAGAMENTI, "Previsione generale pagamenti", "Analizza le partite dei fornitori e ne sintetizza le scadenze" )
    item37.AppendSeparator()
    item37.Append( ID_SCAD_GLOBAL_EFFETTIDAEMETTERE, "Portafoglio effetti da emettere", "Analizza gli effetti da emettere e ne sintetizza le scadenze" )
    item37.Append( ID_SCAD_GLOBAL_EFFETTIEMESSI, "Scadenzario effetti", "Analizza gli effetti emessi e ne sintetizza le scadenze" )
    item37.AppendSeparator()
    item37.Append( ID_SCAD_GLOBAL_EFFETTIINSOLUTI, "Effetti insoluti", "Analizza gli effetti insoluti e ne sintetizza le scadenze" )
    item36.AppendMenu( ID_MENU, "Cash flow", item37 )

    item34.AppendMenu( ID_MENU, "Gestione", item36 )

    item0.Append( item34, "Scadenzari" )
    
    item38 = wx.Menu()
    item38.Append( ID_EMIEFF, "Gestione ed emissione effetti", "Manutenzione e Gestione Effetti" )
    item38.Append( ID_RAGGRPCF, "Accorpamento scadenze", "" )
    item38.AppendSeparator()
    item38.Append( ID_SCAD_GLOBAL_EFFETTIDAEMETTERE, "Portafoglio effetti da emettere", "Analizza gli effetti da emettere e ne sintetizza le scadenze" )
    item38.Append( ID_SCAD_GLOBAL_EFFETTIEMESSI, "Scadenzario effetti", "Analizza gli effetti emessi e ne sintetizza le scadenze" )
    item38.AppendSeparator()
    item38.Append( ID_SCAD_GLOBAL_EFFETTIINSOLUTI, "Effetti insoluti", "Analizza gli effetti insoluti e ne sintetizza le scadenze" )
    item0.Append( item38, "Effetti" )
    
    item39 = wx.Menu()
    
    item40 = wx.Menu()
    
    item41 = wx.Menu()
    item41.Append( ID_CFGCONCAU, "Causali", "Manutenzione tabella Causali contabili" )
    item41.Append( ID_CFGAUTCON, "Automatismi", "Impostazione automatismi contaibili" )
    item41.Append( ID_CFGPDCRANGE, "Range sottoconti", "" )
    item41.AppendSeparator()
    item41.Append( ID_CFGPROGRCON, "Progressivi", "Manutenzione dei progressivi contabili" )
    item41.Append( ID_CFGSPESOM, "Massimali spesometro", "Imposta i massimali per anno di aziende/privati per lo spesometro" )
    item41.AppendSeparator()
    
    item42 = wx.Menu()
    item42.Append( ID_CFGREGIVA, "Registri", "Manutenzione tabella Registri IVA" )
    item42.Append( ID_CFGLIQIVA, "Progressivi liquidazioni", "Manutenzione progressivi IVA" )
    item41.AppendMenu( ID_MENU, "IVA", item42 )

    item40.AppendMenu( ID_MENUSETUP_CONTAB, "Contabilità", item41 )

    
    item43 = wx.Menu()
    item43.Append( ID_CFGMAGCAU, "Causali", "Manutenzione tabella Causali Magazzino (Documenti/Movimenti)" )
    item43.Append( ID_CFGMAGAZZ, "Magazzini", "Gestione tabella Magazzini" )
    item43.Append( ID_CFGAUTMAG, "Automatismi", "Impostazione Automatismi Magazzino" )
    item43.Append( ID_CFGFTDIF, "Fatturazione differita", "Impostazione tipi di fatturazione e/o raggruppamento documenti" )
    item40.AppendMenu( ID_MENUSETUP_MAGAZZ, "Magazzino", item43 )

    item40.AppendSeparator()
    
    item44 = wx.Menu()
    item44.Append( ID_CFGAZIENDA, "Setup Azienda", "Imposta i dati aziendali e le caratteristiche di base della sua gestione" )
    item44.Append( ID_CFGWKS, "Setup Workstation", "Impostazione caratteristiche del posto di lavoro" )
    item44.Append( ID_CFGUPDATES, "Setup Aggiornamenti", "Impostazio il download e la distribuzione degli aggiornamenti" )
    item44.AppendSeparator()
    item44.Append( ID_CFGLICENSE, "Licenza d'uso", "Imposta il tipo di licenza d'so del programma" )
    item44.Append( ID_CFGACTIVATIONCODES, "Codici di attivazione", "" )
    item40.AppendMenu( ID_MENUSETUP_IMPOSTAZIONI, "Impostazioni", item44 )

    
    item45 = wx.Menu()
    
    item46 = wx.Menu()
    item46.Append( ID_CFGEMAIL, "Setup Posta elettronica", "Imposta i parametri occorrenti alla spedizione di messaggi email" )
    item46.Append( ID_CFGXMPP, "Setup Messaggistica immediata", "Imposta i parametri occorrenti alla spedizione di messaggi XMPP" )
    item46.AppendSeparator()
    item46.Append( ID_CFGDOCSEMAIL, "Setup invio documenti per posta elettronica", "Imposta i parametri occorrenti alla spedizione di documenti via email" )
    item45.AppendMenu( ID_MENUSETUP_COMM, "Comunicazioni", item46 )

    
    item47 = wx.Menu()
    item47.Append( ID_CFGTIPEVENT, "Tipi evento", "Gestione tabella Tipi evento" )
    item47.AppendSeparator()
    item47.Append( ID_CFGEVENTMGR, "Eventi", "Gestione tabella Eventi" )
    item45.AppendMenu( ID_MENUEVENTI, "Eventi", item47 )

    item40.AppendMenu( ID_MENUSETUP_OPZIONI, "Opzioni", item45 )

    item39.AppendMenu( ID_MENUSETUP, "Setup", item40 )

    
    item48 = wx.Menu()
    
    item49 = wx.Menu()
    item49.Append( ID_CHIUSCONT_SOVRAPP, "Attiva sovrapposizione di esercizi", "Attiva la sovrapposizione d'esercizio" )
    item49.Append( ID_CHIUSCONT_GENMOV, "Genera movimenti di chiusura/apertura", "Genera i movimenti di chiusura/apertura" )
    item49.Append( ID_CHIUSCONT_ANNUALE, "Chiusura contabile", "Chiude definitivamente l'esercizio in corso" )
    item48.AppendMenu( ID_MENUCHIUSCONTAB, "Contabilità", item49 )

    
    item50 = wx.Menu()
    item50.Append( ID_CHIUSIVA_CHIUSIVA, "Chiusura IVA", "Riporta il credito di fine anno come credito IVA compensabile per l'anno successivo" )
    item48.AppendMenu( ID_MENUCHIUSIVA, "IVA", item50 )

    
    item51 = wx.Menu()
    item51.Append( ID_CHIUSMAGAZZ_CREACOSTI, "Consolidamento costi", "Consolida i costi e le giacenze alla data di chiusura" )
    item51.Append( ID_CHIUSMAGAZZ_EDITGIAC, "Manutenzione giacenze rilevate", "Edita le giacenze rilevate ed i costi dei prodotti" )
    item51.Append( ID_CHIUSMAGAZZ_GENMOVINI, "Genera movimenti giacenza iniziale", "Genera i movimenti di giacenza iniziale" )
    item48.AppendMenu( ID_MENUCHIUSMAGAZZ, "Magazzino", item51 )

    item39.AppendMenu( ID_MENUCHIUSURE, "Chiusure", item48 )

    item39.Append( ID_BACKUPEXPLORER, "Backup Explorer\tAlt-Ctrl-B", "Backup e Restore del database dell'azienda" )
    item0.Append( item39, "Strumenti" )
    
    item52 = wx.Menu()
    item52.Append( ID_ABOUT, "Informazioni sulla versione\tCtrl-?", "" )
    item52.Append( ID_UPDATES, "Verifica disponibilità aggiornamenti", "" )
    item0.Append( item52, "?" )
    
    return item0

ID_INTMAGSRCDES = 5013
ID_HELP = 10255

def XLiteMenuBar():
    item0 = wx.MenuBar()
    
    item1 = wx.Menu()
    item1.Append( ID_QUIT, "Esci", "Chiude la sessione di lavoro" )
    item0.Append( item1, "File" )
    
    item2 = wx.Menu()
    
    item3 = wx.Menu()
    item3.Append( ID_GESCLIENT, "Clienti", "Gestione tabella Clienti" )
    item3.Append( ID_GESCASSE, "Casse", "Gestione tabella Sottoconti di tipo Cassa" )
    item3.Append( ID_GESBANCHE, "Banche", "Gestione tabella Sottoconti di tipo Banca" )
    item3.AppendSeparator()
    item3.Append( ID_GESALQIVA, "Aliquote IVA", "Gestione tabella Aliquote IVA" )
    item2.AppendMenu( ID_MENUTABGLOBAL, "Anagrafiche", item3 )

    
    item4 = wx.Menu()
    item4.Append( ID_GESPROD, "Prodotti", "Gestione tabella Articoli di Magazzino" )
    item4.AppendSeparator()
    item4.Append( ID_GESPROD_TIPART, "Tipi Prodotto", "Gestione tabella Tipi prodotto" )
    item4.Append( ID_GESPROD_CATART, "Categorie", "Gestione tabella Categorie merce" )
    item4.Append( ID_GESPROD_GRUART, "Gruppi", "Gestione tabella Gruppi merce" )
    item4.Append( ID_GESPROD_MARART, "Marche prodotti", "Gestione tabella Gruppi merce" )
    item4.Append( ID_GESPROD_STATUS, "Status prodotti", "Gestione tabella Status prodotti" )
    item4.AppendSeparator()
    
    item5 = wx.Menu()
    item5.Append( ID_GESTRACAU, "Causali", "Gestione tabella Causali di trasporto" )
    item5.Append( ID_GESTRACUR, "A cura", "Gestione tabella Trasporto a cura" )
    item5.Append( ID_GESTRAPOR, "Porto", "Gestione tabella Tipo di porto" )
    item5.Append( ID_GESTRAVET, "Vettori", "Gestione tabella Vettori di consegna" )
    item5.Append( ID_GESTRAASP, "Aspetto esteriore dei beni", "Gestione tabella Aspetto esteriore dei beni" )
    item5.Append( ID_GESTRACON, "Tipi di incasso dei contrassegni", "Gestione tabella Tipi di incasso dei contrassegni" )
    item4.AppendMenu( ID_MENUTRASP, "Dati trasporto", item5 )

    item2.AppendMenu( ID_MENUTABMAGAZZ, "Magazzino", item4 )

    
    item6 = wx.Menu()
    item6.Append( ID_GESMODPAG, "ModalitÃ  di pagamento", "Gestione tabella ModalitÃ  di pagamento" )
    item6.Append( ID_GESTSPEINC, "Spese di incasso", "Gestione tabella Spese di incasso su effetti" )
    item2.AppendMenu( ID_MENUTABSCAD, "Scadenzari Clienti/Fornitori", item6 )

    item0.Append( item2, "Tabelle" )
    
    item7 = wx.Menu()
    item7.Append( ID_CONTABGES_INCPAG, "Registrazione Incassi", "Inserimento registrazioni di tipo Incasso/Pagamento" )
    
    item8 = wx.Menu()
    
    item9 = wx.Menu()
    item9.Append( ID_INTCONCLI, "Clienti", "Interrogazione Mastri Clienti con dati anagrafici completi" )
    item9.Append( ID_INTCONCAS, "Casse", "Interrogazione Mastri Sottoconti Cassa con dati anagrafici completi" )
    item9.Append( ID_INTCONBAN, "Banche", "Interrogazione Mastri Sottoconti Banca con dati anagrafici completi" )
    item8.AppendMenu( ID_INTCONTAB, "Mastri", item9 )

    item8.Append( ID_INTREGCON, "Registrazioni contabili", "Interrogazione registrazioni contabili" )
    item8.Append( ID_INTREGIVA, "Registrazioni IVA", "Interrogazione registrazioni IVA" )
    item8.Append( ID_INTALIQIVA, "Utilizzo Aliquote IVA", "Interrogazione Aliquote IVA" )
    item8.Append( ID_VENDAZIPRIV, "Sintesi vendite privati/aziende", "Analizza le vendite di un periodo e ne evidenzia imponibile ed imposta per anagrafica" )
    item7.AppendMenu( ID_MENUCONTINT, "Interroga", item8 )

    item0.Append( item7, "ContabilitÃ " )
    
    item10 = wx.Menu()
    item10.Append( ID_MAGAZZINS, "Immissione documenti", "Inserimento documenti di magazzino" )
    
    item11 = wx.Menu()
    item11.Append( ID_INTPROD, "Prodotto", "Interrogazione scheda e mastro prodotto" )
    item11.Append( ID_INTDOCMAG, "Documenti", "Interrogazione documenti" )
    item11.Append( ID_INTMOVMAG, "Movimenti", "Interrogazione movimenti" )
    item11.AppendSeparator()
    
    item12 = wx.Menu()
    item12.Append( ID_INTMAGCLI, "Clienti", "Interrogazione scheda e dati di magazzino dei clienti" )
    item12.Append( ID_INTMAGSRCDES, "Ricerca destinazioni merce", "Ricerca clienti da destinazione merce" )
    item11.AppendMenu( ID_MENU, "Anagrafiche", item12 )

    item11.AppendSeparator()
    
    item13 = wx.Menu()
    item13.Append( ID_STATFATCLI, "Fatturato Clienti", "Statistica sul fatturato clienti" )
    item13.Append( ID_STATFATCLICAT, "Fatturato Clienti per Categoria prodotto", "Statistica sul fatturato clienti per categoria merce" )
    item13.AppendSeparator()
    item13.Append( ID_STATFATPRO, "Fatturato Prodotti", "Statistica sul fatturato prodotti" )
    item13.Append( ID_STATFATPROCLI, "Fatturato Prodotti per Cliente", "Statistica sul fatturato prodotti per cliente" )
    item13.AppendSeparator()
    item13.Append( ID_STATFATCATART, "Fatturato Categorie prodotto", "Statistica sul fatturato per categoria prodotto" )
    item13.Append( ID_PDCSINTART, "Schede clienti con sintesi vendite prodotti", "" )
    item11.AppendMenu( ID_MENU, "Statistiche", item13 )

    item10.AppendMenu( ID_MENU, "Interroga", item11 )

    item0.Append( item10, "Magazzino" )
    
    item14 = wx.Menu()
    item14.Append( ID_SCADINS, "Inserisci nuova scadenza", "" )
    item14.Append( ID_INTPCFCLI, "Situazione del Cliente", "Interrogazione Scadenzario Clienti con dati anagrafici completi" )
    item14.Append( ID_SCAD_SCAD, "Scadenzario dei Clienti", "Interrogazione Scadenzari Clienti/Fornitori" )
    item0.Append( item14, "Scadenzari" )
    
    item15 = wx.Menu()
    
    item16 = wx.Menu()
    item16.Append( ID_CFGAZIENDA, "Setup Azienda", "Imposta i dati aziendali e le caratteristiche di base della sua gestione" )
    item16.Append( ID_CFGWKS, "Setup Workstation", "Impostazione caratteristiche del posto di lavoro" )
    item16.AppendSeparator()
    item16.Append( ID_CFGLICENSE, "Licenza d'uso", "Imposta il tipo di licenza d'so del programma" )
    item16.Append( ID_CFGEMAIL, "Setup Posta elettronica", "Imposta i parametri occorrenti alla spedizione di messaggi email" )
    item16.Append( ID_CFGDOCSEMAIL, "Setup invio documenti per posta elettronica", "Imposta i parametri occorrenti alla spedizione di documenti via email" )
    item15.AppendMenu( ID_MENUSETUP, "Setup", item16 )

    item0.Append( item15, "Strumenti" )
    
    item17 = wx.Menu()
    item17.Append( ID_HELP, "Help - Manuale utente", "Richiama il manuale utente" )
    item17.Append( ID_ABOUT, "Informazioni sulla versione", "" )
    item17.Append( ID_UPDATES, "Verifica disponibilitÃ  aggiornamenti", "" )
    item0.Append( item17, "?" )
    
    return item0

# Toolbar functions

# Bitmap functions


# End of generated file
