# -*- coding: UTF-8 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: aliqiva.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid
import wx.animate

# Custom source
from awc.controls.radiobox import RadioBox
from awc.controls.numctrl import NumCtrl
from awc.controls.textctrl import TextCtrl, TextCtrl_LC
from awc.controls.linktable import LinkTable
from Env import Azienda
bt = Azienda.BaseTab

from anag.basetab import AnagCardPanel, WorkZoneNotebook, UnoZeroCheckBox


class ModoIvaRadioBox(RadioBox):

    def __init__(self, *args, **kwargs):
        RadioBox.__init__(self, *args, **kwargs)
        self.SetDataLink(values=["I", "N", "E", "F"])




# Window functions

ID_ANAGMAIN = 16000
ID_DATIALLEG = 16001

def AliqIvaCardFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = AnagCardPanel(parent)
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item3 = WorkZoneNotebook( parent, ID_DATIALLEG, wx.DefaultPosition, [200,160], 0 )
    item2 = item3
    
    item4 = wx.Panel( item3, -1 )
    AliqIvaCardDatiFunc(item4, False)
    item3.AddPage( item4, "Dati" )

    item5 = wx.Panel( item3, -1 )
    AliqIvaCardAllegFunc(item5, False)
    item3.AddPage( item5, "Allegati" )

    item6 = wx.Panel( item3, -1 )
    AliqIvaCardNaturaFunc(item6, False)
    item3.AddPage( item6, "Natura" )

    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_TEXT = 16002
ID_PERCIVA = 16003
ID_PERCIND = 16004
ID_CTRALIQIVA = 16005
ID_TIPO = 16006
ID_MODO = 16007
ID_SM11_NO = 16008
ID_CHECKBOX = 16009

def AliqIvaCardDatiFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item2 = wx.StaticBox( parent, -1, "Percentuali di calcolo" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    
    item3 = wx.FlexGridSizer( 0, 6, 0, 0 )
    
    item4 = wx.StaticText( parent, ID_TEXT, "Aliquota %:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item4, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item5 = NumCtrl( parent, integerWidth=3, fractionWidth=2, allowNegative=False, groupDigits=False); item5.SetName("perciva")
    item3.Add( item5, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item6 = wx.StaticText( parent, ID_TEXT, "Indeducibilità %:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item6, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item7 = NumCtrl( parent, integerWidth=3, fractionWidth=2, allowNegative=False, groupDigits=False); item7.SetName("percind")
    item3.Add( item7, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item8 = wx.StaticText( parent, ID_TEXT, "Codice Split Payment corrispondente:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item8, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item9 = LinkTable(parent, ID_CTRALIQIVA ); item9.SetDataLink( bt.TABNAME_ALIQIVA, "id_split")
    item3.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item3.AddGrowableCol( 5 )

    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item10 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item11 = RadioBox( parent, ID_TIPO, "Tipologia", wx.DefaultPosition, wx.DefaultSize, 
        ["Acquisti/Vendite","Acquisti CEE","Vendite in split payment","Deducibilità differita"] , 1, wx.RA_SPECIFY_COLS )
    item11.SetName( "tipo" )
    item10.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item12 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item13 = ModoIvaRadioBox( parent, ID_MODO, "L'importo assogettato a questa aliquota è:", wx.DefaultPosition, wx.DefaultSize, 
        ["Imponibile","Non Imponibile","Esente","Fuori Campo"] , 1, wx.RA_SPECIFY_COLS )
    item13.SetName( "modo" )
    item12.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item15 = wx.StaticBox( parent, -1, "Spesometro 2011" )
    item14 = wx.StaticBoxSizer( item15, wx.VERTICAL )
    
    item16 = UnoZeroCheckBox( parent, ID_SM11_NO, "Escludi dalla compilazione dello spesometro", wx.DefaultPosition, wx.DefaultSize, 0 )
    item16.SetName( "sm11_no" )
    item14.Add( item16, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item12.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item18 = wx.StaticBox( parent, -1, "Totalizzatori per Comunicazioni Liquidazioni Iva" )
    item17 = wx.StaticBoxSizer( item18, wx.VERTICAL )
    
    item19 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item20 = UnoZeroCheckBox( parent, ID_CHECKBOX, "Escludi da Operazioni Attive", wx.DefaultPosition, wx.DefaultSize, 0 )
    item20.SetName( "notot_liquatt" )
    item19.Add( item20, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item21 = UnoZeroCheckBox( parent, ID_CHECKBOX, "Escludi da Operazioni Passive", wx.DefaultPosition, wx.DefaultSize, 0 )
    item21.SetName( "notot_liqupas" )
    item19.Add( item21, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item17.Add( item19, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item12.Add( item17, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item12.AddGrowableCol( 0 )

    item10.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item10.AddGrowableCol( 0 )

    item10.AddGrowableCol( 1 )

    item0.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_RADIOBOX = 16010

def AliqIvaCardAllegFunc( parent, call_fit = True, set_sizer = True ):
    item1 = wx.StaticBox( parent, -1, "Progressivi allegati clienti/fornitori" )
    item0 = wx.StaticBoxSizer( item1, wx.VERTICAL )
    
    item2 = wx.FlexGridSizer( 0, 5, 0, 0 )
    
    item3 = wx.StaticText( parent, ID_TEXT, "Clienti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.Add( item3, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item4 = RadioBox( parent, ID_RADIOBOX, "Colonna 1", wx.DefaultPosition, wx.DefaultSize, 
        ["Nulla","Imponibile","Imposta"] , 1, wx.RA_SPECIFY_COLS )
    item4.SetName( "pralcc1" )
    item2.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item5 = RadioBox( parent, ID_RADIOBOX, "Colonna 2", wx.DefaultPosition, wx.DefaultSize, 
        ["Nulla","Imponibile","Imposta"] , 1, wx.RA_SPECIFY_COLS )
    item5.SetName( "pralcc2" )
    item2.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item6 = RadioBox( parent, ID_RADIOBOX, "Colonna 3", wx.DefaultPosition, wx.DefaultSize, 
        ["Nulla","Imponibile","Imposta"] , 1, wx.RA_SPECIFY_COLS )
    item6.SetName( "pralcc3" )
    item2.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item7 = RadioBox( parent, ID_RADIOBOX, "Colonna 4", wx.DefaultPosition, wx.DefaultSize, 
        ["Nulla","Imponibile","Imposta"] , 1, wx.RA_SPECIFY_COLS )
    item7.SetName( "pralcc4" )
    item2.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item8 = wx.StaticText( parent, ID_TEXT, "Fornitori", wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.Add( item8, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item9 = RadioBox( parent, ID_RADIOBOX, "Colonna 1", wx.DefaultPosition, wx.DefaultSize, 
        ["Nulla","Imponibile","Imposta"] , 1, wx.RA_SPECIFY_COLS )
    item9.SetName( "pralfc1" )
    item2.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item10 = RadioBox( parent, ID_RADIOBOX, "Colonna 2", wx.DefaultPosition, wx.DefaultSize, 
        ["Nulla","Imponibile","Imposta"] , 1, wx.RA_SPECIFY_COLS )
    item10.SetName( "pralfc2" )
    item2.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item11 = RadioBox( parent, ID_RADIOBOX, "Colonna 3", wx.DefaultPosition, wx.DefaultSize, 
        ["Nulla","Imponibile","Imposta"] , 1, wx.RA_SPECIFY_COLS )
    item11.SetName( "pralfc3" )
    item2.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item12 = RadioBox( parent, ID_RADIOBOX, "Colonna 4", wx.DefaultPosition, wx.DefaultSize, 
        ["Nulla","Imponibile","Imposta"] , 1, wx.RA_SPECIFY_COLS )
    item12.SetName( "pralfc4" )
    item2.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item2.AddGrowableCol( 1 )

    item2.AddGrowableCol( 2 )

    item2.AddGrowableCol( 3 )

    item2.AddGrowableCol( 4 )

    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_TEXTCTRL = 16011

def AliqIvaCardNaturaFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item1 = RadioBox( parent, ID_RADIOBOX, "Natura", wx.DefaultPosition, wx.DefaultSize, 
        ["-","N1 - Escluso ex Art.15","N2 - Non soggetto","N2.1 - non soggette(artt. da 7 a 7-septies)","N2.2 - non soggette - altri casi","N3 - Non imponibile","N3.1 - non imponibili - esportazioni","N3.2 - non imponibili - cessioni intracomunitarie","N3.3 - non imponibili - cessioni verso San Marino","N3.4 - non imponibili - operaz.assimilate a esportazione","N3.5 - non imponibili - a seguito di dich. d'intento","N3.6 - non imponibili - altre operazioni no plafond","N4 - Esente","N5 - Regime del margine","N6 - Inversione contabile (reverse chanrge)","N6.1 - inversione contabile - cessione rottami ecc.","N6.2 - inversione contabile - cessione di oro/argento","N6.3 - inversione contabile - subappalto edile","N6.4 - inversione contabile - cessione di fabbricati","N6.5 - inversione contabile - cessione cellulari","N6.6 - inversione contabile - cessione prod.elettronici","N6.7 - inversione contabile - prestazioni edili ecc.","N6.8 - inversione contabile - operazioni sett.energetico","N6.9 - inversione contabile - altri casi","N7 - IVA assolta in altro stato UE"] , 2, wx.RA_SPECIFY_COLS )
    item1.SetName( "ftel_natura" )
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item2 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item3 = wx.StaticText( parent, ID_TEXT, "Riferimento normativo", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.SetForegroundColour( wx.BLUE )
    item2.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item4 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [400,40], wx.TE_MULTILINE )
    item4.SetName( "ftel_rifnorm" )
    item2.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item2.AddGrowableCol( 0 )

    item2.AddGrowableRow( 1 )

    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 1 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
