# -*- coding: iso-8859-15 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: pdctip.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid

# Custom source
from awc.controls.radiobox import RadioBox
from awc.controls.linktable import LinkTable

from anag.basetab import AnagCardPanel

import Env
bt = Env.Azienda.BaseTab



# Window functions

ID_ANAGMAIN = 16000
ID_RADIOTIPO = 16001
ID_CTRPDCRANGE = 16002

def PdcTipCardFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item0.AddGrowableCol( 0 )
    
    item1 = AnagCardPanel(parent)
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item2 = RadioBox( parent, ID_RADIOTIPO, "I sottoconti di questo tipo sono:", wx.DefaultPosition, wx.DefaultSize, 
        ["Cassa","Banche","Clienti","Fornitori","Effetti","Altro"] , 1, wx.RA_SPECIFY_ROWS )
    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item4 = wx.StaticBox( parent, -1, "Range codici sottoconti" )
    item3 = wx.StaticBoxSizer( item4, wx.VERTICAL )
    
    item5 = LinkTable(parent, ID_CTRPDCRANGE ); item5.SetDataLink( bt.TABNAME_PDCRANGE, "id_pdcrange", None )
    item3.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.Add( [ 20, 100 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
