# -*- coding: iso-8859-15 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: statcli.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid

# Custom source
from anag.basetab import AnagCardPanel

from awc.controls.checkbox import CheckBox
from awc.controls.linktable import LinkTable
from awc.controls.attachbutton import AttachmentButton

from Env import Azienda
bt = Azienda.BaseTab

class UnoZeroCheckBox(CheckBox):

    def __init__(self, *args, **kwargs):
        CheckBox.__init__(self, *args, **kwargs)
        self.SetDataLink(values=(1,0))



# Window functions

ID_ANAGMAIN = 16000
ID_HIDESEARCH = 16001
ID_NOMOV_ORDCLI = 16002
ID_NOMOV_VENCLI = 16003
ID_NOMOV_RESCLI = 16004
ID_LINE = 16005
ID_NOEFFETTI = 16006

def StatCliCardFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item0.AddGrowableCol( 0 )
    
    item1 = AnagCardPanel(parent)
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item3 = wx.StaticBox( parent, -1, "Ricerca clienti" )
    item2 = wx.StaticBoxSizer( item3, wx.VERTICAL )
    
    item4 = UnoZeroCheckBox( parent, ID_HIDESEARCH, "Nascondi nelle ricerche i clienti con questo status", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.SetName( "hidesearch" )
    item2.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item6 = wx.StaticBox( parent, -1, "Non consentire l'uso dei clienti con questo stato:" )
    item5 = wx.StaticBoxSizer( item6, wx.VERTICAL )
    
    item7 = UnoZeroCheckBox( parent, ID_NOMOV_ORDCLI, "Nei documenti di tipo ordine", wx.DefaultPosition, wx.DefaultSize, 0 )
    item7.SetName( "nomov_ordcli" )
    item5.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item8 = UnoZeroCheckBox( parent, ID_NOMOV_VENCLI, "Nei documenti di vendita", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.SetName( "nomov_vencli" )
    item5.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item9 = UnoZeroCheckBox( parent, ID_NOMOV_RESCLI, "Nei documenti di reso", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.SetName( "nomov_rescli" )
    item5.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item10 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item5.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item11 = UnoZeroCheckBox( parent, ID_NOEFFETTI, "Con mod. pagamento di tipo effetto", wx.DefaultPosition, wx.DefaultSize, 0 )
    item11.SetName( "noeffetti" )
    item5.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.Add( [ 20, 120 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
