# -*- coding: UTF-8 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: ripara.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid
import wx.animate

# Custom source
from awc.controls.linktable import LinkTable
from awc.controls.textctrl import TextCtrl
from awc.controls.datectrl import DateCtrl
from awc.controls.numctrl import NumCtrl
from awc.controls.checkbox import CheckBox, RCheckBox
from awc.controls.radiobox import RadioBox

import anag.lib as alib

from Env import Azienda
bt = Azienda.BaseTab



# Window functions

ID_TEXT = 10000
ID_TEXTCTRL = 10001
ID_BTNABORT = 10002
ID_BTNCHANGE = 10003

def RiparaFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item2 = wx.StaticText( parent, ID_TEXT, "Riparazione Tabella del database", wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.SetName( "labelTitolo" )
    item1.Add( item2, 0, wx.GROW|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item3 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [800,500], wx.TE_MULTILINE )
    item3.SetFont( wx.Font( 12, wx.MODERN, wx.NORMAL, wx.NORMAL ) )
    item3.SetName( "stato" )
    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item1.AddGrowableCol( 0 )

    item1.AddGrowableRow( 0 )

    item0.Add( item1, 0, wx.GROW, 5 )

    item4 = wx.FlexGridSizer( 0, 3, 0, 0 )
    
    item4.Add( [ 250, 20 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item5 = wx.Button( parent, ID_BTNABORT, "Abbandona", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.SetName( "btnAbort" )
    item4.Add( item5, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item6 = wx.Button( parent, ID_BTNCHANGE, "Ripara", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.SetName( "btnRipara" )
    item4.Add( item6, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item4, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
