# -*- coding: iso-8859-15 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: util.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid

# Custom source
import awc.controls.images as images

class WIPTitlePanel(wx.Panel):
    def __init__(self, parent, id):
        wx.Panel.__init__(self, parent, id)
        self.SetBackgroundColour('white')
        WIPTitlePanelFunc(self)



# Window functions

ID_FOREIGN = 10000
ID_MESSAGE = 10001
ID_PROGRESS = 10002
ID_MESSAGE2 = 10003
ID_PROGRESS2 = 10004
ID_BTNBREAK = 10005

def WorkInProgressFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item0.AddGrowableCol( 0 )
    item0.AddGrowableRow( 2 )
    
    item1 = WIPTitlePanel(parent, ID_FOREIGN)
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( [ 20, 10 ] , 0, wx.ALIGN_CENTER, 5 )

    item2 = wx.FlexGridSizer( 1, 0, 0, 0 )
    item2.AddGrowableCol( 1 )
    
    item2.Add( [ 20, 40 ] , 0, wx.ALIGN_CENTER, 5 )

    item3 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item3.AddGrowableCol( 0 )
    
    item4 = wx.StaticText( parent, ID_MESSAGE, "Elaborazione dati in corso.", wx.DefaultPosition, [280,-1], 0 )
    item4.SetName( "message" )
    item3.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item5 = wx.Gauge( parent, ID_PROGRESS, 100, wx.DefaultPosition, [280,15], 0 )
    item5.SetName( "progress" )
    item3.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item6 = wx.StaticText( parent, ID_MESSAGE2, "Elaborazione dati in corso.", wx.DefaultPosition, [280,-1], 0 )
    item6.SetName( "message2" )
    item3.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item7 = wx.Gauge( parent, ID_PROGRESS2, 100, wx.DefaultPosition, [280,15], 0 )
    item7.SetName( "progress2" )
    item3.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item2.Add( item3, 0, wx.ALIGN_CENTER, 5 )

    item2.Add( [ 20, 40 ] , 0, wx.ALIGN_CENTER, 5 )

    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item8 = wx.Button( parent, ID_BTNBREAK, "Interrompi", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item8, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_ICONWAIT = 10006
ID_TITLE = 10007

def WIPTitlePanelFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item0.AddGrowableCol( 0 )
    
    item0.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER, 5 )

    item1 = wx.BoxSizer( wx.HORIZONTAL )
    
    item1.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER, 5 )

    item2 = wx.StaticBitmap(parent, ID_ICONWAIT, images.getWait32Bitmap())
    item1.Add( item2, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item3 = wx.StaticText( parent, ID_TITLE, "Attendere prego...", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.SetFont( wx.Font( 12, wx.DEFAULT, wx.NORMAL, wx.BOLD ) )
    item1.Add( item3, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item1, 0, 0, 5 )

    item0.Add( [ 20, 10 ] , 0, wx.ALIGN_CENTER, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
