# -*- coding: UTF-8 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: listini.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid
import wx.animate

# Custom source
from wx import Panel as wxPanel

from awc.controls.linktable import LinkTable
from awc.controls.datectrl import DateCtrl
from awc.controls.textctrl import TextCtrl
from awc.controls.numctrl import NumCtrl
from awc.controls.checkbox import CheckBox, RCheckBox
from awc.controls.radiobox import RadioBox

from anag.lib import LinkTableTipArt, LinkTableCatArt, LinkTableGruArt, LinkTableFornit, LinkTableMarArt, LinkTableStatArt, LinkTableCliFor, LinkTableGruPrez, LinkTableCliente, LinkTableAgente

from Env import Azienda
bt = Azienda.BaseTab

class SintesiPanel(wx.Panel):
    def __init__(self, *args, **kwargs):
        wx.Panel.__init__(self, *args, **kwargs)
        SintesiPanelFunc(self)

PREZZOWIDTH = 90

class ListinoPanel(wx.Panel):
    def __init__(self, id, parent, pos, size, style):
        size = (500+PREZZOWIDTH*bt.MAGNUMLIS, size[1])
        wx.Panel.__init__(self, id, parent, pos, size, style)

class VariaListPanel(wx.Panel):
    def __init__(self, *args, **kwargs):
        wx.Panel.__init__(self, *args, **kwargs)
        VariaListFunc(self)

class TipAggListRadioBox(RadioBox):
    def __init__(self, *args, **kwargs):
        RadioBox.__init__(self, *args, **kwargs)
        self.SetDataLink('tvlist', 'NRV')

SelDataPanel = None

class ListiniAttualiSelDataPanel(wx.Panel):
    def __init__(self, *args, **kwargs):
        wx.Panel.__init__(self, *args, **kwargs)
        ListiniAttualiSelDataFunc(self)

class GrigliaPrezziiAttualiSelDataPanel(wx.Panel):
    def __init__(self, *args, **kwargs):
        wx.Panel.__init__(self, *args, **kwargs)
        GrigliaPrezziAttualiSelDataFunc(self)


class OrdinamentoRadioBox(RadioBox):

    def __init__(self, *args, **kwargs):
        RadioBox.__init__(self, *args, **kwargs)
        self.SetDataLink(values="CDF")
        #if not bt.MAGFORLIS:
            #self.ShowItem(2, False)

class RaggruppamentoRadioBox(RadioBox):

    def __init__(self, *args, **kwargs):
        RadioBox.__init__(self, *args, **kwargs)
        self.SetDataLink(values="NCG")


class ValutaCostiPrezziBasePanel(wx.Panel):
    def __init__(self, *args, **kwargs):
        wx.Panel.__init__(self, *args, **kwargs)
        ValutaCostiPrezziBaseFunc(self)


class ValutaPrezziClientiPanel(wx.Panel):
    def __init__(self, *args, **kwargs):
        wx.Panel.__init__(self, *args, **kwargs)
        ValutaPrezziClientiFunc(self)


class ValutaCostiFornitoriPanel(wx.Panel):
    def __init__(self, *args, **kwargs):
        wx.Panel.__init__(self, *args, **kwargs)
        ValutaCostiFornitoriFunc(self)




# Window functions

ID_TEXT = 14000
ID_LINE = 14001
ID_CODICE1 = 14002
ID_CODICE2 = 14003
ID_DESCRIZ1 = 14004
ID_DESCRIZ2 = 14005
ID_FILT_TIPART = 14006
ID_FILT_CATART = 14007
ID_FILT_GRUART = 14008
ID_FILT_FORNIT1 = 14009
ID_FILT_FORNIT2 = 14010
ID_FILT_STATUS1 = 14011
ID_FILT_STATUS2 = 14012
ID_AUTORICALC = 14013
ID_AUTOLISTINO = 14014
ID_ORDINAM = 14015
ID_RAGGRUPPAM = 14016
ID_ESCL0COS = 14017
ID_ESCL0PRE = 14018
ID_SSV = 14019
ID_PANSINT = 14020
ID_UPDATE = 14021
ID_SOLOLIST = 0
ID_PANGRIDLIS = 14022
ID_RICALCPC = 14023
ID_RICALCALL = 14024
ID_RICALCLIST = 14025
ID_VARIAPERC = 14026
ID_ACQLIST = 14027
ID_PRINTLIS = 14028
ID_SAVELIST = 14029

def ListiniFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item2 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item3 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item4 = wx.StaticText( parent, ID_TEXT, "Selezione prodotti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.SetForegroundColour( wx.BLUE )
    item3.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item5 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item3.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item6 = wx.FlexGridSizer( 0, 3, 0, 0 )
    
    item7 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item7, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item8 = wx.StaticText( parent, ID_TEXT, "Da:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP, 5 )

    item9 = wx.StaticText( parent, ID_TEXT, "A:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item10 = wx.StaticText( parent, ID_TEXT, "Codice:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item6.Add( item10, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item11 = TextCtrl( parent, ID_CODICE1, "", wx.DefaultPosition, [120,-1], 0 )
    item11.SetName( "codice1" )
    item6.Add( item11, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item12 = TextCtrl( parent, ID_CODICE2, "", wx.DefaultPosition, [120,-1], 0 )
    item12.SetName( "codice2" )
    item6.Add( item12, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item13 = wx.StaticText( parent, ID_TEXT, "Descrizione:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item6.Add( item13, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item14 = TextCtrl( parent, ID_DESCRIZ1, "", wx.DefaultPosition, [80,-1], 0 )
    item14.SetName( "descriz1" )
    item6.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item15 = TextCtrl( parent, ID_DESCRIZ2, "", wx.DefaultPosition, [80,-1], 0 )
    item15.SetName( "descriz2" )
    item6.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item16 = wx.StaticText( parent, ID_TEXT, "Tipo:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item6.Add( item16, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item17 = LinkTableTipArt(parent, ID_FILT_TIPART, 'id_tipart1')
    item6.Add( item17, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item18 = LinkTableTipArt(parent, ID_FILT_TIPART, 'id_tipart2')
    item6.Add( item18, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item19 = wx.StaticText( parent, ID_TEXT, "Categoria:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item6.Add( item19, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item20 = LinkTableCatArt(parent, ID_FILT_CATART, 'id_catart1')
    item6.Add( item20, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item21 = LinkTableCatArt(parent, ID_FILT_CATART, 'id_catart2')
    item6.Add( item21, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item22 = wx.StaticText( parent, ID_TEXT, "Gruppo:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item6.Add( item22, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item23 = LinkTableGruArt(parent, ID_FILT_GRUART, 'id_gruart1')
    item6.Add( item23, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item24 = LinkTableGruArt(parent, ID_FILT_GRUART, 'id_gruart2')
    item6.Add( item24, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item25 = wx.StaticText( parent, ID_TEXT, "Fornitore:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item6.Add( item25, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item26 = LinkTableFornit(parent, ID_FILT_FORNIT1, 'id_fornit1')
    item6.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item27 = LinkTableFornit(parent, ID_FILT_FORNIT2, 'id_fornit2')
    item6.Add( item27, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item28 = wx.StaticText( parent, ID_TEXT, "Status:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item6.Add( item28, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item29 = LinkTableStatArt(parent, ID_FILT_STATUS1, 'id_status1')
    item6.Add( item29, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item30 = LinkTableStatArt(parent, ID_FILT_STATUS2, 'id_status2')
    item6.Add( item30, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item6.AddGrowableCol( 1 )

    item6.AddGrowableCol( 2 )

    item3.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item31 = wx.BoxSizer( wx.HORIZONTAL )
    
    item32 = wx.StaticText( parent, ID_TEXT, "Ricalcola automaticamente:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item31.Add( item32, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item33 = wx.CheckBox( parent, ID_AUTORICALC, "Costo/Prezzo", wx.DefaultPosition, wx.DefaultSize, 0 )
    item31.Add( item33, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item34 = wx.CheckBox( parent, ID_AUTOLISTINO, "Prezzi listino", wx.DefaultPosition, wx.DefaultSize, 0 )
    item34.SetName( "autolistino" )
    item31.Add( item34, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item3.Add( item31, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item3.AddGrowableCol( 0 )

    item2.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item35 = wx.BoxSizer( wx.VERTICAL )
    
    item36 = OrdinamentoRadioBox( parent, ID_ORDINAM, "Ordinamento", wx.DefaultPosition, wx.DefaultSize, 
        ["Codice","Descrizione","Cod.Fornitore"] , 1, wx.RA_SPECIFY_COLS )
    item36.SetName( "ordinam" )
    item35.Add( item36, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item37 = RaggruppamentoRadioBox( parent, ID_RAGGRUPPAM, "Raggruppamento", wx.DefaultPosition, wx.DefaultSize, 
        ["Nessuno","Categoria","Categoria, gruppo"] , 1, wx.RA_SPECIFY_COLS )
    item37.SetName( "raggruppam" )
    item35.Add( item37, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item39 = wx.StaticBox( parent, -1, "Escludi se è nullo:" )
    item38 = wx.StaticBoxSizer( item39, wx.HORIZONTAL )
    
    item40 = wx.CheckBox( parent, ID_ESCL0COS, "Il costo", wx.DefaultPosition, wx.DefaultSize, 0 )
    item40.SetName( "excl0cos" )
    item38.Add( item40, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item41 = wx.CheckBox( parent, ID_ESCL0PRE, "Il prezzo", wx.DefaultPosition, wx.DefaultSize, 0 )
    item41.SetName( "excl0pre" )
    item38.Add( item41, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item35.Add( item38, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item42 = wx.CheckBox( parent, ID_SSV, "Solo Status Visibile", wx.DefaultPosition, wx.DefaultSize, 0 )
    item42.SetValue( True )
    item42.SetName( "ssv" )
    item35.Add( item42, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item2.Add( item35, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item43 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [-1,20], wx.LI_VERTICAL )
    item2.Add( item43, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item44 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item45 = SintesiPanel(parent, ID_PANSINT)
    item44.Add( item45, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item46 = wx.Button( parent, ID_UPDATE, "&Aggiorna", wx.DefaultPosition, wx.DefaultSize, 0 )
    item46.SetToolTip( wx.ToolTip("Aggiorna la griglia dei prodotti") )
    item46.SetName( "update" )
    item44.Add( item46, 0, wx.ALIGN_RIGHT|wx.ALIGN_BOTTOM|wx.ALL, 5 )

    item44.AddGrowableCol( 0 )

    item44.AddGrowableRow( 1 )

    item44.AddGrowableRow( 2 )

    item2.Add( item44, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item2.AddGrowableCol( 0 )

    item2.AddGrowableRow( 0 )

    item1.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item1.AddGrowableCol( 0 )

    item1.AddGrowableRow( 0 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item47 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item48 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item49 = wx.StaticText( parent, ID_TEXT, "Prezzi di listino", wx.DefaultPosition, wx.DefaultSize, 0 )
    item49.SetForegroundColour( wx.BLUE )
    item48.Add( item49, 0, wx.GROW|wx.ALIGN_BOTTOM|wx.LEFT, 5 )

    item50 = RCheckBox( parent, ID_SOLOLIST, "Mostra solo prodotti presenti nei listini", wx.DefaultPosition, wx.DefaultSize, 0 )
    item50.SetName( "sololist" )
    item48.Add( item50, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item48.AddGrowableCol( 0 )

    item47.Add( item48, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item51 = ListinoPanel( parent, ID_PANGRIDLIS, wx.DefaultPosition, [-1,400], wx.SUNKEN_BORDER )
    item47.Add( item51, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item47.AddGrowableCol( 0 )

    item47.AddGrowableRow( 1 )

    item0.Add( item47, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item52 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item54 = wx.StaticBox( parent, -1, "Ricalcoli da effettuare sui prodotti selezionati" )
    item53 = wx.StaticBoxSizer( item54, wx.HORIZONTAL )
    
    item55 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item56 = wx.StaticText( parent, ID_TEXT, "Ricalcola:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item55.Add( item56, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item57 = wx.Button( parent, ID_RICALCPC, "&1: Costo/prezzo", wx.DefaultPosition, wx.DefaultSize, 0 )
    item57.SetToolTip( wx.ToolTip("Ricalcola il costo/prezzo dei prodotti selezionati") )
    item55.Add( item57, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item58 = wx.Button( parent, ID_RICALCALL, "&2: Costo/prezzo e Listini", wx.DefaultPosition, wx.DefaultSize, 0 )
    item58.SetToolTip( wx.ToolTip("Ricalcola il costo/prezzo e i prezzi di listino dei prodotti selezionati") )
    item55.Add( item58, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item59 = wx.Button( parent, ID_RICALCLIST, "&3: Listini", wx.DefaultPosition, wx.DefaultSize, 0 )
    item59.SetToolTip( wx.ToolTip("Ricalcola i prezzi di listino dei prodotti selezionati") )
    item55.Add( item59, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item60 = wx.Button( parent, ID_VARIAPERC, "&Variazioni %", wx.DefaultPosition, wx.DefaultSize, 0 )
    item60.SetToolTip( wx.ToolTip("Applica variazioni percentuali al costo, al prezzo e ai prezzi di listino") )
    item55.Add( item60, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item55.AddGrowableCol( 4 )

    item53.Add( item55, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item52.Add( item53, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item62 = wx.StaticBox( parent, -1, "Acquisizione" )
    item61 = wx.StaticBoxSizer( item62, wx.VERTICAL )
    
    item63 = wx.Button( parent, ID_ACQLIST, "CSV Fornitore", wx.DefaultPosition, wx.DefaultSize, 0 )
    item61.Add( item63, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 5 )

    item52.Add( item61, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item65 = wx.StaticBox( parent, -1, "Salva dati" )
    item64 = wx.StaticBoxSizer( item65, wx.VERTICAL )
    
    item66 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item67 = wx.Button( parent, ID_PRINTLIS, "Stam&pa", wx.DefaultPosition, wx.DefaultSize, 0 )
    item67.SetToolTip( wx.ToolTip("Stampa listino") )
    item66.Add( item67, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item68 = wx.Button( parent, ID_SAVELIST, "&Salva", wx.DefaultPosition, wx.DefaultSize, 0 )
    item68.SetToolTip( wx.ToolTip("Memorizza le variazioni apportate") )
    item66.Add( item68, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item66.AddGrowableCol( 0 )

    item66.AddGrowableCol( 1 )

    item64.Add( item66, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item52.Add( item64, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item52.AddGrowableCol( 1 )

    item0.Add( item52, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 1 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_CANCLIST = 14030
ID_PANGRIDSIN = 14031
ID_DATA = 14032
ID_RESET = 14033
ID_NEWDATALABEL = 14034
ID_NEWDATA = 14035
ID_COPYLIS = 14036

def SintesiPanelFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item1 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item2 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item3 = wx.StaticText( parent, ID_TEXT, "Listini presenti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.SetForegroundColour( wx.BLUE )
    item2.Add( item3, 0, wx.ALIGN_BOTTOM|wx.LEFT|wx.RIGHT, 5 )

    item4 = wx.Button( parent, ID_CANCLIST, "&Elimina", wx.DefaultPosition, [-1,20], 0 )
    item2.Add( item4, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item2.AddGrowableCol( 1 )

    item1.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item5 = wx.Panel( parent, ID_PANGRIDSIN, wx.DefaultPosition, [170,120], wx.SUNKEN_BORDER )
    item1.Add( item5, 0, wx.GROW|wx.LEFT|wx.RIGHT, 5 )

    item6 = wx.FlexGridSizer( 0, 3, 0, 0 )
    
    item7 = wx.StaticText( parent, ID_TEXT, "Data:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item7, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item8 = DateCtrl( parent, ID_DATA, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.SetName( "data" )
    item6.Add( item8, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item9 = wx.Button( parent, ID_RESET, "&Reset", wx.DefaultPosition, [50,-1], 0 )
    item9.SetToolTip( wx.ToolTip("Abbandona le variazioni apportate e riaggiorna la griglia prodotti") )
    item6.Add( item9, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item10 = wx.StaticText( parent, ID_NEWDATALABEL, "Nuovo:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item10.SetName( "newdatalabel" )
    item6.Add( item10, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item11 = DateCtrl( parent, ID_NEWDATA, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item11.SetName( "newdata" )
    item6.Add( item11, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item12 = wx.Button( parent, ID_COPYLIS, "&Copia", wx.DefaultPosition, [50,-1], 0 )
    item12.SetToolTip( wx.ToolTip("Abbandona le variazioni apportate e riaggiorna la griglia prodotti") )
    item6.Add( item12, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.BOTTOM, 5 )

    item1.Add( item6, 0, wx.ALIGN_RIGHT|wx.ALIGN_BOTTOM, 5 )

    item1.AddGrowableCol( 0 )

    item1.AddGrowableRow( 1 )

    item1.AddGrowableRow( 2 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_PVCOSTO = 14037
ID_PVPREZZO = 14038
ID_TVLIST = 14039
ID_PVPREZZO1 = 14040
ID_PVPREZZO2 = 14041
ID_PVPREZZO3 = 14042
ID_PVPREZZO4 = 14043
ID_PVPREZZO5 = 14044
ID_PVPREZZO6 = 14045
ID_PVPREZZO7 = 14046
ID_PVPREZZO8 = 14047
ID_PVPREZZO9 = 14048
ID_BTNOK = 14049

def VariaPercFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item2 = wx.StaticBox( parent, -1, "Variazione del costo/prezzo" )
    item1 = wx.StaticBoxSizer( item2, wx.HORIZONTAL )
    
    item3 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item4 = wx.StaticText( parent, ID_TEXT, "Costo di acquisto:", wx.DefaultPosition, [100,-1], wx.ALIGN_RIGHT )
    item3.Add( item4, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item5 = NumCtrl(parent, ID_PVCOSTO, integerWidth=3, fractionWidth=2, allowNegative=True); item5.SetName("pvcosto")
    item3.Add( item5, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item6 = wx.StaticText( parent, ID_TEXT, "Prezzo al pubblico:", wx.DefaultPosition, [100,-1], wx.ALIGN_RIGHT )
    item3.Add( item6, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item7 = NumCtrl(parent, ID_PVPREZZO, integerWidth=3, fractionWidth=2, allowNegative=True); item7.SetName("pvprezzo")
    item3.Add( item7, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item3.AddGrowableCol( 0 )

    item1.Add( item3, 0, 0, 5 )

    item8 = wx.CheckBox( parent, ID_RICALCPC, "Ricalcola", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.SetValue( True )
    item8.SetName( "ricalcpc" )
    item1.Add( item8, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item9 = TipAggListRadioBox( parent, ID_TVLIST, "Aggiornamento dei prezzi di listino", wx.DefaultPosition, wx.DefaultSize, 
        ["Nessuno: i listini non vengono alterati","Ricalcola come da condizioni del gruppo prezzi","Variazione percentuale di ogni prezzo"] , 1, wx.RA_SPECIFY_COLS )
    item9.SetName( "tvlist" )
    item0.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item11 = wx.StaticBox( parent, -1, "Variazione dei prezzi di listino" )
    item10 = wx.StaticBoxSizer( item11, wx.HORIZONTAL )
    
    item12 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item13 = wx.StaticText( parent, ID_TEXT, "Listino 1:", wx.DefaultPosition, [100,-1], wx.ALIGN_RIGHT )
    item13.SetName( "labelprezzo1" )
    item12.Add( item13, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item14 = NumCtrl(parent, ID_PVPREZZO1, integerWidth=3, fractionWidth=2, allowNegative=True); item14.SetName("pvprezzo1")
    item12.Add( item14, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item15 = wx.StaticText( parent, ID_TEXT, "Listino 2:", wx.DefaultPosition, [100,-1], wx.ALIGN_RIGHT )
    item15.SetName( "labelprezzo2" )
    item12.Add( item15, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item16 = NumCtrl(parent, ID_PVPREZZO2, integerWidth=3, fractionWidth=2, allowNegative=True); item16.SetName("pvprezzo2")
    item12.Add( item16, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item17 = wx.StaticText( parent, ID_TEXT, "Listino 3:", wx.DefaultPosition, [100,-1], wx.ALIGN_RIGHT )
    item17.SetName( "labelprezzo3" )
    item12.Add( item17, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item18 = NumCtrl(parent, ID_PVPREZZO3, integerWidth=3, fractionWidth=2, allowNegative=True); item18.SetName("pvprezzo3")
    item12.Add( item18, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item19 = wx.StaticText( parent, ID_TEXT, "Listino 4:", wx.DefaultPosition, [100,-1], wx.ALIGN_RIGHT )
    item19.SetName( "labelprezzo4" )
    item12.Add( item19, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item20 = NumCtrl(parent, ID_PVPREZZO4, integerWidth=3, fractionWidth=2, allowNegative=True); item20.SetName("pvprezzo4")
    item12.Add( item20, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item21 = wx.StaticText( parent, ID_TEXT, "Listino 5:", wx.DefaultPosition, [100,-1], wx.ALIGN_RIGHT )
    item21.SetName( "labelprezzo5" )
    item12.Add( item21, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item22 = NumCtrl(parent, ID_PVPREZZO5, integerWidth=3, fractionWidth=2, allowNegative=True); item22.SetName("pvprezzo5")
    item12.Add( item22, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item23 = wx.StaticText( parent, ID_TEXT, "Listino 6:", wx.DefaultPosition, [100,-1], wx.ALIGN_RIGHT )
    item23.SetName( "labelprezzo6" )
    item12.Add( item23, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item24 = NumCtrl(parent, ID_PVPREZZO6, integerWidth=3, fractionWidth=2, allowNegative=True); item24.SetName("pvprezzo6")
    item12.Add( item24, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item25 = wx.StaticText( parent, ID_TEXT, "Listino 7:", wx.DefaultPosition, [100,-1], wx.ALIGN_RIGHT )
    item25.SetName( "labelprezzo7" )
    item12.Add( item25, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item26 = NumCtrl(parent, ID_PVPREZZO7, integerWidth=3, fractionWidth=2, allowNegative=True); item26.SetName("pvprezzo7")
    item12.Add( item26, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item27 = wx.StaticText( parent, ID_TEXT, "Listino 8:", wx.DefaultPosition, [100,-1], wx.ALIGN_RIGHT )
    item27.SetName( "labelprezzo8" )
    item12.Add( item27, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item28 = NumCtrl(parent, ID_PVPREZZO8, integerWidth=3, fractionWidth=2, allowNegative=True); item28.SetName("pvprezzo8")
    item12.Add( item28, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item29 = wx.StaticText( parent, ID_TEXT, "Listino 9:", wx.DefaultPosition, [100,-1], wx.ALIGN_RIGHT )
    item29.SetName( "labelprezzo9" )
    item12.Add( item29, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item30 = NumCtrl(parent, ID_PVPREZZO9, integerWidth=3, fractionWidth=2, allowNegative=True); item30.SetName("pvprezzo9")
    item12.Add( item30, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item12.AddGrowableCol( 0 )

    item10.Add( item12, 0, 0, 5 )

    item0.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item31 = wx.BoxSizer( wx.HORIZONTAL )
    
    item32 = wx.Button( parent, ID_BTNOK, "Applica", wx.DefaultPosition, wx.DefaultSize, 0 )
    item32.SetDefault()
    item32.SetToolTip( wx.ToolTip("Applica le variazioni percentuali indicate sui prodotti selezionati") )
    item31.Add( item32, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item31, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_STCOSTO = 14050
ID_STPREZZO = 14051
ID_STPREZZO1 = 14052
ID_STPREZZO2 = 14053
ID_STPREZZO3 = 14054
ID_STPREZZO4 = 14055
ID_STPREZZO5 = 14056
ID_STPREZZO6 = 14057
ID_STPREZZO7 = 14058
ID_STPREZZO8 = 14059
ID_STPREZZO9 = 14060
ID_OKPRINT = 14061

def ColonneDaStampareFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.StaticText( parent, ID_TEXT, "Selezionare le colonne da includere nella stampa del listino.", wx.DefaultPosition, [200,30], 0 )
    item1.SetBackgroundColour( wx.WHITE )
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item2 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item3 = wx.CheckBox( parent, ID_STCOSTO, "Costo di acquisto", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.SetName( "p_costo" )
    item2.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item4 = wx.CheckBox( parent, ID_STPREZZO, "Prezzo al pubblico", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.SetValue( True )
    item4.SetName( "p_prezzo" )
    item2.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item5 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item0.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item6 = wx.CheckBox( parent, ID_STPREZZO1, "Listino 1", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.SetName( "prezzo1" )
    item0.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item7 = wx.CheckBox( parent, ID_STPREZZO2, "Listino 2", wx.DefaultPosition, wx.DefaultSize, 0 )
    item7.SetName( "prezzo2" )
    item0.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item8 = wx.CheckBox( parent, ID_STPREZZO3, "Listino 3", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.SetName( "prezzo3" )
    item0.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item9 = wx.CheckBox( parent, ID_STPREZZO4, "Listino 4", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.SetName( "prezzo4" )
    item0.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item10 = wx.CheckBox( parent, ID_STPREZZO5, "Listino 5", wx.DefaultPosition, wx.DefaultSize, 0 )
    item10.SetName( "prezzo5" )
    item0.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item11 = wx.CheckBox( parent, ID_STPREZZO6, "Listino 6", wx.DefaultPosition, wx.DefaultSize, 0 )
    item11.SetName( "prezzo6" )
    item0.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item12 = wx.CheckBox( parent, ID_STPREZZO7, "Listino 7", wx.DefaultPosition, wx.DefaultSize, 0 )
    item12.SetName( "prezzo7" )
    item0.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item13 = wx.CheckBox( parent, ID_STPREZZO8, "Listino 8", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.SetName( "prezzo8" )
    item0.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item14 = wx.CheckBox( parent, ID_STPREZZO9, "Listino 9", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.SetName( "prezzo9" )
    item0.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item15 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item0.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item16 = wx.BoxSizer( wx.HORIZONTAL )
    
    item17 = wx.Button( parent, ID_OKPRINT, "Conferma", wx.DefaultPosition, wx.DefaultSize, 0 )
    item17.SetDefault()
    item17.SetToolTip( wx.ToolTip("Conferma la stampa del listino con i valori indicati") )
    item16.Add( item17, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item16, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_FOREIGN = 14062
ID_CODFOR1 = 14063
ID_BARCODE1 = 14064
ID_CODFOR2 = 14065
ID_BARCODE2 = 14066
ID_TIPART1 = 14067
ID_TIPART2 = 14068
ID_CATART1 = 14069
ID_CATART2 = 14070
ID_GRUART1 = 14071
ID_GRUART2 = 14072
ID_FORNIT1 = 14073
ID_FORNIT2 = 14074
ID_MARART1 = 14075
ID_MARART2 = 14076
ID_STATUS1 = 14077
ID_STATUS2 = 14078
ID_BUTUPDATE = 14079
ID_PANGRIDLIST = 14080
ID_BUTPRINT = 14081

def ListiniAttualiFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = SelDataPanel(parent, ID_FOREIGN)
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item2 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item3 = wx.FlexGridSizer( 0, 3, 0, 0 )
    
    item4 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item4, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item5 = wx.StaticText( parent, ID_TEXT, "Da", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item6 = wx.StaticText( parent, ID_TEXT, "A", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item3.Add( [ 20, 2 ] , 0, wx.ALIGN_CENTER, 5 )

    item7 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item3.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item8 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item3.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item9 = wx.StaticText( parent, ID_TEXT, "Codici:", wx.DefaultPosition, [60,-1], wx.ALIGN_RIGHT )
    item3.Add( item9, 0, wx.ALIGN_RIGHT|wx.ALIGN_BOTTOM|wx.BOTTOM, 10 )

    item10 = wx.FlexGridSizer( 0, 3, 0, 0 )
    
    item11 = wx.StaticText( parent, ID_TEXT, "Codice interno", wx.DefaultPosition, wx.DefaultSize, 0 )
    item10.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item12 = wx.StaticText( parent, ID_TEXT, "Codice del fornitore", wx.DefaultPosition, wx.DefaultSize, 0 )
    item10.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item13 = wx.StaticText( parent, ID_TEXT, "Barcode", wx.DefaultPosition, wx.DefaultSize, 0 )
    item10.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item14 = TextCtrl( parent, ID_CODICE1, "", wx.DefaultPosition, [90,-1], 0 )
    item14.SetName( "codice1" )
    item10.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item15 = TextCtrl( parent, ID_CODFOR1, "", wx.DefaultPosition, [90,-1], 0 )
    item15.SetName( "codfor1" )
    item10.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item16 = TextCtrl( parent, ID_BARCODE1, "", wx.DefaultPosition, [90,-1], 0 )
    item16.SetName( "barcode1" )
    item10.Add( item16, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item10.AddGrowableCol( 0 )

    item10.AddGrowableCol( 1 )

    item10.AddGrowableCol( 2 )

    item3.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item17 = wx.FlexGridSizer( 0, 3, 0, 0 )
    
    item18 = wx.StaticText( parent, ID_TEXT, "Codice interno", wx.DefaultPosition, wx.DefaultSize, 0 )
    item17.Add( item18, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item19 = wx.StaticText( parent, ID_TEXT, "Codice del fornitore", wx.DefaultPosition, wx.DefaultSize, 0 )
    item17.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item20 = wx.StaticText( parent, ID_TEXT, "Barcode", wx.DefaultPosition, wx.DefaultSize, 0 )
    item17.Add( item20, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item21 = TextCtrl( parent, ID_CODICE2, "", wx.DefaultPosition, [120,-1], 0 )
    item21.SetName( "codice2" )
    item17.Add( item21, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item22 = TextCtrl( parent, ID_CODFOR2, "", wx.DefaultPosition, [90,-1], 0 )
    item22.SetName( "codfor2" )
    item17.Add( item22, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item23 = TextCtrl( parent, ID_BARCODE2, "", wx.DefaultPosition, [90,-1], 0 )
    item23.SetName( "barcode2" )
    item17.Add( item23, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item17.AddGrowableCol( 0 )

    item17.AddGrowableCol( 1 )

    item17.AddGrowableCol( 2 )

    item3.Add( item17, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item24 = wx.StaticText( parent, ID_TEXT, "Tipo:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item3.Add( item24, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item25 = LinkTableTipArt(parent, ID_TIPART1, 'tipart1')
    item3.Add( item25, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item26 = LinkTableTipArt(parent, ID_TIPART2, 'tipart2')
    item3.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item27 = wx.StaticText( parent, ID_TEXT, "Categoria:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item3.Add( item27, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item28 = LinkTableCatArt(parent, ID_CATART1, 'catart1')
    item3.Add( item28, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item29 = LinkTableCatArt(parent, ID_CATART2, 'catart2')
    item3.Add( item29, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item30 = wx.StaticText( parent, ID_TEXT, "Gruppo:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item3.Add( item30, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item31 = LinkTableGruArt(parent, ID_GRUART1, 'gruart1')
    item3.Add( item31, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item32 = LinkTableGruArt(parent, ID_GRUART2, 'gruart2')
    item3.Add( item32, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item33 = wx.StaticText( parent, ID_TEXT, "Fornitore:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item3.Add( item33, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item34 = LinkTableFornit(parent, ID_FORNIT1, 'fornit1')
    item3.Add( item34, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item35 = LinkTableFornit(parent, ID_FORNIT2, 'fornit2')
    item3.Add( item35, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item36 = wx.StaticText( parent, ID_TEXT, "Marca:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item3.Add( item36, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item37 = LinkTableMarArt(parent, ID_MARART1, 'marart1')
    item3.Add( item37, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item38 = LinkTableMarArt(parent, ID_MARART2, 'marart2')
    item3.Add( item38, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item39 = wx.StaticText( parent, ID_TEXT, "Status:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item3.Add( item39, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item40 = LinkTableStatArt(parent, ID_STATUS1, 'status1')
    item3.Add( item40, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item41 = LinkTableStatArt(parent, ID_STATUS2, 'status2')
    item3.Add( item41, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item3.AddGrowableCol( 1 )

    item3.AddGrowableCol( 2 )

    item2.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item42 = wx.Button( parent, ID_BUTUPDATE, "Aggiorna", wx.DefaultPosition, wx.DefaultSize, 0 )
    item42.SetDefault()
    item42.SetName( "butupdate" )
    item2.Add( item42, 0, wx.ALIGN_BOTTOM|wx.ALIGN_CENTER_HORIZONTAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item2.AddGrowableCol( 0 )

    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item43 = wx.StaticText( parent, ID_TEXT, "Elenco prodotti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item43.SetForegroundColour( wx.BLUE )
    item0.Add( item43, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item44 = wx.Panel( parent, ID_PANGRIDLIST, wx.DefaultPosition, [950,412], 0 )
    item44.SetName( "pangridlist" )
    item0.Add( item44, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item45 = wx.Button( parent, ID_BUTPRINT, "Stampa", wx.DefaultPosition, wx.DefaultSize, 0 )
    item45.SetName( "butprint" )
    item0.Add( item45, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 3 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_DATAVAL = 14082
ID_INCL_COSTO = 14083
ID_INCL_PZCONF = 14084

def ListiniAttualiSelDataFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item1 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item2 = wx.StaticText( parent, ID_TEXT, "Validità al:", wx.DefaultPosition, [60,-1], wx.ALIGN_RIGHT )
    item1.Add( item2, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item3 = DateCtrl( parent, ID_DATAVAL, "", wx.DefaultPosition, [80,-1], 0 )
    item3.SetName( "dataval" )
    item1.Add( item3, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item4 = wx.StaticText( parent, ID_TEXT, "Includi:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item4, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item5 = wx.CheckBox( parent, ID_INCL_COSTO, "Costo di acquisto", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.SetName( "incl_costo" )
    item1.Add( item5, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item6 = wx.CheckBox( parent, ID_INCL_PZCONF, "Pz.Conf.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.SetName( "incl_pzconf" )
    item1.Add( item6, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_PDC = 14085
ID_BUTCHICOSA = 14086

def GrigliaPrezziAttualiSelDataFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item1 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item2 = wx.StaticText( parent, ID_TEXT, "Validità:", wx.DefaultPosition, [60,-1], wx.ALIGN_RIGHT )
    item1.Add( item2, 0, wx.ALIGN_RIGHT|wx.ALIGN_BOTTOM|wx.TOP|wx.BOTTOM, 5 )

    item3 = wx.BoxSizer( wx.VERTICAL )
    
    item4 = wx.StaticText( parent, ID_TEXT, "Data griglia", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item5 = DateCtrl( parent, ID_DATAVAL, "", wx.DefaultPosition, [80,-1], 0 )
    item5.SetName( "dataval" )
    item3.Add( item5, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item1.Add( item3, 0, wx.ALIGN_CENTER, 5 )

    item6 = wx.StaticText( parent, ID_TEXT, "Anagrafica:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item6, 0, wx.ALIGN_BOTTOM|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item7 = wx.BoxSizer( wx.VERTICAL )
    
    item7.Add( [ 400, 2 ] , 0, wx.ALIGN_CENTER, 5 )

    item8 = LinkTableCliFor(parent, ID_PDC, 'id_pdc')
    item7.Add( item8, 0, wx.GROW|wx.ALIGN_BOTTOM|wx.ALL, 5 )

    item1.Add( item7, 0, wx.ALIGN_BOTTOM|wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item9 = wx.Button( parent, ID_BUTCHICOSA, "Chi ha cosa?", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.SetName( "butchicosa" )
    item1.Add( item9, 0, wx.ALIGN_BOTTOM|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_ELENCOTITLE = 14087

def VediPrezziInVigoreFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.StaticText( parent, ID_ELENCOTITLE, "Elenco prodotti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.SetForegroundColour( wx.BLUE )
    item1.SetName( "elencotitle" )
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item2 = wx.Panel( parent, ID_PANGRIDLIST, wx.DefaultPosition, [950,412], 0 )
    item2.SetName( "pangridlist" )
    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item3 = wx.Button( parent, ID_BUTPRINT, "Stampa", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.SetName( "butprint" )
    item0.Add( item3, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 1 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_PANGRIDRIEP = 14088

def ChiCosaFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.Panel( parent, ID_PANGRIDRIEP, wx.DefaultPosition, [500,350], 0 )
    item1.SetName( "pangridriep" )
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_NUMPRODOTTI = 14089
ID_NEW_GRUPREZ = 14090
ID_SOLOSENZAGP = 14091
ID_BUTASSEGNA = 14092

def AssegnaGruPrezFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item2 = wx.StaticText( parent, ID_TEXT, "Prodotti selezionati:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item2, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP, 5 )

    item3 = wx.StaticText( parent, ID_NUMPRODOTTI, "32", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.SetFont( wx.Font( 10, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item3.SetName( "numprodotti" )
    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item4 = wx.StaticText( parent, ID_TEXT, "Nuovo Gruppo Prezzi:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item4, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item5 = LinkTableGruPrez(parent, ID_NEW_GRUPREZ, 'new_gruprez')
    item1.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item6 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item6, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item7 = wx.CheckBox( parent, ID_SOLOSENZAGP, "Solo prodotti senza gruppo prezzi", wx.DefaultPosition, [200,-1], 0 )
    item7.SetName( "solosenzagp" )
    item1.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item1.AddGrowableCol( 1 )

    item0.Add( item1, 0, wx.GROW|wx.ALL, 5 )

    item8 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item0.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item9 = wx.BoxSizer( wx.HORIZONTAL )
    
    item10 = wx.Button( parent, ID_BUTASSEGNA, "&Assegna", wx.DefaultPosition, wx.DefaultSize, 0 )
    item10.SetName( "butassegna" )
    item9.Add( item10, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item9, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0


def ValutaCostiPrezziBaseFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item2 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item3 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item4 = wx.StaticText( parent, ID_TEXT, "Selezione prodotti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.SetForegroundColour( wx.BLUE )
    item3.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item5 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item3.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item6 = wx.FlexGridSizer( 0, 3, 0, 0 )
    
    item7 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item7, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item8 = wx.StaticText( parent, ID_TEXT, "Da:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP, 5 )

    item9 = wx.StaticText( parent, ID_TEXT, "A:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item10 = wx.StaticText( parent, ID_TEXT, "Codice:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item6.Add( item10, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item11 = TextCtrl( parent, ID_CODICE1, "", wx.DefaultPosition, [120,-1], 0 )
    item11.SetName( "codice1" )
    item6.Add( item11, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item12 = TextCtrl( parent, ID_CODICE2, "", wx.DefaultPosition, [120,-1], 0 )
    item12.SetName( "codice2" )
    item6.Add( item12, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item13 = wx.StaticText( parent, ID_TEXT, "Descrizione:", wx.DefaultPosition, [70,-1], wx.ALIGN_RIGHT )
    item6.Add( item13, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item14 = TextCtrl( parent, ID_DESCRIZ1, "", wx.DefaultPosition, [80,-1], 0 )
    item14.SetName( "descriz1" )
    item6.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item15 = TextCtrl( parent, ID_DESCRIZ2, "", wx.DefaultPosition, [80,-1], 0 )
    item15.SetName( "descriz2" )
    item6.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item16 = wx.StaticText( parent, ID_TEXT, "Tipo:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item6.Add( item16, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item17 = LinkTableTipArt(parent, ID_FILT_TIPART, 'id_tipart1')
    item6.Add( item17, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item18 = LinkTableTipArt(parent, ID_FILT_TIPART, 'id_tipart2')
    item6.Add( item18, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item19 = wx.StaticText( parent, ID_TEXT, "Categoria:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item6.Add( item19, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item20 = LinkTableCatArt(parent, ID_FILT_CATART, 'id_catart1')
    item6.Add( item20, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item21 = LinkTableCatArt(parent, ID_FILT_CATART, 'id_catart2')
    item6.Add( item21, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item22 = wx.StaticText( parent, ID_TEXT, "Gruppo:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item6.Add( item22, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item23 = LinkTableGruArt(parent, ID_FILT_GRUART, 'id_gruart1')
    item6.Add( item23, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item24 = LinkTableGruArt(parent, ID_FILT_GRUART, 'id_gruart2')
    item6.Add( item24, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item25 = wx.StaticText( parent, ID_TEXT, "Fornitore:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item6.Add( item25, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item26 = LinkTableFornit(parent, ID_FILT_FORNIT1, 'id_fornit1')
    item6.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item27 = LinkTableFornit(parent, ID_FILT_FORNIT2, 'id_fornit2')
    item6.Add( item27, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item28 = wx.StaticText( parent, ID_TEXT, "Status:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item6.Add( item28, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item29 = LinkTableStatArt(parent, ID_FILT_STATUS1, 'id_status1')
    item6.Add( item29, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item30 = LinkTableStatArt(parent, ID_FILT_STATUS2, 'id_status2')
    item6.Add( item30, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item6.AddGrowableCol( 1 )

    item6.AddGrowableCol( 2 )

    item3.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item31 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item3.Add( item31, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item3.AddGrowableCol( 0 )

    item2.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item32 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [-1,20], wx.LI_VERTICAL )
    item2.Add( item32, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item2.AddGrowableCol( 0 )

    item2.AddGrowableRow( 0 )

    item1.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item1.AddGrowableCol( 0 )

    item1.AddGrowableRow( 0 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 1 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_PANGRIDMOV = 14093

def MovimentiPrezziFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.StaticText( parent, ID_TEXT, "Prezzi presenti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.SetForegroundColour( wx.BLUE )
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item2 = wx.Panel( parent, ID_PANGRIDMOV, wx.DefaultPosition, [800,450], wx.SUNKEN_BORDER )
    item2.SetName( "pangridmov" )
    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 1 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_DATREG1 = 14094
ID_DATREG2 = 14095
ID_FILT_ANAG1 = 14096
ID_FILT_ANAG2 = 14097
ID_FILT_AGENTE1 = 14098
ID_FILT_AGENTE2 = 14099

def ValutaPrezziClientiFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.StaticText( parent, ID_TEXT, "Selezioni sulle vendite", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.SetForegroundColour( wx.BLUE )
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item2 = wx.FlexGridSizer( 0, 3, 0, 0 )
    
    item3 = wx.StaticText( parent, ID_TEXT, "Data:", wx.DefaultPosition, [70,-1], wx.ALIGN_RIGHT )
    item2.Add( item3, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item4 = DateCtrl( parent, ID_DATREG1, "", wx.DefaultPosition, [80,-1], 0 )
    item4.SetName( "datreg1" )
    item2.Add( item4, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item5 = DateCtrl( parent, ID_DATREG2, "", wx.DefaultPosition, [80,-1], 0 )
    item5.SetName( "datreg2" )
    item2.Add( item5, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item6 = wx.StaticText( parent, ID_TEXT, "Cliente:", wx.DefaultPosition, [70,-1], wx.ALIGN_RIGHT )
    item2.Add( item6, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item7 = LinkTableCliente(parent, ID_FILT_ANAG1, 'id_anag1')
    item2.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item8 = LinkTableCliente(parent, ID_FILT_ANAG2, 'id_anag2')
    item2.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item9 = wx.StaticText( parent, ID_TEXT, "Agente:", wx.DefaultPosition, [70,-1], wx.ALIGN_RIGHT )
    item2.Add( item9, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item10 = LinkTableAgente(parent, ID_FILT_AGENTE1, 'id_agente1')
    item2.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item11 = LinkTableAgente(parent, ID_FILT_AGENTE2, 'id_agente2')
    item2.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item2.AddGrowableCol( 1 )

    item2.AddGrowableCol( 2 )

    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0


def ValutaCostiFornitoriFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.StaticText( parent, ID_TEXT, "Selezioni sugli acquisti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.SetForegroundColour( wx.BLUE )
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item2 = wx.FlexGridSizer( 0, 3, 0, 0 )
    
    item3 = wx.StaticText( parent, ID_TEXT, "Data:", wx.DefaultPosition, [70,-1], wx.ALIGN_RIGHT )
    item2.Add( item3, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item4 = DateCtrl( parent, ID_DATREG1, "", wx.DefaultPosition, [80,-1], 0 )
    item4.SetName( "datreg1" )
    item2.Add( item4, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item5 = DateCtrl( parent, ID_DATREG2, "", wx.DefaultPosition, [80,-1], 0 )
    item5.SetName( "datreg2" )
    item2.Add( item5, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item6 = wx.StaticText( parent, ID_TEXT, "Fornitore:", wx.DefaultPosition, [70,-1], wx.ALIGN_RIGHT )
    item2.Add( item6, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item7 = LinkTableFornit(parent, ID_FILT_ANAG1, 'id_anag1')
    item2.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item8 = LinkTableFornit(parent, ID_FILT_ANAG2, 'id_anag2')
    item2.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item2.AddGrowableCol( 1 )

    item2.AddGrowableCol( 2 )

    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_PANBASE = 14100
ID_PANANAG = 14101
ID_PANGRIDVPV = 14102
ID_PRINT = 14103

def ValutaPrezziApplicatiFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item2 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item3 = ValutaCostiPrezziBasePanel( parent, ID_PANBASE, wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item4 = ValutaPrezziClientiPanel( parent, ID_PANANAG, wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item2.AddGrowableCol( 0 )

    item1.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item5 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item6 = OrdinamentoRadioBox( parent, ID_ORDINAM, "Ordinamento", wx.DefaultPosition, wx.DefaultSize, 
        ["Codice","Descrizione","Cod.Fornitore"] , 1, wx.RA_SPECIFY_COLS )
    item6.SetName( "ordinam" )
    item5.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item7 = wx.CheckBox( parent, ID_SSV, "Solo Status Visibile", wx.DefaultPosition, wx.DefaultSize, 0 )
    item7.SetValue( True )
    item7.SetName( "ssv" )
    item5.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item8 = wx.Button( parent, ID_UPDATE, "&Aggiorna", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.SetDefault()
    item8.SetName( "update" )
    item5.Add( item8, 0, wx.ALIGN_RIGHT|wx.ALIGN_BOTTOM|wx.ALL, 5 )

    item5.AddGrowableRow( 2 )

    item1.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item1.AddGrowableCol( 0 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item9 = wx.StaticText( parent, ID_TEXT, "Prodotti venduti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.SetForegroundColour( wx.BLUE )
    item0.Add( item9, 0, wx.GROW|wx.ALIGN_BOTTOM|wx.LEFT, 5 )

    item10 = wx.Panel( parent, ID_PANGRIDVPV, wx.DefaultPosition, [990,350], wx.SUNKEN_BORDER )
    item10.SetName( "pangridvpv" )
    item0.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item11 = wx.Button( parent, ID_PRINT, "Stampa", wx.DefaultPosition, wx.DefaultSize, 0 )
    item11.SetName( "print" )
    item0.Add( item11, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0


def ValutaCostiAcquistoFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item2 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item3 = ValutaCostiPrezziBasePanel( parent, ID_PANBASE, wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item4 = ValutaCostiFornitoriPanel( parent, ID_PANANAG, wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item2.AddGrowableCol( 0 )

    item1.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item5 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item6 = OrdinamentoRadioBox( parent, ID_ORDINAM, "Ordinamento", wx.DefaultPosition, wx.DefaultSize, 
        ["Codice","Descrizione","Cod.Fornitore"] , 1, wx.RA_SPECIFY_COLS )
    item6.SetName( "ordinam" )
    item5.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item7 = wx.CheckBox( parent, ID_SSV, "Solo Status Visibile", wx.DefaultPosition, wx.DefaultSize, 0 )
    item7.SetValue( True )
    item7.SetName( "ssv" )
    item5.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item8 = wx.Button( parent, ID_UPDATE, "&Aggiorna", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.SetDefault()
    item8.SetName( "update" )
    item5.Add( item8, 0, wx.ALIGN_RIGHT|wx.ALIGN_BOTTOM|wx.ALL, 5 )

    item5.AddGrowableRow( 2 )

    item1.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item1.AddGrowableCol( 0 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item9 = wx.StaticText( parent, ID_TEXT, "Prodotti acquistati", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.SetForegroundColour( wx.BLUE )
    item0.Add( item9, 0, wx.GROW|wx.ALIGN_BOTTOM|wx.LEFT, 5 )

    item10 = wx.Panel( parent, ID_PANGRIDVPV, wx.DefaultPosition, [990,350], wx.SUNKEN_BORDER )
    item10.SetName( "pangridvpv" )
    item0.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item11 = wx.Button( parent, ID_PRINT, "Stampa", wx.DefaultPosition, wx.DefaultSize, 0 )
    item11.SetName( "print" )
    item0.Add( item11, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
