# -*- coding: iso-8859-15 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: movint.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid

# Custom source
from wx import Panel as wxPanel

from awc.controls.linktable import LinkTable
from awc.controls.datectrl import DateCtrl
from awc.controls.textctrl import TextCtrl
from awc.controls.numctrl import NumCtrl
from awc.controls.radiobox import RadioBox

from anag.lib import LinkTableMagazz, LinkTableDocMagazz, LinkTableMovMagazz, LinkTablePdc, LinkTableAgente, LinkTableProd, LinkTableAliqIva, LinkTableZona

from anag.mag import MagazzDialog
from anag.agenti import AgentiDialog
from anag.prod import ProdDialog
from anag.aliqiva import AliqIvaDialog

from Env import Azienda
bt = Azienda.BaseTab

class TipOrdinamRadioBox(RadioBox):

    def __init__(self, *args, **kwargs):
        RadioBox.__init__(self, *args, **kwargs)
        self.SetDataLink(values="DATX")



# Window functions

ID_LABMASMAG = 14000
ID_MASID_MAGAZZ = 14001
ID_LABMASDOC = 14002
ID_MASID_TIPDOC = 14003
ID_LABMASPDC = 14004
ID_MASID_PDC = 14005
ID_LABMASAGE = 14006
ID_MASID_AGENTE = 14007
ID_NODOCANN = 14008
ID_NODOCACQ = 14009
ID_LABMASMOV = 14010
ID_MASID_PROD = 14011
ID_MASDESCRIZ = 14012
ID_MASID_TIPMOV = 14013
ID_LABMASIVA = 14014
ID_MASID_ALIQIVA = 14015
ID_NOMOVANN = 14016
ID_SOLOPRMANCA = 14017
ID_TEXT = 14018
ID_LABMASNUM1 = 14019
ID_LABMASDAT1 = 14020
ID_LABMASNUM2 = 14021
ID_LABMASDAT2 = 14022
ID_MASNUMDOC1 = 14023
ID_MASDATDOC1 = 14024
ID_MASNUMDOC2 = 14025
ID_MASDATDOC2 = 14026
ID_LABMASREG = 14027
ID_MASNUMREG1 = 14028
ID_MASDATREG1 = 14029
ID_MASNUMREG2 = 14030
ID_MASDATREG2 = 14031
ID_LABMASRIF = 14032
ID_MASNUMRIF1 = 14033
ID_MASDATRIF1 = 14034
ID_MASNUMRIF2 = 14035
ID_MASDATRIF2 = 14036
ID_TIPORD = 14037
ID_MASBUTUPD = 14038
ID_MASBUTPRT = 14039
ID_LABTOTNUM = 14040
ID_LABTOTIMP = 14041
ID_LABTOTMOV = 14042
ID_TOTNUMMOV = 14043
ID_LABTOTIMPORTO = 14044
ID_TOTIMPORTO = 14045
ID_LABTOTMERCE = 14046
ID_TOTMERCE = 14047
ID_LABTOTSCRIP = 14048
ID_TOTSCRIP = 14049
ID_LABTOTSPESE = 14050
ID_TOTSPESE = 14051
ID_LABTOTSCM = 14052
ID_TOTSCMCE = 14053
ID_LABTOTSERV = 14054
ID_TOTSERVI = 14055
ID_LABTOTOMG = 14056
ID_TOTOMAGG = 14057
ID_LABTOTTRASP = 14058
ID_TOTTRASP = 14059
ID_PANGRIDMOV = 14060

def _OLD_MovMagFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item0.AddGrowableCol( 0 )
    item0.AddGrowableRow( 1 )
    
    item1 = wx.FlexGridSizer( 1, 0, 0, 0 )
    item1.AddGrowableCol( 0 )
    
    item2 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item2.AddGrowableCol( 0 )
    item2.AddGrowableRow( 1 )
    
    item4 = wx.StaticBox( parent, -1, "Selezioni sui documenti" )
    item3 = wx.StaticBoxSizer( item4, wx.VERTICAL )
    
    item5 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item5.AddGrowableCol( 0 )
    
    item6 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item6.AddGrowableCol( 0 )
    
    item7 = wx.StaticText( parent, ID_LABMASMAG, "Magazzino", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item8 = LinkTableMagazz(parent, ID_MASID_MAGAZZ, "masid_magazz")
    item6.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item5.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item9 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item9.AddGrowableCol( 0 )
    
    item10 = wx.StaticText( parent, ID_LABMASDOC, "Documento:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item11 = LinkTableDocMagazz(parent, ID_MASID_TIPDOC, "masid_tipdoc")
    item9.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item5.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item12 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item12.AddGrowableCol( 0 )
    
    item13 = wx.StaticText( parent, ID_LABMASPDC, "Sottoconto", wx.DefaultPosition, wx.DefaultSize, 0 )
    item12.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item14 = LinkTablePdc(parent, ID_MASID_PDC, "masid_pdc")
    item12.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item5.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item15 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item15.AddGrowableCol( 0 )
    
    item16 = wx.StaticText( parent, ID_LABMASAGE, "Agente", wx.DefaultPosition, wx.DefaultSize, 0 )
    item15.Add( item16, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item17 = LinkTableAgente(parent, ID_MASID_AGENTE, "masid_agente")
    item15.Add( item17, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item5.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item3.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item18 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item19 = wx.CheckBox( parent, ID_NODOCANN, "Escludi documenti annullati", wx.DefaultPosition, wx.DefaultSize, 0 )
    item19.SetValue( True )
    item19.SetName( "escdocann" )
    item18.Add( item19, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item20 = wx.CheckBox( parent, ID_NODOCACQ, "Escludi documenti acquisiti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item20.SetValue( True )
    item20.SetName( "escdocacq" )
    item18.Add( item20, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item3.Add( item18, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item2.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item22 = wx.StaticBox( parent, -1, "Selezioni sui movimenti" )
    item21 = wx.StaticBoxSizer( item22, wx.VERTICAL )
    
    item23 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item23.AddGrowableCol( 0 )
    
    item24 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item24.AddGrowableCol( 0 )
    
    item25 = wx.StaticText( parent, ID_LABMASMOV, "Prodotto:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item24.Add( item25, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item26 = LinkTableProd(parent, ID_MASID_PROD, "masid_prod")
    item24.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item27 = wx.StaticText( parent, ID_LABMASMOV, "Descrizione libera (contenuto):", wx.DefaultPosition, wx.DefaultSize, 0 )
    item24.Add( item27, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item28 = wx.TextCtrl( parent, ID_MASDESCRIZ, "", wx.DefaultPosition, [80,-1], 0 )
    item28.SetName( "masdescriz" )
    item24.Add( item28, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item29 = wx.StaticText( parent, ID_LABMASMOV, "Movimento:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item24.Add( item29, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item30 = LinkTableMovMagazz(parent, ID_MASID_TIPMOV, "masid_tipmov")
    item24.Add( item30, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item23.Add( item24, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item31 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item31.AddGrowableCol( 0 )
    
    item32 = wx.StaticText( parent, ID_LABMASIVA, "Aliquota IVA", wx.DefaultPosition, wx.DefaultSize, 0 )
    item31.Add( item32, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item33 = LinkTableAliqIva(parent, ID_MASID_ALIQIVA, "masid_aliqiva")
    item31.Add( item33, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item23.Add( item31, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item21.Add( item23, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item34 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item35 = wx.CheckBox( parent, ID_NOMOVANN, "Escludi movimenti annullati", wx.DefaultPosition, wx.DefaultSize, 0 )
    item35.SetValue( True )
    item35.SetName( "escmovann" )
    item34.Add( item35, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item36 = wx.CheckBox( parent, ID_SOLOPRMANCA, "Solo righe con prezzo mancante", wx.DefaultPosition, wx.DefaultSize, 0 )
    item36.SetName( "soloprmanca" )
    item34.Add( item36, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item21.Add( item34, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item2.Add( item21, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item1.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item37 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item37.AddGrowableRow( 1 )
    
    item39 = wx.StaticBox( parent, -1, "Periodo" )
    item38 = wx.StaticBoxSizer( item39, wx.VERTICAL )
    
    item40 = wx.FlexGridSizer( 0, 5, 0, 0 )
    item40.AddGrowableCol( 0 )
    
    item41 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item40.Add( item41, 0, wx.ALIGN_CENTER|wx.TOP, 5 )

    item42 = wx.StaticText( parent, ID_LABMASNUM1, "Da numero:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item40.Add( item42, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item43 = wx.StaticText( parent, ID_LABMASDAT1, "Da data:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item40.Add( item43, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item44 = wx.StaticText( parent, ID_LABMASNUM2, "A numero:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item40.Add( item44, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item45 = wx.StaticText( parent, ID_LABMASDAT2, "A data:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item40.Add( item45, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item46 = wx.StaticText( parent, ID_LABMASDOC, "Documento", wx.DefaultPosition, wx.DefaultSize, wx.ST_NO_AUTORESIZE|wx.ALIGN_RIGHT )
    item40.Add( item46, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item47 = TextCtrl( parent, ID_MASNUMDOC1, "", wx.DefaultPosition, [60,-1], 0 )
    item47.SetName( "masnumdoc1" )
    item40.Add( item47, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item48 = DateCtrl( parent, ID_MASDATDOC1, "", wx.DefaultPosition, [80,-1], 0 )
    item48.SetName( "masdatdoc1" )
    item40.Add( item48, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item49 = TextCtrl( parent, ID_MASNUMDOC2, "", wx.DefaultPosition, [60,-1], 0 )
    item49.SetName( "masnumdoc2" )
    item40.Add( item49, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item50 = DateCtrl( parent, ID_MASDATDOC2, "", wx.DefaultPosition, [80,-1], 0 )
    item50.SetName( "masdatdoc2" )
    item40.Add( item50, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item51 = wx.StaticText( parent, ID_LABMASREG, "Registrazione", wx.DefaultPosition, wx.DefaultSize, wx.ST_NO_AUTORESIZE|wx.ALIGN_RIGHT )
    item40.Add( item51, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item52 = TextCtrl( parent, ID_MASNUMREG1, "", wx.DefaultPosition, [60,-1], 0 )
    item52.SetName( "masnumreg1" )
    item40.Add( item52, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item53 = DateCtrl( parent, ID_MASDATREG1, "", wx.DefaultPosition, [80,-1], 0 )
    item53.SetName( "masdatreg1" )
    item40.Add( item53, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item54 = TextCtrl( parent, ID_MASNUMREG2, "", wx.DefaultPosition, [60,-1], 0 )
    item54.SetName( "masnumreg2" )
    item40.Add( item54, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item55 = DateCtrl( parent, ID_MASDATREG2, "", wx.DefaultPosition, [80,-1], 0 )
    item55.SetName( "masdatreg2" )
    item40.Add( item55, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item56 = wx.StaticText( parent, ID_LABMASRIF, "Riferimento", wx.DefaultPosition, wx.DefaultSize, wx.ST_NO_AUTORESIZE|wx.ALIGN_RIGHT )
    item40.Add( item56, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item57 = TextCtrl( parent, ID_MASNUMRIF1, "", wx.DefaultPosition, [60,-1], 0 )
    item57.SetName( "masnumrif1" )
    item40.Add( item57, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item58 = DateCtrl( parent, ID_MASDATRIF1, "", wx.DefaultPosition, [80,-1], 0 )
    item58.SetName( "masdatrif1" )
    item40.Add( item58, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item59 = TextCtrl( parent, ID_MASNUMRIF2, "", wx.DefaultPosition, [60,-1], 0 )
    item59.SetName( "masnumrif2" )
    item40.Add( item59, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item60 = DateCtrl( parent, ID_MASDATRIF2, "", wx.DefaultPosition, [80,-1], 0 )
    item60.SetName( "masdatrif2" )
    item40.Add( item60, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item38.Add( item40, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item37.Add( item38, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item61 = wx.FlexGridSizer( 1, 0, 0, 0 )
    item61.AddGrowableRow( 0 )
    
    item62 = TipOrdinamRadioBox( parent, ID_TIPORD, "Ordina per:", wx.DefaultPosition, wx.DefaultSize, 
        ["Data, Tipo documento, Numero","Anagrafica, Data, Tipo documento, Numero","Tipo documento, Anno, Numero","Tipo documento, Anagrafica, Anno, Numero"] , 1, wx.RA_SPECIFY_COLS )
    item62.SetName( "tipord" )
    item61.Add( item62, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL|wx.RIGHT, 5 )

    item63 = wx.BoxSizer( wx.HORIZONTAL )
    
    item64 = wx.Button( parent, ID_MASBUTUPD, "Applica", wx.DefaultPosition, wx.DefaultSize, 0 )
    item64.SetDefault()
    item63.Add( item64, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item65 = wx.Button( parent, ID_MASBUTPRT, "Stampa", wx.DefaultPosition, wx.DefaultSize, 0 )
    item63.Add( item65, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item61.Add( item63, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item37.Add( item61, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item67 = wx.StaticBox( parent, -1, "Totali" )
    item66 = wx.StaticBoxSizer( item67, wx.VERTICAL )
    
    item68 = wx.FlexGridSizer( 0, 4, 0, 0 )
    item68.AddGrowableCol( 0 )
    
    item69 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item68.Add( item69, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item70 = wx.StaticText( parent, ID_LABTOTNUM, "Numero", wx.DefaultPosition, wx.DefaultSize, 0 )
    item68.Add( item70, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item71 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item68.Add( item71, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item72 = wx.StaticText( parent, ID_LABTOTIMP, "Importo", wx.DefaultPosition, wx.DefaultSize, 0 )
    item68.Add( item72, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item73 = wx.StaticText( parent, ID_LABTOTMOV, "Movimenti estratti:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item73.SetName( "totmov" )
    item68.Add( item73, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item74 = masked.NumCtrl(parent, integerWidth=8); item74.SetName("totnummov"); item74.SetEditable(False)
    item68.Add( item74, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item75 = wx.StaticText( parent, ID_LABTOTIMPORTO, "per un totale di:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item68.Add( item75, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item76 = masked.NumCtrl( parent, integerWidth=11, fractionWidth=bt.VALINT_DECIMALS); item76.SetName("totimporto"); item76.SetEditable(False)
    item68.Add( item76, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item77 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item68.Add( item77, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item78 = wx.StaticText( parent, ID_LABTOTIMP, "Imponibile", wx.DefaultPosition, wx.DefaultSize, 0 )
    item68.Add( item78, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item79 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item68.Add( item79, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item80 = wx.StaticText( parent, ID_LABTOTIMP, "Importo", wx.DefaultPosition, wx.DefaultSize, 0 )
    item68.Add( item80, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item81 = wx.StaticText( parent, ID_LABTOTMERCE, "Merce", wx.DefaultPosition, wx.DefaultSize, 0 )
    item68.Add( item81, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item82 = masked.NumCtrl(parent, integerWidth=11, fractionWidth=bt.VALINT_DECIMALS); item82.SetName("totimpmerce"); item82.SetEditable(False)
    item68.Add( item82, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item83 = wx.StaticText( parent, ID_LABTOTSCRIP, "Sconti ripartiti:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item68.Add( item83, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item84 = masked.NumCtrl(parent, integerWidth=11, fractionWidth=bt.VALINT_DECIMALS); item84.SetName("totimpscrip"); item84.SetEditable(False)
    item68.Add( item84, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item85 = wx.StaticText( parent, ID_LABTOTSPESE, "Spese", wx.DefaultPosition, wx.DefaultSize, 0 )
    item68.Add( item85, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item86 = masked.NumCtrl(parent, integerWidth=11, fractionWidth=bt.VALINT_DECIMALS); item86.SetName("totimpspese"); item86.SetEditable(False)
    item68.Add( item86, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item87 = wx.StaticText( parent, ID_LABTOTSCM, "Sconti in merce:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item68.Add( item87, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item88 = masked.NumCtrl(parent, integerWidth=11, fractionWidth=bt.VALINT_DECIMALS); item88.SetName("totimpscmce"); item88.SetEditable(False)
    item68.Add( item88, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item89 = wx.StaticText( parent, ID_LABTOTSERV, "Servizi", wx.DefaultPosition, wx.DefaultSize, 0 )
    item68.Add( item89, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item90 = masked.NumCtrl(parent, integerWidth=11, fractionWidth=bt.VALINT_DECIMALS); item90.SetName("totimpservi"); item90.SetEditable(False)
    item68.Add( item90, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item91 = wx.StaticText( parent, ID_LABTOTOMG, "Omaggi:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item68.Add( item91, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item92 = masked.NumCtrl(parent, integerWidth=11, fractionWidth=bt.VALINT_DECIMALS); item92.SetName("totimpomagg"); item92.SetEditable(False)
    item68.Add( item92, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item93 = wx.StaticText( parent, ID_LABTOTTRASP, "Trasporti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item68.Add( item93, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item94 = masked.NumCtrl(parent, integerWidth=11, fractionWidth=bt.VALINT_DECIMALS); item94.SetName("totimptrasp"); item94.SetEditable(False)
    item68.Add( item94, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item95 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item68.Add( item95, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item96 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item68.Add( item96, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item66.Add( item68, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item37.Add( item66, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item1.Add( item37, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item97 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item97.AddGrowableCol( 0 )
    item97.AddGrowableRow( 1 )
    
    item98 = wx.StaticText( parent, ID_TEXT, "Movimenti presenti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item98.SetForegroundColour( wx.BLUE )
    item97.Add( item98, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item99 = wx.Panel( parent, ID_PANGRIDMOV, wx.DefaultPosition, [800,280], wx.SUNKEN_BORDER )
    item97.Add( item99, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.Add( item97, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_EVAPARZ = 14061
ID_EVANONE = 14062
ID_EVACHIUSI = 14063
ID_LABMASTOTDOCQ = 14064
ID_MASTOTNUMMOV = 14065
ID_LABMASTOTDOCV = 14066
ID_MASTOTDOCQ = 14067
ID_MASTOTDOCV = 14068
ID_LABMASACQ = 14069
ID_MASTOTACQQ = 14070
ID_MASTOTACQV = 14071
ID_LABMASRES = 14072
ID_MASTOTRESQ = 14073
ID_MASTOTRESV = 14074

def EvaMagFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item0.AddGrowableCol( 0 )
    item0.AddGrowableRow( 0 )
    
    item1 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item1.AddGrowableCol( 0 )
    item1.AddGrowableRow( 2 )
    
    item2 = wx.FlexGridSizer( 1, 0, 0, 0 )
    item2.AddGrowableCol( 0 )
    
    item4 = wx.StaticBox( parent, -1, "Selezioni" )
    item3 = wx.StaticBoxSizer( item4, wx.VERTICAL )
    
    item5 = wx.FlexGridSizer( 0, 2, 0, 0 )
    item5.AddGrowableCol( 0 )
    item5.AddGrowableCol( 1 )
    
    item6 = wx.StaticText( parent, ID_LABMASMAG, "Magazzino:", wx.DefaultPosition, [160,-1], 0 )
    item5.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item7 = wx.StaticText( parent, ID_LABMASPDC, "Sottoconto:", wx.DefaultPosition, [160,-1], 0 )
    item5.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item8 = LinkTable(parent, ID_MASID_MAGAZZ ); item8.SetDataLink( bt.TABNAME_MAGAZZ, "masid_magazz", MagazzDialog)
    item5.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item9 = LinkTable(parent, ID_MASID_PDC ); item9.SetDataLink( bt.TABNAME_PDC, "masid_pdc", None)
    item5.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item10 = wx.StaticText( parent, ID_LABMASPDC, "Documento:", wx.DefaultPosition, [160,-1], 0 )
    item5.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item11 = wx.StaticText( parent, ID_LABMASMOV, "Movimento:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item12 = LinkTable(parent, ID_MASID_TIPDOC ); item12.SetDataLink( bt.TABNAME_CFGMAGDOC, "masid_tipdoc", None)
    item5.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item13 = LinkTable(parent, ID_MASID_TIPMOV ); item13.SetDataLink( bt.TABNAME_CFGMAGMOV, "masid_tipmov", None)
    item5.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item14 = wx.StaticText( parent, ID_LABMASMOV, "Prodotto:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item15 = wx.StaticText( parent, ID_LABMASAGE, "Agente:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item16 = LinkTableProd(parent, ID_MASID_PROD, "masid_prod")
    item5.Add( item16, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item17 = LinkTable(parent, ID_MASID_AGENTE ); item17.SetDataLink( bt.TABNAME_AGENTI, "masid_agente", AgentiDialog)
    item5.Add( item17, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item3.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item18 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item19 = wx.StaticText( parent, ID_TEXT, "Escludi:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item18.Add( item19, 0, wx.ALIGN_CENTER, 5 )

    item20 = wx.CheckBox( parent, ID_NODOCANN, "Doc. annullati", wx.DefaultPosition, wx.DefaultSize, 0 )
    item20.SetValue( True )
    item20.SetName( "escdocann" )
    item18.Add( item20, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item21 = wx.CheckBox( parent, ID_NODOCACQ, "Doc. acquisiti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item21.SetValue( True )
    item21.SetName( "escdocacq" )
    item18.Add( item21, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item22 = wx.CheckBox( parent, ID_NOMOVANN, "Mov. annullati", wx.DefaultPosition, wx.DefaultSize, 0 )
    item22.SetValue( True )
    item22.SetName( "escmovann" )
    item18.Add( item22, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item3.Add( item18, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item2.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP, 5 )

    item23 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item24 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item26 = wx.StaticBox( parent, -1, "Periodo" )
    item25 = wx.StaticBoxSizer( item26, wx.VERTICAL )
    
    item27 = wx.FlexGridSizer( 0, 5, 0, 0 )
    item27.AddGrowableCol( 0 )
    
    item28 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item27.Add( item28, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item29 = wx.StaticText( parent, ID_LABMASNUM1, "Da numero:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item27.Add( item29, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item30 = wx.StaticText( parent, ID_LABMASDAT1, "Da data:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item27.Add( item30, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item31 = wx.StaticText( parent, ID_LABMASNUM2, "A numero:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item27.Add( item31, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item32 = wx.StaticText( parent, ID_LABMASDAT2, "A data:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item27.Add( item32, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item33 = wx.StaticText( parent, ID_LABMASDOC, "Documento", wx.DefaultPosition, wx.DefaultSize, wx.ST_NO_AUTORESIZE|wx.ALIGN_RIGHT )
    item27.Add( item33, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item34 = TextCtrl( parent, ID_MASNUMDOC1, "", wx.DefaultPosition, [60,-1], 0 )
    item34.SetName( "masnumdoc1" )
    item27.Add( item34, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item35 = DateCtrl( parent, ID_MASDATDOC1, "", wx.DefaultPosition, [80,-1], 0 )
    item35.SetName( "masdatdoc1" )
    item27.Add( item35, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item36 = TextCtrl( parent, ID_MASNUMDOC2, "", wx.DefaultPosition, [60,-1], 0 )
    item36.SetName( "masnumdoc2" )
    item27.Add( item36, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item37 = DateCtrl( parent, ID_MASDATDOC2, "", wx.DefaultPosition, [80,-1], 0 )
    item37.SetName( "masdatdoc2" )
    item27.Add( item37, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item38 = wx.StaticText( parent, ID_LABMASREG, "Registrazione", wx.DefaultPosition, wx.DefaultSize, wx.ST_NO_AUTORESIZE|wx.ALIGN_RIGHT )
    item27.Add( item38, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item39 = TextCtrl( parent, ID_MASNUMREG1, "", wx.DefaultPosition, [60,-1], 0 )
    item39.SetName( "masnumreg1" )
    item27.Add( item39, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item40 = DateCtrl( parent, ID_MASDATREG1, "", wx.DefaultPosition, [80,-1], 0 )
    item40.SetName( "masdatreg1" )
    item27.Add( item40, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item41 = TextCtrl( parent, ID_MASNUMREG2, "", wx.DefaultPosition, [60,-1], 0 )
    item41.SetName( "masnumreg2" )
    item27.Add( item41, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item42 = DateCtrl( parent, ID_MASDATREG2, "", wx.DefaultPosition, [80,-1], 0 )
    item42.SetName( "masdatreg2" )
    item27.Add( item42, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item43 = wx.StaticText( parent, ID_LABMASRIF, "Riferimento", wx.DefaultPosition, wx.DefaultSize, wx.ST_NO_AUTORESIZE|wx.ALIGN_RIGHT )
    item27.Add( item43, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.TOP, 5 )

    item44 = TextCtrl( parent, ID_MASNUMRIF1, "", wx.DefaultPosition, [60,-1], 0 )
    item44.SetName( "masnumrif1" )
    item27.Add( item44, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item45 = DateCtrl( parent, ID_MASDATRIF1, "", wx.DefaultPosition, [80,-1], 0 )
    item45.SetName( "masdatrif1" )
    item27.Add( item45, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item46 = TextCtrl( parent, ID_MASNUMRIF2, "", wx.DefaultPosition, [60,-1], 0 )
    item46.SetName( "masnumrif2" )
    item27.Add( item46, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item47 = DateCtrl( parent, ID_MASDATRIF2, "", wx.DefaultPosition, [80,-1], 0 )
    item47.SetName( "masdatrif2" )
    item27.Add( item47, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item25.Add( item27, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item24.Add( item25, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item48 = wx.BoxSizer( wx.VERTICAL )
    
    item49 = wx.Button( parent, ID_MASBUTUPD, "Applica", wx.DefaultPosition, wx.DefaultSize, 0 )
    item49.SetDefault()
    item48.Add( item49, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item50 = wx.Button( parent, ID_MASBUTPRT, "&Lista", wx.DefaultPosition, wx.DefaultSize, 0 )
    item48.Add( item50, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item24.Add( item48, 0, wx.ALIGN_RIGHT|wx.ALIGN_BOTTOM, 5 )

    item23.Add( item24, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item52 = wx.StaticBox( parent, -1, "Stato di evasione" )
    item51 = wx.StaticBoxSizer( item52, wx.HORIZONTAL )
    
    item53 = wx.CheckBox( parent, ID_EVAPARZ, "Da evadere parzialmente", wx.DefaultPosition, wx.DefaultSize, 0 )
    item53.SetValue( True )
    item53.SetName( "evaparz" )
    item51.Add( item53, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item54 = wx.CheckBox( parent, ID_EVANONE, "Da evadere totalmente (mai evasi)", wx.DefaultPosition, wx.DefaultSize, 0 )
    item54.SetValue( True )
    item54.SetName( "evanone" )
    item51.Add( item54, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item55 = wx.CheckBox( parent, ID_EVACHIUSI, "Totalmente evasi (chiusi)", wx.DefaultPosition, wx.DefaultSize, 0 )
    item55.SetName( "evachiusi" )
    item51.Add( item55, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item23.Add( item51, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item2.Add( item23, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item1.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item56 = wx.StaticText( parent, ID_TEXT, "Movimenti presenti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item56.SetForegroundColour( wx.BLUE )
    item1.Add( item56, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item57 = wx.Panel( parent, ID_PANGRIDMOV, wx.DefaultPosition, [-1,240], wx.SUNKEN_BORDER )
    item1.Add( item57, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item59 = wx.StaticBox( parent, -1, "Totali" )
    item58 = wx.StaticBoxSizer( item59, wx.VERTICAL )
    
    item60 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item61 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item62 = wx.StaticText( parent, ID_LABMASTOTDOCQ, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item61.Add( item62, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item63 = wx.StaticText( parent, ID_LABMASTOTDOCQ, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item61.Add( item63, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item64 = wx.StaticText( parent, ID_LABMASMOV, "Numero di movimenti:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item61.Add( item64, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item65 = NumCtrl(parent, integerWidth=6, fractionWidth=0); item65.SetName("mastotnummov"); item65.SetEditable(False)
    item61.Add( item65, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item60.Add( item61, 0, wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item66 = wx.FlexGridSizer( 0, 3, 0, 0 )
    
    item67 = wx.StaticText( parent, ID_LABMASTOTDOCQ, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item66.Add( item67, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item68 = wx.StaticText( parent, ID_LABMASTOTDOCQ, "Quantità", wx.DefaultPosition, wx.DefaultSize, 0 )
    item66.Add( item68, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item69 = wx.StaticText( parent, ID_LABMASTOTDOCV, "Importo", wx.DefaultPosition, wx.DefaultSize, 0 )
    item66.Add( item69, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item70 = wx.StaticText( parent, ID_LABMASMOV, "Movimenti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item66.Add( item70, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item71 = bt.GetMagQtaNumCtrl(parent, ID_MASTOTDOCQ, 'mastotdocq', editable=False)
    item66.Add( item71, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item72 = bt.GetValIntNumCtrl(parent, ID_MASTOTDOCV, 'mastotdocv', editable=False)
    item66.Add( item72, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item73 = wx.StaticText( parent, ID_LABMASACQ, "Evaso", wx.DefaultPosition, wx.DefaultSize, 0 )
    item66.Add( item73, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item74 = bt.GetMagQtaNumCtrl(parent, ID_MASTOTACQQ, 'mastotacqq', editable=False)
    item66.Add( item74, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item75 = bt.GetValIntNumCtrl(parent, ID_MASTOTACQV, 'mastotacqv', editable=False)
    item66.Add( item75, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item76 = wx.StaticText( parent, ID_LABMASRES, "Residuo", wx.DefaultPosition, wx.DefaultSize, 0 )
    item66.Add( item76, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item77 = bt.GetMagQtaNumCtrl(parent, ID_MASTOTRESQ, 'mastotresq', editable=False)
    item66.Add( item77, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item78 = bt.GetValIntNumCtrl(parent, ID_MASTOTRESV, 'mastotresv', editable=False)
    item66.Add( item78, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item60.Add( item66, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item58.Add( item60, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item58, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_TIPDOC = 14075
ID_NUMDOC = 14076
ID_DATDOC = 14077
ID_PDC = 14078
ID_NUMRIF = 14079
ID_DATRIF = 14080
ID_PANGRIDMOVEVA = 14081

def VediEvasioniFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item0.AddGrowableCol( 0 )
    
    item2 = wx.StaticBox( parent, -1, "Documento evaso" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    
    item3 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item3.AddGrowableCol( 0 )
    
    item4 = wx.FlexGridSizer( 0, 3, 0, 0 )
    item4.AddGrowableCol( 0 )
    
    item5 = wx.StaticText( parent, ID_TEXT, "Documento:", wx.DefaultPosition, [70,-1], 0 )
    item4.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP, 5 )

    item6 = wx.StaticText( parent, ID_TEXT, "Num.", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item4.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item7 = wx.StaticText( parent, ID_TEXT, "Data:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP, 5 )

    item8 = LinkTable(parent, ID_TIPDOC); item8.SetDataLink(bt.TABNAME_CFGMAGDOC, "id_tipdoc", None)
    item4.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item9 = NumCtrl( parent, integerWidth=6); item9.SetName("numdoc"); item9.SetEditable(False)
    item4.Add( item9, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item10 = DateCtrl( parent, ID_DATDOC, "", wx.DefaultPosition, [80,-1], 0 )
    item10.SetName( "datdoc" )
    item4.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item3.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item11 = wx.FlexGridSizer( 0, 3, 0, 0 )
    item11.AddGrowableCol( 0 )
    
    item12 = wx.StaticText( parent, ID_TEXT, "Anagrafica:", wx.DefaultPosition, [70,-1], 0 )
    item11.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP, 5 )

    item13 = wx.StaticText( parent, ID_TEXT, "Rif.", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item11.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item14 = wx.StaticText( parent, ID_TEXT, "Data:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item11.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP, 5 )

    item15 = LinkTable(parent, ID_PDC); item15.SetDataLink(bt.TABNAME_PDC, "id_pdc", None)
    item11.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item16 = TextCtrl(parent, ID_NUMRIF); item16.SetName("numrif"); item16.SetEditable(False)
    item11.Add( item16, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item17 = DateCtrl( parent, ID_DATRIF, "", wx.DefaultPosition, [80,-1], 0 )
    item17.SetName( "datrif" )
    item11.Add( item17, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item3.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item18 = wx.StaticText( parent, ID_TEXT, "Dettaglio righe", wx.DefaultPosition, wx.DefaultSize, 0 )
    item18.SetForegroundColour( wx.BLUE )
    item0.Add( item18, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item19 = wx.Panel( parent, ID_PANGRIDMOVEVA, wx.DefaultPosition, [800,400], wx.SUNKEN_BORDER )
    item0.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_MASID_ZONA = 14082

def MovMagFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item0.AddGrowableCol( 0 )
    item0.AddGrowableRow( 2 )
    
    item1 = wx.FlexGridSizer( 1, 0, 0, 0 )
    item1.AddGrowableCol( 0 )
    
    item3 = wx.StaticBox( parent, -1, "Selezioni sui documenti" )
    item2 = wx.StaticBoxSizer( item3, wx.VERTICAL )
    
    item4 = wx.FlexGridSizer( 0, 2, 0, 0 )
    item4.AddGrowableCol( 0 )
    item4.AddGrowableCol( 1 )
    
    item5 = wx.StaticText( parent, ID_LABMASMAG, "Magazzino:", wx.DefaultPosition, [160,-1], 0 )
    item4.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item6 = wx.StaticText( parent, ID_LABMASPDC, "Sottoconto:", wx.DefaultPosition, [160,-1], 0 )
    item4.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item7 = LinkTableMagazz(parent, ID_MASID_MAGAZZ, "masid_magazz")
    item4.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item8 = LinkTablePdc(parent, ID_MASID_PDC, "masid_pdc")
    item4.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item9 = wx.StaticText( parent, ID_LABMASDOC, "Documento:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item10 = wx.StaticText( parent, ID_LABMASMOV, "Movimento:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item11 = LinkTableDocMagazz(parent, ID_MASID_TIPDOC, "masid_tipdoc")
    item4.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item12 = LinkTableMovMagazz(parent, ID_MASID_TIPMOV, "masid_tipmov")
    item4.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item13 = wx.StaticText( parent, ID_LABMASAGE, "Agente:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item14 = wx.StaticText( parent, ID_LABMASAGE, "Zona:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item15 = LinkTableAgente(parent, ID_MASID_AGENTE, "masid_agente")
    item4.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item16 = LinkTableZona(parent, ID_MASID_ZONA, "masid_zona")
    item4.Add( item16, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item17 = wx.StaticText( parent, ID_LABMASMOV, "Prodotto:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item17, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item18 = wx.StaticText( parent, ID_LABMASIVA, "Aliquota IVA", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item18, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item19 = LinkTableProd(parent, ID_MASID_PROD, "masid_prod")
    item4.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item20 = LinkTableAliqIva(parent, ID_MASID_ALIQIVA, "masid_aliqiva")
    item4.Add( item20, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item2.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item21 = wx.StaticText( parent, ID_LABMASMOV, "Descrizione libera (contenuto):", wx.DefaultPosition, wx.DefaultSize, 0 )
    item2.Add( item21, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item22 = wx.FlexGridSizer( 1, 0, 0, 0 )
    item22.AddGrowableCol( 0 )
    
    item23 = wx.TextCtrl( parent, ID_MASDESCRIZ, "", wx.DefaultPosition, [80,-1], 0 )
    item23.SetName( "masdescriz" )
    item22.Add( item23, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item24 = wx.CheckBox( parent, ID_SOLOPRMANCA, "Solo righe con prezzo mancante", wx.DefaultPosition, wx.DefaultSize, 0 )
    item24.SetName( "soloprmanca" )
    item22.Add( item24, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item2.Add( item22, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item25 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item26 = wx.StaticText( parent, ID_TEXT, "Escludi:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item25.Add( item26, 0, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item27 = wx.CheckBox( parent, ID_NODOCANN, "Doc. annullati", wx.DefaultPosition, wx.DefaultSize, 0 )
    item27.SetValue( True )
    item27.SetName( "escdocann" )
    item25.Add( item27, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item28 = wx.CheckBox( parent, ID_NODOCACQ, "Doc. acquisiti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item28.SetValue( True )
    item28.SetName( "escdocacq" )
    item25.Add( item28, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item29 = wx.CheckBox( parent, ID_NOMOVANN, "Mov. annullati", wx.DefaultPosition, wx.DefaultSize, 0 )
    item29.SetValue( True )
    item29.SetName( "escmovann" )
    item25.Add( item29, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item2.Add( item25, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item1.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item30 = wx.FlexGridSizer( 0, 1, 0, 0 )
    item30.AddGrowableRow( 1 )
    
    item32 = wx.StaticBox( parent, -1, "Periodo" )
    item31 = wx.StaticBoxSizer( item32, wx.VERTICAL )
    
    item33 = wx.FlexGridSizer( 0, 5, 0, 0 )
    item33.AddGrowableCol( 0 )
    
    item34 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item33.Add( item34, 0, wx.ALIGN_CENTER|wx.TOP, 5 )

    item35 = wx.StaticText( parent, ID_LABMASNUM1, "Da numero:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item33.Add( item35, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP, 5 )

    item36 = wx.StaticText( parent, ID_LABMASDAT1, "Da data:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item33.Add( item36, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP, 5 )

    item37 = wx.StaticText( parent, ID_LABMASNUM2, "A numero:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item33.Add( item37, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP, 5 )

    item38 = wx.StaticText( parent, ID_LABMASDAT2, "A data:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item33.Add( item38, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP, 5 )

    item39 = wx.StaticText( parent, ID_LABMASDOC, "Documento", wx.DefaultPosition, wx.DefaultSize, wx.ST_NO_AUTORESIZE|wx.ALIGN_RIGHT )
    item33.Add( item39, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item40 = TextCtrl( parent, ID_MASNUMDOC1, "", wx.DefaultPosition, [60,-1], 0 )
    item40.SetName( "masnumdoc1" )
    item33.Add( item40, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item41 = DateCtrl( parent, ID_MASDATDOC1, "", wx.DefaultPosition, [80,-1], 0 )
    item41.SetName( "masdatdoc1" )
    item33.Add( item41, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item42 = TextCtrl( parent, ID_MASNUMDOC2, "", wx.DefaultPosition, [60,-1], 0 )
    item42.SetName( "masnumdoc2" )
    item33.Add( item42, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item43 = DateCtrl( parent, ID_MASDATDOC2, "", wx.DefaultPosition, [80,-1], 0 )
    item43.SetName( "masdatdoc2" )
    item33.Add( item43, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item44 = wx.StaticText( parent, ID_LABMASREG, "Registrazione", wx.DefaultPosition, wx.DefaultSize, wx.ST_NO_AUTORESIZE|wx.ALIGN_RIGHT )
    item33.Add( item44, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item45 = TextCtrl( parent, ID_MASNUMREG1, "", wx.DefaultPosition, [60,-1], 0 )
    item45.SetName( "masnumreg1" )
    item33.Add( item45, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item46 = DateCtrl( parent, ID_MASDATREG1, "", wx.DefaultPosition, [80,-1], 0 )
    item46.SetName( "masdatreg1" )
    item33.Add( item46, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item47 = TextCtrl( parent, ID_MASNUMREG2, "", wx.DefaultPosition, [60,-1], 0 )
    item47.SetName( "masnumreg2" )
    item33.Add( item47, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item48 = DateCtrl( parent, ID_MASDATREG2, "", wx.DefaultPosition, [80,-1], 0 )
    item48.SetName( "masdatreg2" )
    item33.Add( item48, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item49 = wx.StaticText( parent, ID_LABMASRIF, "Riferimento", wx.DefaultPosition, wx.DefaultSize, wx.ST_NO_AUTORESIZE|wx.ALIGN_RIGHT )
    item33.Add( item49, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.TOP, 5 )

    item50 = TextCtrl( parent, ID_MASNUMRIF1, "", wx.DefaultPosition, [60,-1], 0 )
    item50.SetName( "masnumrif1" )
    item33.Add( item50, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item51 = DateCtrl( parent, ID_MASDATRIF1, "", wx.DefaultPosition, [80,-1], 0 )
    item51.SetName( "masdatrif1" )
    item33.Add( item51, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item52 = TextCtrl( parent, ID_MASNUMRIF2, "", wx.DefaultPosition, [60,-1], 0 )
    item52.SetName( "masnumrif2" )
    item33.Add( item52, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item53 = DateCtrl( parent, ID_MASDATRIF2, "", wx.DefaultPosition, [80,-1], 0 )
    item53.SetName( "masdatrif2" )
    item33.Add( item53, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item31.Add( item33, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item30.Add( item31, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item54 = wx.FlexGridSizer( 1, 0, 0, 0 )
    item54.AddGrowableRow( 0 )
    
    item55 = TipOrdinamRadioBox( parent, ID_TIPORD, "Ordina per:", wx.DefaultPosition, wx.DefaultSize, 
        ["Data, Tipo documento, Numero","Anagrafica, Data, Tipo documento, Numero","Tipo documento, Anno, Numero","Tipo documento, Anagrafica, Anno, Numero"] , 1, wx.RA_SPECIFY_COLS )
    item55.SetName( "tipord" )
    item54.Add( item55, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL|wx.RIGHT, 5 )

    item56 = wx.BoxSizer( wx.VERTICAL )
    
    item57 = wx.Button( parent, ID_MASBUTUPD, "Applica", wx.DefaultPosition, wx.DefaultSize, 0 )
    item57.SetDefault()
    item56.Add( item57, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item58 = wx.Button( parent, ID_MASBUTPRT, "&Lista", wx.DefaultPosition, wx.DefaultSize, 0 )
    item56.Add( item58, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item54.Add( item56, 0, wx.ALIGN_RIGHT|wx.ALIGN_BOTTOM, 5 )

    item30.Add( item54, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item1.Add( item30, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item59 = wx.StaticText( parent, ID_TEXT, "Movimenti presenti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item59.SetForegroundColour( wx.BLUE )
    item0.Add( item59, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item60 = wx.Panel( parent, ID_PANGRIDMOV, wx.DefaultPosition, [-1,180], wx.SUNKEN_BORDER )
    item0.Add( item60, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item61 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item63 = wx.StaticBox( parent, -1, "Totali generali dei movimenti" )
    item62 = wx.StaticBoxSizer( item63, wx.VERTICAL )
    
    item64 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item65 = wx.StaticText( parent, ID_TEXT, "Movimenti estratti:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item64.Add( item65, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item66 = NumCtrl(parent, integerWidth=8); item66.SetName("totnummov"); item66.SetEditable(False)
    item64.Add( item66, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item67 = wx.StaticText( parent, ID_LABTOTIMPORTO, "Tot.Importo:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item64.Add( item67, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item68 = bt.GetValIntNumCtrl(parent, ID_TOTIMPORTO, 'totimporto', editable=False)
    item64.Add( item68, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item62.Add( item64, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item61.Add( item62, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.LEFT|wx.BOTTOM, 5 )

    item70 = wx.StaticBox( parent, -1, "Merce e servizi" )
    item69 = wx.StaticBoxSizer( item70, wx.VERTICAL )
    
    item71 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item72 = wx.StaticText( parent, ID_TEXT, "Tot.Merce:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item71.Add( item72, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item73 = bt.GetValIntNumCtrl(parent, ID_TOTMERCE, 'totimpmerce', editable=False)
    item71.Add( item73, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item74 = wx.StaticText( parent, ID_TEXT, "Tot.Servizi:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item71.Add( item74, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item75 = bt.GetValIntNumCtrl(parent, ID_TOTSERVI, 'totimpservi', editable=False)
    item71.Add( item75, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item69.Add( item71, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item61.Add( item69, 0, wx.LEFT|wx.BOTTOM, 5 )

    item77 = wx.StaticBox( parent, -1, "Addebiti" )
    item76 = wx.StaticBoxSizer( item77, wx.VERTICAL )
    
    item78 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item79 = wx.StaticText( parent, ID_LABTOTSPESE, "Spese:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item78.Add( item79, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item80 = bt.GetValIntNumCtrl(parent, ID_TOTSPESE, 'totimpspese', editable=False)
    item78.Add( item80, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item81 = wx.StaticText( parent, ID_LABTOTSPESE, "Trasporti:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item78.Add( item81, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item82 = bt.GetValIntNumCtrl(parent, ID_TOTTRASP, 'totimptrasp', editable=False)
    item78.Add( item82, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item76.Add( item78, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item61.Add( item76, 0, wx.LEFT|wx.BOTTOM, 5 )

    item84 = wx.StaticBox( parent, -1, "Sconti praticati" )
    item83 = wx.StaticBoxSizer( item84, wx.VERTICAL )
    
    item85 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item86 = wx.StaticText( parent, ID_LABTOTSCRIP, "Sconti ripartiti:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item85.Add( item86, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item87 = bt.GetValIntNumCtrl(parent, ID_TOTSCRIP, 'totimpscrip', editable=False)
    item85.Add( item87, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item88 = wx.StaticText( parent, ID_LABTOTSCM, "Sconti in merce:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item85.Add( item88, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item89 = bt.GetValIntNumCtrl(parent, ID_TOTSCMCE, 'totimpscmce', editable=False)
    item85.Add( item89, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item90 = wx.StaticText( parent, ID_LABTOTOMG, "Omaggi:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item85.Add( item90, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item91 = bt.GetValIntNumCtrl(parent, ID_TOTOMAGG, 'totimpomagg', editable=False)
    item85.Add( item91, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item83.Add( item85, 0, wx.ALIGN_CENTER, 5 )

    item61.Add( item83, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.Add( item61, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
